hyperledger/iroha

.gitmodules

Fix git submodule

---

README.md
core/validation/transaction_validator.hpp

Updating the docs for the steps needed on a fresh setup.

Documentation update for setup and a small compile fix

---

core/consensus/sumeragi.cpp
core/infra/service/peer_service_with_json.cpp
core/util/use_optional.hpp

Call exit(EXIT_FAILURE) when opening sumeragi.json file error occurred.

Add termination when not found sumeragi.json

---

test/consensus/CMakeLists.txt

As discussed in issue https://github.com/hyperledger/iroha/issues/157, I launched a pull request.
here is my certification

add leveldb linking setting for sumeragi_test

---

test/connection/connection_with_grpc_test.cpp

Second ConnectionWithGrpcTorii should be dead.

Fix test segv

---

benchmark/crypto/CMakeLists.txt
benchmark/crypto/base64.cpp
core/consensus/sumeragi.cpp

- base64 implementation updated
- setAwkTimer updated, now it does not create threads with each call
- hash benchmark added

Update setAwkTimer and base64

---

core/repository/consensus/merkle_transaction_repository.cpp

Comment out infinite loop

---

core/crypto/signature.hpp
core/infra/connection/connection_with_grpc.cpp
core/infra/crypto/signature.cpp

can be related to #223
~~work still in progress, plz don't merge~~

Remove redundant allocation in signatures

---

docs/how_to_build.rst

You need ssl.h < libssl-dev
You need java.
'make' is expected to run automatically, but it doesn't.

added some procedure into how to build

---

docker/README.md

better to add -it option.
better to add port binding option (but as you like)

modify README

---

core/service/executor.cpp
test/scenario/virtual_currency_test.cpp

Fix update asset logic

---

tools/make_sumeragi.cpp

getopt function in make_sumeragi.cpp return value should be int rather than char.

getopt return value should be int rather than char.

---

core/infra/config/abstract_config_manager.hpp
core/infra/config/iroha_config_with_json.cpp
core/infra/config/iroha_config_with_json.hpp
core/infra/config/peer_service_with_json.cpp
core/infra/config/peer_service_with_json.hpp

https://github.com/hyperledger/iroha/issues/257

Abstract_config_manager can work with hierarchical configurations now

---

docker/README.md
docker/build_in_docker.sh
docker/dev/README.md

This script is almost same to build.sh.
The difference is to run the build inside the docker container.

Add build script to build the iroha inside the docker container using iroha-dev.

---

schema/commands.fbs

Change PeerRemove in `commands.fbs`

fix commnands.fbs latest

---

core/infra/ametsuchi/include/ametsuchi/ametsuchi.h
core/infra/ametsuchi/include/ametsuchi/currency.h
core/infra/ametsuchi/include/ametsuchi/wsv.h
core/infra/ametsuchi/src/ametsuchi/ametsuchi.cc
core/infra/ametsuchi/src/ametsuchi/currency.cc
core/infra/ametsuchi/src/ametsuchi/wsv.cc

fix compile error asset operate in wsv

---

core/utils/logger.cpp
core/utils/logger.hpp

I debugged logger. ( Issue #327 )
Would you review it?

debug about setLogLevel, fixes #327

---

core/utils/exception.hpp

I debugged UndefinedIrohaHomeException.
Would you review it?

debug about UndefinedIrohaHomeException

---

schema/asset.proto
schema/block.proto
schema/commands.proto
schema/primitive.proto

Add protobuf's scheme.
3.3.0
- transaction header contains  a version number
https://github.com/hyperledger/iroha/compare/mvp-base...feature/mvp/add-scheme?expand=1#diff-20668a62f9784b9d6011379ec2f56285R10
- the package name is `iroha.protocol;`

Add scheme files

---

libs/dao/transaction.hpp

Vector should contain pointers to allow storing objects of derived classes

Fix abstract command in transaction

---

libs/dao/CMakeLists.txt
libs/dao/queries/get_blocks.hpp
libs/dao/queries/responses/blocks_response.hpp
libs/dao/queries/responses/error_response.hpp

Data object for query get blocks
Client will form query to ametsuchi not depended on transport

Dao query get blocks

---

irohad/consensus/sumeragi.cpp
irohad/ordering/queue.cpp
schema/block.proto
schema/commands.proto
schema/queries.proto
schema/responses.proto

Updating obsolete proto files to be consistent with model

Update proto files

---

irohad/ametsuchi/impl/storage_impl.hpp
irohad/validation/impl/stateful_validator_impl.cpp

Iroha's build fix on some environments (at least in my local one)
Because I need a working Iroha (and other people who possibly may also face this issue too)
Just build Iroha as usual.
Added two missed includes: <numeric> for std::accumulate and <cmath> for std::abs.

Fix Iroha's build on some environments (missed includes)

---

libs/common/test_observable.hpp
test/libs/CMakeLists.txt
test/libs/common/CMakeLists.txt
test/libs/common/test_observable_testing.cpp

This pr provide feature for testing subscribtions in terms of rxcpp
This PR will be useful for testing observables, because rxcpp doesn't provide testing features for it.
Usage:
1. Wrap observable
2. use method `test_subscriber` with own invariant
3. check invariant with `validate` method.
More about usage [here](https://github.com/hyperledger/iroha/blob/feature/test-observable/test/libs/common/test_observable_testing.cpp)
Also, implement only invariant for checking exact number of calls on subscriber. Use base class - `VerificationStrategy`, for implement own invariants.

Add TestObservable class;

---

.circleci/config.yml

Commenting out coverage report SH script
In now, coverage reports are not meaningful since they are flooding PR discussion

Comment out coverage report

---

README.md

Update of README file with dates of release

Update README with current status

---

irohad/model/converters/impl/json_query_factory.cpp

Add json type check in json_query_factory.
To avoid rapidjson's assertion in query_factory when json format is wrong.

Add type check in json_query_factory

---

test/libs/CMakeLists.txt

Fixes linkage error caused by primitiveproto_h static library

Fix linkage error

---

irohad/consensus/yac/impl/yac.cpp
irohad/consensus/yac/yac.hpp

This pr provide locks in consensus for prevent race conditions.
Race conditions in consensus may generate bugs related to multi commit and other strange and unexpected behaviour. This implementation provide lock based solution on `lock_guard`s.

Add locks to consensus

---

MAINTAINERS.md

Update of maintainers list
Previously, list of maintainers did not contain developer and had typo in GitHub name of our maintainer.

Update of maintainers list

---

docker/docker-compose.yml
scripts/run-iroha-dev.sh

Fix test failures due to static postgres and redis host environment variables

Add support for dynamic docker project name

---

irohad/consensus/yac/impl/network_impl.cpp
irohad/consensus/yac/impl/network_impl.hpp
irohad/consensus/yac/impl/yac.cpp
irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/consensus/yac/impl/yac_hash_provider_impl.cpp
irohad/consensus/yac/storage/impl/yac_block_storage.cpp
irohad/consensus/yac/storage/impl/yac_proposal_storage.cpp
irohad/consensus/yac/storage/yac_block_storage.hpp
irohad/consensus/yac/storage/yac_proposal_storage.hpp
irohad/consensus/yac/yac.hpp
test/module/irohad/consensus/yac/yac_hash_provider_test.cpp

This pr provides logging for yac and for yac network.
All in case, just look for output when use consensus.

Add logging for yac and yac network;

---

irohad/model/execution/command_executor.hpp
irohad/model/execution/impl/command_executor.cpp

This pr provides logging in command executor.
Functionality gives useful information about fail case on stateful validation in system.
* Logging in command executor
* Rework unused variable
* Replace logic symbols (&& ||) with modern
* Little style refactoring

Add logging to command executor

---

test/module/irohad/ordering/ordering_gate_service_test.cpp
test/module/irohad/ordering/ordering_service_test.cpp

Replacing calls std::this_thread::sleep with subsriber callbacks + mutexes

Removing RC in ordering tests

---

.gitignore
scripts/build-local-image.sh
scripts/build-test-swarm.sh
scripts/swarm-deploy.sh

Add:
- Building local image
- Building test swarm
Besides add absolute path to swarm-deploy due to some issues

Add docker scripts

---

irohad/main/application.cpp
irohad/main/application.hpp
irohad/model/peer.hpp

This pr provide reworking of initialization: all internal dependencies may be changed with inherited classes.
This pr very useful in tests, because current implementation not support testing: all dependencies initialize in one function and can not be changes for test purposes.
Inherit from application and change dependencies for your purposes.

Initialization bundle

---

irohad/ametsuchi/impl/storage_impl.cpp

Fix issue with commit not finishing due to lock in mutable storage creation.

Fix synchronizer lock when creating mutable storage

---

irohad/main/application.cpp
irohad/main/irohad.cpp

Fix initialization in the production run of Iroha.

Fix bugs in initialization bundle

---

README.md

Just added a link to docs in the readme.

add link to docs

---

cmake/Modules/Findgrpc.cmake
irohad/ametsuchi/impl/postgres_wsv_command.cpp

fixed grpc patch command and added missing headers

added numeric header for std::accumulate

---

iroha-cli/main.cpp
irohad/main/application.cpp
irohad/main/application.hpp
irohad/main/irohad.cpp
irohad/model/generators/CMakeLists.txt
irohad/model/generators/block_generator.hpp
irohad/model/generators/impl/block_generator.cpp
irohad/model/generators/impl/transaction_generator.cpp
irohad/model/generators/transaction_generator.hpp
irohad/validation/impl/stateful_validator_impl.cpp
libs/crypto/CMakeLists.txt
test/integration/pipeline/tx_pipeline_integration_test.cpp

Keypair for node can be specified with flag `keypair_name`

Use keypair for node id, create keypair when generating genesis block

---

iroha-cli/interactive/impl/interactive_transaction_cli.cpp
irohad/ametsuchi/impl/postgres_wsv_command.cpp
irohad/ametsuchi/impl/postgres_wsv_command.hpp
irohad/ametsuchi/impl/postgres_wsv_query.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/ametsuchi/wsv_command.hpp
irohad/model/commands/create_role.hpp
irohad/model/converters/impl/json_command_factory.cpp
irohad/model/converters/impl/pb_command_factory.cpp
irohad/model/converters/impl/pb_query_response_factory.cpp
irohad/model/converters/pb_command_factory.hpp
irohad/model/execution/impl/command_executor.cpp
irohad/model/generators/command_generator.hpp
irohad/model/generators/impl/block_generator.cpp
irohad/model/generators/impl/command_generator.cpp
irohad/model/generators/impl/transaction_generator.cpp
irohad/model/permissions.hpp
test/integration/pipeline/tx_pipeline_integration_test.cpp
test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
test/module/irohad/ametsuchi/wsv_query_command_test.cpp
test/module/irohad/model/command_validate_execute_test.cpp
test/module/irohad/model/converters/json_commands_test.cpp
test/module/irohad/model/converters/pb_commands_test.cpp

Add new permission model to interactive cli

Add create role to interactive cli

---

deploy/ansible/hosts
deploy/ansible/provisioning.yml
deploy/ansible/setup.yml

Added Ansible playbook that installs docker, adds user to the group and starts docker

Ansible install docker

---

.gitignore
CMakeLists.txt
cmake/Modules/Findbenchmark.cmake
cmake/dependencies.cmake
test/CMakeLists.txt
test/benchmark/CMakeLists.txt
test/benchmark/benchmark_example.cpp

Add Google Benchmark lib

---

.circleci/config.yml

Fixes `sonar-pr` error in https://github.com/hyperledger/iroha/pull/631

Fix issue when PR from non-maintainers fails sonar-pr

---

deploy/ansible/hosts
deploy/ansible/provisioning.yml

Added tasks for installing docker-py, postgres, redis. 
Added random postgres password for each host
Run iroha inside docker
Private network

Install dependencies for running iroha network

---

.circleci/config.yml
docker/develop/Dockerfile

Mean time for build with cache: 2.30 min
Mean time for build without cache: 11 min

CircleCI improvements

---

irohad/multi_sig_transactions/CMakeLists.txt
irohad/multi_sig_transactions/gossip_propagation_strategy.hpp
irohad/multi_sig_transactions/impl/gossip_propagation_strategy.cpp
test/module/irohad/multi_sig_transactions/CMakeLists.txt
test/module/irohad/multi_sig_transactions/gossip_propagation_strategy_test.cpp

Pull requests should have these details:
This pull request contains basic gossip strategy for propagation (basically emitting next peers for gossiping)
So far there's no comments, I'm going to add them after.
Also there's no explicit dep for current time, that also should be fixed

Add gossip strategy

---

shared_model/interfaces/commands/command.hpp
shared_model/interfaces/common_objects/types.hpp
shared_model/interfaces/queries/get_account.hpp
shared_model/interfaces/queries/get_account_assets.hpp
shared_model/interfaces/queries/get_asset_info.hpp
shared_model/interfaces/queries/get_roles.hpp
shared_model/interfaces/queries/get_signatories.hpp
shared_model/interfaces/queries/get_transactions.hpp
shared_model/interfaces/queries/query.hpp
shared_model/interfaces/query_responses/query_response.hpp
shared_model/interfaces/transaction.hpp

Add query interfaces for the new model
Interfaces allow to implement backend dependent implementation of the model
To use provided interfaces it is required to inherit from them and override their methods
Every query could be signed, thus they need to be hashable

New query interfaces

---

irohad/model/converters/impl/pb_command_factory.cpp
irohad/model/execution/impl/command_executor.cpp
irohad/model/permissions.hpp
schema/primitive.proto
test/module/irohad/model/command_validate_execute_test.cpp

Add grant transfer ability, so that one can transfer assets from other's account.
Add validation in transfer asset to check granted permission. 
Add test two test cases: 
- When creator has granted permission to transfer 
- When creator has no granted permission to transfer

Add grant transfer

---

iroha-cli/impl/query_response_handler.cpp
irohad/model/converters/impl/pb_query_response_factory.cpp
schema/responses.proto

Updates Account model by introducing an additional field with key value data
Updates get account query parsing in CLI
According to POW N 010 we should be able to store key value data about account
Now account has an additional field about data that it stores
Data is stored in json format, new data field has the string type

Update account model

---

irohad/ametsuchi/impl/postgres_wsv_query.cpp
irohad/ametsuchi/impl/postgres_wsv_query.hpp
irohad/ametsuchi/wsv_query.hpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
test/module/irohad/ametsuchi/yuna_storage_test.cpp

Yuna storage integration test
This PR tests yuna functionality allowing putting key:value information about accounts
Check out ametsuchi/yuna_storage_test.cpp
Test creates YunaStorage fixture inserting 2 accounts:
1. One containing predefined json data field
2. Another containing data field set by `SetAccountDetail` method
Then both of them are checked using GetAccountDetail method

Yuna integration test

---

shared_model/interfaces/queries/get_account.hpp
shared_model/interfaces/queries/get_account_assets.hpp
shared_model/interfaces/queries/get_asset_info.hpp
shared_model/interfaces/queries/get_roles.hpp
shared_model/interfaces/queries/get_signatories.hpp
shared_model/interfaces/queries/get_transactions.hpp
shared_model/interfaces/queries/query.hpp

Made concrete queries primitive, not hashable

Primitive query

---

irohad/model/converters/impl/json_transaction_factory.cpp
test/integration/client_test.cpp

This PR implements task https://soramitsu.atlassian.net/browse/IR-603. It adds converter from json to model and vice versa

Add json quorum converters

---

shared_model/bindings/model_builder.cpp
shared_model/bindings/model_builder.hpp
shared_model/builders/protobuf/transaction.hpp
test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp

Small fix of wrong method name (assetQuantity->addAssetQuantity).

Fix name assetQuantity -> addAssetQuantity

---

irohad/model/commands/subtract_asset_quantity.hpp
irohad/model/converters/impl/json_command_factory.cpp
irohad/model/converters/impl/pb_command_factory.cpp
irohad/model/converters/json_command_factory.hpp
irohad/model/converters/pb_command_factory.hpp
irohad/model/execution/command_executor.hpp
irohad/model/execution/impl/command_executor.cpp
irohad/model/execution/impl/command_executor_factory.cpp
irohad/model/generators/impl/command_generator.cpp
irohad/model/impl/model_operators.cpp
irohad/model/permissions.hpp
irohad/model/registration/command_registration.hpp
schema/commands.proto
schema/primitive.proto
test/module/irohad/model/command_validate_execute_test.cpp
test/module/irohad/model/converters/json_commands_test.cpp
test/module/irohad/model/converters/pb_commands_test.cpp
test/module/irohad/model/operators/model_operators_test.cpp
test/module/irohad/model/static_map.cpp

Re PR
https://github.com/hyperledger/iroha/pull/742

Support subtract asset quantity command

---

test/module/shared_model/validators/commands_validator_test.cpp

Adds missing checks in commands validator test
To increase code coverage to >80%
Check code coverage using sonar

Improve validator test cov

---

.codecov.yml
cmake/analysis.cmake
sonar-project.properties

- add shared_model folder to sonar analysis
- fixes in analysis steps (CMake)
- changes in codecov

Improve analysis

---

irohad/main/application.cpp
irohad/model/converters/impl/pb_transaction_factory.cpp
irohad/multi_sig_transactions/impl/gossip_propagation_strategy.cpp
test/integration/pipeline/tx_pipeline_integration_test.cpp
test/module/irohad/multi_sig_transactions/gossip_propagation_strategy_test.cpp
test/module/irohad/multi_sig_transactions/mst_test_helpers.hpp
test/module/irohad/multi_sig_transactions/transport_test.cpp

This pr provides fixes for rebased MST trunk and contains following improvements:
* fix for MST transport test
* fix for transaction deserialization
* fix for tx_pipeline_integration test
* fix for gossip propagation strategy

Fix mst transport bugs

---

schema/block.proto

I lost the game of rebase, so I included the change in this branch instead of what I had in #789

Remove ugly space

---

shared_model/bindings/bindings.i
shared_model/bindings/model_query_builder.cpp
shared_model/bindings/model_query_builder.hpp
shared_model/bindings/model_transaction_builder.cpp
shared_model/bindings/model_transaction_builder.hpp
shared_model/builders/protobuf/queries.hpp

Add missing binding for getTransactions query in query builder.

Add getTransactions to model query builder

---

shared_model/bindings/bindings.i

Ignore default ctr generation for Java

---

test/module/shared_model/bindings/QueryTest.java
test/module/shared_model/bindings/builder-test.py
test/module/shared_model/bindings/query-test.py

python and java tests do not pass
Fix tests
Do you provide tests, or use case examples?
Describe how to use features in your pull request.

Fix swig tests

---

.circleci/config.yml

This PR moves codecov report submission out from sonar steps (sonar-pr, sonar-release) to single build step. 
1. single place of report submission
2. now dev should wait a bit less time till report is submitted
None
None.
None.

Codecov submission moved from sonar step to build step

---

shared_model/validators/field_validator.hpp
shared_model/validators/transaction_validator.hpp
test/module/irohad/consensus/yac/network_test.cpp
test/module/shared_model/validators/CMakeLists.txt
test/module/shared_model/validators/field_validator_test.cpp
test/module/shared_model/validators/query_validator_test.cpp
test/module/shared_model/validators/transaction_validator_test.cpp
test/module/shared_model/validators/validators_fixture.hpp

This Pull Request introduces several changes to stateless validation:
1. FieldValidator now returns value of invalid field
2. Amount is checked to be greater than 0
3. CommandsValidator now appends counter to Command name, which allows understanding which command has failed.
The biggest change of this pull request is tests for FieldValidator, which are organized in a table-like manner with various test cases for different fields. Because of a lot of boilerplate, file is quite large, but it allows to add various test cases for different fields very easily.
1. Better error message for stateless validation
2. Test structure for FieldValidator allows us to test it easier
1. Size of the test file is quite large, and it may take some time to understand how it all works. 
If you want to add a …

Improve stateless validation

---

.circleci/config.yml
docker/develop/Dockerfile
docker/develop/README.md
docker/docker-compose.yml
scripts/build-local-image.sh
scripts/run-iroha-dev.sh

This PR enables CI build from non-privileged user, instead of root.
It builds iroha-docker-develop with pre-created iroha user, and simplifies run-iroha-dev script.
More realistic CI builds.
Simpler run-iroha-dev script
None

Set iroha user in Dockerfile

---

test/module/shared_model/bindings/QueryTest.java
test/module/shared_model/bindings/query-test.py

Seems that swig test for GetTransaction was missed, here's the simple fix

Add missing get tx swig tests

---

irohad/model/model_crypto_provider.hpp
irohad/validation/chain_validator.hpp
irohad/validation/stateful_validator.hpp
irohad/validation/stateless_validator.hpp
libs/crypto/keys_manager.hpp

Add virtual destructors for classes with virtual methods.
Get rid of warnings and make code less bug prone.
No.
Not needed.
No.

fix/Add virtual destructors for classes with virtual methods. IR-769

---

libs/common/files.cpp
libs/common/files.hpp

Replace dirent.h functions with boost::filesystem in remove_all function.  
Portability.
None.
Not requred.
No.

IR-578 Make filesystem operations via boost::filesystem

---

irohad/main/CMakeLists.txt
irohad/main/impl/raw_block_loader.cpp
irohad/main/irohad.cpp
irohad/main/raw_block_loader.hpp
test/integration/pipeline/transfer_asset_inter_domain_test.cpp
test/integration/pipeline/tx_pipeline_integration_test.cpp
test/integration/pipeline/tx_pipeline_integration_test_fixture.hpp
test/module/irohad/common/CMakeLists.txt
test/module/irohad/common/block_insertion_test.cpp
test/module/irohad/common/raw_block_loader_test.cpp

* rework Irohad initialization with storage block insertions
* rename raw block insertion to raw block loader
* remove insertion stuff from block loader
* fix integration tests
* remove redundant tests from block insertion tests
Easier to manage Irohad because of simplification of initialization.

Rework raw block insertion

---

irohad/main/application.cpp
irohad/main/irohad.cpp

Add comments to irohad.cpp and application.cpp

Add comments to irohad.cpp and application.cpp

---

irohad/main/server_runner.hpp

Add comments to ServerRunner.
Code is documented now.
No.
No need.
No.

Add comments to ServerRunner

---

cmake/analysis.cmake

Improvements of the coverage:
- Set `llvm-cov` with clang
- <s>Remove test dir from coverage</s>

Add llvm-cov for clang

---

irohad/ametsuchi/impl/flat_file/flat_file.cpp

Related to [that](https://github.com/hyperledger/iroha/pull/845#discussion_r162268651)

Use std::less instead lambda at the ordering

---

test/framework/integration_framework/integration_test_framework.cpp
test/framework/integration_framework/integration_test_framework.hpp
test/framework/integration_framework/iroha_instance.hpp

Adds setters into IrohaInstance in order to easily parametrize initialization of test class. I didn't add another builder since IrohaInstance is some kind of builder itself. initPipeline() builds object.
Allow to parametrize initialization.
No.
see IntegrationTestFramework::setInitialState()
Another builder adds unnecessary layer of wrapper.

IR-793 add ability to configure initialization of IrohaInstance in ITF

---

irohad/ametsuchi/impl/postgres_wsv_command.cpp
irohad/ametsuchi/impl/postgres_wsv_command.hpp
irohad/ametsuchi/impl/postgres_wsv_common.hpp
irohad/ametsuchi/impl/postgres_wsv_query.cpp
irohad/ametsuchi/impl/postgres_wsv_query.hpp
irohad/model/account_asset.hpp
irohad/model/asset.hpp
test/module/irohad/ametsuchi/wsv_query_command_test.cpp

This Pull Request changes postgres_wsv_command postgres_wsv_query to reduce code duplication and improve readability. Main refactor is to use bind operator to perform database accesses instead of repeated try-catch code.
Several tests were added to cover previously uncovered branches in these 2 files
1. Reduced code duplication
2. Test coverage improved
None

Refactor postgres_wsv_* to reduce code duplication

---

irohad/main/irohad.cpp

Add missing doxygen based info in a comments of irohad.cpp

Add missing doxygen-based info

---

shared_model/backend/protobuf/block.hpp
shared_model/backend/protobuf/impl.cpp
shared_model/builders/protobuf/block.hpp
shared_model/interfaces/iroha_internal/block.hpp
shared_model/validators/block_validator.hpp

This PR adds a new item to shared model: Block
It includes interface, protobuf implementation, builders and a template for validators.
New implemented item in shared model
None

Shared model/block

---

schema/endpoint.proto

Remove unused service from endpoint.proto
Less confusion for the readers
None

Remove genesis block service from proto schema

---

housekeeping/upsource-webhook.py
iroha-cli/client.cpp
iroha-cli/main.cpp
irohad/main/irohad.cpp
irohad/torii/command_client.cpp
irohad/torii/processor/query_processor.hpp
irohad/torii/torii_service_handler.cpp
libs/crypto/keys_manager_impl.cpp
libs/generator/generator.cpp
libs/validator/domain_name_validator.cpp
test/framework/test_block_generator.cpp

Some headers were removed and rearranged by Clion.
Less headers, less dependecies.
None.
None.
We need to do it with some better tools.

optimize import with clion

---

shared_model/interfaces/proposal.hpp
shared_model/interfaces/transaction.hpp

fix missing part

---

docker/docker-compose.yml

Add minor fix to docker-compose file. 
Fix user name. 
Can run run-iroha-dev script
Was tested for docker-compose 1.18, what about others?

Add fix to docker-compose file

---

shared_model/backend/protobuf/common_objects/trivial_proto.hpp
shared_model/builders/protobuf/builder_templates/block_template.hpp
shared_model/converters/protobuf/json_proto_converter.hpp
test/module/shared_model/backend_proto/CMakeLists.txt
test/module/shared_model/converters/CMakeLists.txt
test/module/shared_model/converters/json_proto_converter_test.cpp

Adds json converters from shared model objects with proto backend. 
Allows converting shared model objects into json and vice versa by means of protobuf methods.
* Currently conversions are done using functions without classes. Might look as a drawback for someone.
* While model to json function is straightforward, conversion from command contains 3 functions: 
1. jsonToModel -- general function to convert json into protobuf message objects. Returns none if json is not valid.
2. jsonToBlock -- function converting json into shared model block. Returns none if json is not valid.
3. jsonToTransaction -- function converting json into shared model transaction. Returns none if json is not valid.
* At the moment this PR was implemented proto class for …

Implement json converter

---

Jenkinsfile

- ccache is now bind mounted into docker container. It was not merged in previous commits
- make docker container names more random. Useful if multiple concurrent builds are run for the same PR
Overall, speeds up builds and stability in case several concurrent builds are running
None

Revert ccache

---

example/node/.gitignore
example/node/binding.gyp
example/node/clean.sh
example/node/index.js
example/node/package.json
example/node/prepare.sh
shared_model/bindings/CMakeLists.txt

Signed-off-by: Vyacheslav Bikbaev <la.sintez@gmail.com>
Implementation of shared library for NodeJS.
Huge thanks to @haojun for help in implementing of this.
Possible to use Shared Model with NodeJS (And Electron)
None

Feature: Shared Library for NodeJS

---

irohad/multi_sig_transactions/gossip_propagation_strategy.hpp
irohad/multi_sig_transactions/impl/gossip_propagation_strategy.cpp
irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
irohad/multi_sig_transactions/mst_processor_impl.hpp
irohad/multi_sig_transactions/storage/impl/mst_storage.cpp
irohad/torii/processor/impl/transaction_processor_impl.cpp
test/module/irohad/multi_sig_transactions/gossip_propagation_strategy_test.cpp

As long as we're forbid merges there's an additional commit for fixing mst branch after previous rebase
So far:
- There's fixed race condition bug in gossip strategy
- Test for that

Mst branch fixes

---

shared_model/backend/protobuf/from_old_model.hpp

Make new shared model with older ones
Easier migration

  Feature/from old model

---

libs/common/result.hpp
test/module/libs/common/result_test.cpp

Result Type which wraps types into polymorphic containers (shared_ptr)
Reduces boilerplate when using result with polymorphic objects
Objects must be stored on the heap, which impacts performance.

Add Polymorphic Result type

---

libs/cache/cache.hpp
test/module/libs/cache/cache_test.cpp

Allows using cache with custom type as a key when corresponding hasher is defined.
Makes cache class more flexible
None
Test is provided

Cache with custom type

---

irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/network/block_loader.hpp
irohad/network/impl/block_loader_impl.cpp
irohad/network/impl/block_loader_impl.hpp
irohad/synchronizer/impl/synchronizer_impl.cpp
libs/common/wrapper.hpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/network/CMakeLists.txt
test/module/irohad/network/block_loader_test.cpp
test/module/irohad/network/network_mocks.hpp
test/module/irohad/synchronizer/synchronizer_test.cpp

Change BlockLoader's interface to the new shared model

Rework BlockLoader with new model

---

libs/logger/logger.cpp

Add date to logger and refactor the format
Now we have full date in logger
Check the new format: 
Non debug mode
Debug mode:

Refactor logger format

---

.circleci/config.yml

I hope it will fix internal compiler error.

Reduce parallelism for debug build

---

irohad/ametsuchi/impl/postgres_ordering_service_persistent_state.cpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/main/server_runner.cpp
irohad/ordering/impl/ordering_service_impl.cpp
irohad/ordering/impl/ordering_service_impl.hpp

Add log, which outputs the size of ordering service queue and informs about the time when proposal was started to form. Also, there was a bug in case when Postgres options were not allowing to connect — irohad binary was crashing.
More verbose log and explanatory start up messages
None

Logging and small bug fix

---

.circleci/config.yml

- decrease cache size for linux debug build from 5G to 2G -- it decreases mean build time while still keeping the whole project in cache.
- fix build-macos-release 
Fixed CI for mac.
This solution may be temporal, and may be changed in future, but for now, it is good to have working CI.

Fix build-macos-release

---

.gitignore

Remove docker/release/iroha.deb file, since it is a binary file and was pushed by mistake.
Less time to download repo, smaller size.
None.

Remove deb and add gitignore for deb

---

Jenkinsfile
deploy/ansible/roles/iroha-node/defaults/main.yml
deploy/ansible/roles/iroha-node/tasks/ubuntu.yml
deploy/ansible/roles/iroha-node/templates/config.j2
docker/develop/Dockerfile
docker/docker-compose-swarm.yml
docker/docker-compose.yml
docs/source/deployment.rst
irohad/ametsuchi/impl/postgres_block_query.cpp
irohad/ametsuchi/impl/postgres_block_query.hpp
scripts/local-develop.sh
scripts/swarm-deploy.sh

Redis dependencies were removed from docker-compose files, configuration files and all the rest places where Redis was mentioned.
Additionally, there is a complementary PR for iroha-api repository https://github.com/hyperledger/iroha-api/pull/58
Completely removes Redis from the project after #933

Remove redundant Redis dependencies and mentions

---

example/genesis.block
irohad/model/converters/impl/pb_command_factory.cpp
irohad/model/permissions.hpp
schema/primitive.proto

This pull requests brings prettified file permissions.hpp, refactored order in primitive.proto and addition of domain-related permissions to the primitive.proto and pb_command_factory. The order is persistent across modified files, so it is convenient now to check what is the status of permissions.
Now genesis block has almost all possible permissions in it. The code looks a bit better.
1. Genesis block was modified manually. CLI code has to be modified as well.
2. Grant permission for TransferAsset is not checked.
pb_commands_tests.cpp
CommandTest, create_role
I also executed a manual test against modified genesis.block, and it works.

Refactor permissions and add set account detail in genesis block

---

irohad/model/commit.hpp
irohad/network/impl/peer_communication_service_impl.cpp
irohad/network/impl/peer_communication_service_impl.hpp
irohad/network/peer_communication_service.hpp
irohad/synchronizer/impl/synchronizer_impl.cpp
irohad/synchronizer/impl/synchronizer_impl.hpp
irohad/synchronizer/synchronizer.hpp
irohad/torii/processor/impl/transaction_processor_impl.cpp
irohad/validation/chain_validator.hpp
irohad/validation/impl/chain_validator_impl.cpp
irohad/validation/impl/chain_validator_impl.hpp
test/framework/integration_framework/integration_test_framework.cpp
test/framework/integration_framework/integration_test_framework.hpp
test/integration/client_test.cpp
test/integration/pipeline/tx_pipeline_integration_test.cpp
test/integration/pipeline/tx_pipeline_integration_test_fixture.cpp
test/integration/pipeline/tx_pipeline_integration_test_fixture.hpp
test/module/irohad/network/network_mocks.hpp
test/module/irohad/torii/processor/transaction_processor_test.cpp
test/module/irohad/torii/torii_service_test.cpp
test/module/irohad/validation/validation_mocks.hpp

Updates pcs to use shared model
New model will be used in pcs
none

Update pcs to shm

---

shared_model/backend/protobuf/common_objects/amount.hpp
shared_model/builders/protobuf/common_objects/proto_account_asset_builder.hpp
shared_model/builders/protobuf/common_objects/proto_amount_builder.hpp
test/module/shared_model/backend_proto/CMakeLists.txt
test/module/shared_model/backend_proto/common_objects/shared_proto_amount_test.cpp
test/module/shared_model/builders/protobuf/common_objects/proto_amount_builder_test.cpp

This pull request fixes a critical bug with incorrect amount initialization, which caused Amount object to hold incorrect Value. This could result in loss of assets and other issues.
Bug was fixed and regression tests were added
Bug fixed
None

Fix incorrect proto amount initialisation

---

irohad/ametsuchi/impl/mutable_storage_impl.cpp
irohad/ametsuchi/impl/mutable_storage_impl.hpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/mutable_storage.hpp
irohad/validation/impl/chain_validator_impl.cpp
test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp
test/module/irohad/ametsuchi/kv_storage_test.cpp
test/module/irohad/validation/chain_validation_test.cpp

`MutableStorage` was migrated to the new model.
Less dependency on old model.
None.

Shared model/new mutable storage

---

CMakeLists.txt
cmake/Modules/Finded25519.cmake
cmake/Modules/Findpq.cmake
cmake/Modules/Findpqxx.cmake
cmake/Modules/Findswig.cmake
cmake/Modules/Findtbb.cmake

Fixes build via ninja generator
Working ninja build
`cmake -G Ninja .. && ninja`

Fixes build via ninja generator

---

irohad/network/impl/block_loader_impl.cpp

Change severity level for BlockLoaderImpl messages
Not so much
Neither any

Implement the change request for err level

---

libs/amount/CMakeLists.txt
libs/amount/amount.cpp

Remove logger include and link library from amount library
Shared model does not depend on logger
None

Remove unused logger dependency from amount

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/ametsuchi/impl/wsv_restorer_impl.cpp
irohad/ametsuchi/storage.hpp
irohad/main/irohad.cpp
test/framework/integration_framework/iroha_instance.cpp
test/integration/pipeline/transfer_asset_inter_domain_test.cpp
test/integration/pipeline/tx_pipeline_integration_test.cpp
test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp

This PR changes storage to shared_model
Continue migration to shared_model
None

Storage to shared model

---

cmake/Modules/Findgrpc.cmake
docker/develop/Dockerfile
snap/snapcraft.yaml

- `Findgrpc.cmake`: remove `grpc++_reflection` library
- `develop/Dockerfile`: refactor tools, add CMAKE_BUILD_TYPE build argument, rebuild dependencies in Release, fix few bugs: fix boost build, fix postgres build, remove unused dependencies.
- `snap`: change ln -> cp to make postgres succeed.
This dockerfile is already built as `hyperledger/iroha-docker-develop:v1`, please update your local copy.
Fixes lots of build bugs in `develop/Dockerfile`, makes Dockerfile easier to read and support.
None.
`docker pull hyperledger/iroha-docker-develop:v1`
Hunter would be better for dependencies.

Refactor and fixes in dependencies

---

cmake/Modules/Findgrpc.cmake
cmake/Modules/Findprotobuf.cmake
docker/develop/Dockerfile

- Findgrpc.cmake: add missing `gpr_LIBRARY`, improve readability
- Findprotobuf.cmake: improve readability
- develop/Dockerfile: 
- add `set -e` to make docker image build fail, if any of commands fail. 
- add ldconfig to every step (grpc depends on protoc, which depends on libprotoc.so, without ldconfig protoc can not find libprotoc.so). 
- it turned out that `sh` has no `lib{gpr,grpc,grpc++,grpc_plugin_support}.so` and I was forced to explicitly copy libs one-by-one. 
Bugfixes.
None.

Docker-develop dockerfile fixes and cmake dependencies readability improvement

---

shared_model/builders/protobuf/builder_templates/block_template.hpp
test/framework/integration_framework/integration_test_framework.cpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp
test/module/irohad/ametsuchi/block_query_test.cpp
test/module/irohad/ametsuchi/block_query_transfer_test.cpp
test/module/irohad/network/block_loader_test.cpp
test/module/irohad/simulator/simulator_test.cpp
test/module/irohad/torii/torii_service_test.cpp
test/module/irohad/validation/chain_validation_test.cpp
test/module/shared_model/builders/protobuf/transport_builder_test.cpp
test/module/shared_model/converters/json_proto_converter_test.cpp

Remove `txNumber` from required fields in `BlockBuilder`.
Less error prone code.
None

Remove txNumber

---

shared_model/backend/protobuf/block.hpp
shared_model/backend/protobuf/query_responses/proto_transaction_response.hpp
shared_model/interfaces/common_objects/signable_hash.hpp
shared_model/interfaces/common_objects/types.hpp
shared_model/interfaces/iroha_internal/block.hpp
shared_model/interfaces/query_responses/transactions_response.hpp

Move TransactionCollectionType from shared_model/interface/iroha_internal/block.hpp to shared_model/interfaces/common_object/types.hpp.
Datatypes are more structured.
no
no
no

Move TransactionCollectionType to interface/types.h

---

libs/generator/CMakeLists.txt
shared_model/cryptography/ed25519_sha3_impl/internal/CMakeLists.txt
shared_model/cryptography/model_impl/CMakeLists.txt

Fix for impossibility to find boost headers (optional.hpp actually) in case of building iroha library with a cross compiler.
Possibility to build libraries for Android and iOS.
None.

Fix boost headers issues.

---

example/config.sample
irohad/main/iroha_conf_loader.hpp

- Missed empty line in config, that may resolve #1081 
- More detailed error at config parsing

Add detailed error at config parsing

---

docker/develop/aarch64/Dockerfile
docker/develop/armv7l/Dockerfile
docker/develop/x86_64/Dockerfile
snap/snapcraft.yaml

Removes nonstd completely.
Minus one dependency
None

Remove nonstd optional

---

example/java/build.gradle

Fix build dir path, and add javaDoc artifact.
New command for grade
None

Shared model/maven

---

docs/source/use_cases/index.rst

This pr adds relevant iroha use cases. Please review and pay attention to huge introduction section. I describe more in Possible Drawbacks. 
Documentation with relevant use cases. 
The introduction to the use cases is somewhat big. Although, it is not directly relevant to use case section, it provides useful context for it. We need to think what can we do with it, maybe we can move part of the introduction section to other docs?

Add relevant use cases

---

shared_model/CMakeLists.txt

Fix CMake cyclic dependency when shared_model is built with SWIG.
Succesful CMake configuration which allows to build shared_model
None

Fix cyclic dependency when shared_model project is built with SWIG

---

docs/source/requirements.txt

Signed-off-by: Vyacheslav Bikbaev <la.sintez@gmail.com>
Updated ``sphinx-rtd-theme`` for our documentation to ``0.2.5b2``. Current version (``0.2.4``) has a bug with lines-of-code display, [https://github.com/rtfd/readthedocs.org/issues/3470]( https://github.com/rtfd/readthedocs.org/issues/3470)
Listings with code are displayed better, other improvements.
None

fix: updated sphinx theme, so lines of code are displayed correctly

---

.jenkinsci/bindings.groovy
.jenkinsci/debug-build.groovy
.jenkinsci/docker-cleanup.groovy
.jenkinsci/release-build.groovy
CMakeLists.txt
Jenkinsfile
docker/release/x86_64/Dockerfile

- Fix ccache not being used during builds on MacOS
- Fix full path to binaries being used instead of relative ones on MacOS. Jenkins now complements PATH with additional lookup paths
- Fix post step may stuck forever on random builds. It now has a timeout. Post step will be forcibly terminated after a certain timeout (60s)
- Fix `cppcheck` target enabled even when coverage is disabled for that build
- Fix local `parallelism` param in Groovy build scripts was always null on the FIRST build. It is a known  [Jenkins bug](https://issues.jenkins-ci.org/browse/JENKINS-41929)
**[UPD]**
- FIx dependencies in release Dockefile not installed properly
Increase stability of CI pipeline. Improve Jenkinsfile readability.
None

Jenkinsfile fixes

---

irohad/ametsuchi/impl/postgres_wsv_query.cpp

Add log output if error is produced on `Peer` deserialisation from database.
It is possible to see the error if genesis block with peers is applied, but peer query returns that there are no peers in ledger.
None.

Print getPeers errors in PostgresWsvQuery

---

docs/README.md
docs/source/index.rst

Change reference to logo in main page
Now localised docs available at:
https://readthedocs.org/projects/iroha/
https://readthedocs.org/projects/iroha-de/
https://readthedocs.org/projects/iroha-fr/
https://readthedocs.org/projects/iroha-ja/
https://readthedocs.org/projects/iroha-ru/
As they are using hard link now they show images without troubles
None
Check recent build of docs after merge of this PR :) or build them manually

Change image reference

---

docker/release/x86_64/Dockerfile

Jenkinsfile:
- Fix dependencies not installed when building release docker image
Docker images will come with preinstalled dependencies required to run Iroha.
None

Fix dependencies installation in release docker image

---

test/integration/acceptance/CMakeLists.txt
test/integration/acceptance/add_asset_qty_test.cpp

Add AddAssetQuantity acceptance test
Hopefully all works as expected, so there is no disabled tests.
~145 sec of test execution time :(

Add AddAssetQuantity acceptance test

---

irohad/main/impl/raw_block_loader.cpp
irohad/main/irohad.cpp
irohad/main/raw_block_loader.hpp
test/module/irohad/common/raw_block_loader_test.cpp

Move raw block loader to shared_model
refactoring to a new model
none

shared model raw block loader

---

docs/source/guides/libraries.rst

PR introduces documentation about Android Client Library.
Documentation answers the following set of questions for Android developer: where to get, how to build, how to use, where to find code examples.
The guide presented in this PR is not relevant until #1133 and #1073 are merged into develop branch.
If you want to test the guide, then you have to download android-build.sh script from #1073 and change the line 
``git clone -b develop --depth=1 https://github.com/hyperledger/iroha`` 
to 
``git clone -b fix/swig-patch-path --depth=1 https://github.com/hyperledger/iroha``

Android Documentation

---

test/integration/acceptance/CMakeLists.txt
test/integration/acceptance/subtract_asset_qty_test.cpp

Add SubtractAssetQuantity acceptance test
Hopefully all works as expected, so there is no disabled tests.
~115 sec of test execution time :(

Add SubtractAssetQuantity acceptance test

---

cmake/Modules/Findswig.cmake

This pull request fixes path to Swig patch file.
After introducing shared_model as a separate project patching became broken. This pr fixes that.
Also pr downloads tarball instead of git repository to decrease number of packages needed to build client libraries.
None.

Fix path to swig patch

---

cmake/Modules/Findswig.cmake

Uses ftp instead of http url for swig.
It was discovered that cmake can't handle https urls in all systems (http redirects to https)
None.

Use ftp url for swig instead of tarball

---

shared_model/packages/ios/.gitignore
shared_model/packages/ios/ios-build.sh

Iroha bindings build script for iOS
Builds bindings libraries and dependencies with iOS specific parameters - bitcode, ARC, ARM architecture.
None.
`./example/ios/ios-build.sh OS Debug`

iOS build script

---

irohad/network/impl/peer_communication_service_impl.cpp
irohad/synchronizer/impl/synchronizer_impl.cpp
irohad/synchronizer/impl/synchronizer_impl.hpp
irohad/synchronizer/synchronizer.hpp
irohad/validation/impl/chain_validator_impl.cpp
test/module/irohad/synchronizer/CMakeLists.txt
test/module/irohad/synchronizer/synchronizer_test.cpp

Synchronizer: replace old model to shared model.
Old model is a subject to remove so we are one step closer to success now.
None.
Tests were changed accordingly.

 Replace old model to shared model in synchronizer

---

docs/source/api/commands.rst
docs/source/api/index.rst

After copying the contents from Iroha API and their review ReadTheDocs contents will have a finished look. This is a piece of this work, since at least we need to copy queries in separate PR and also we need to copy remaining info in Core Concepts section.
More explanation of Iroha API.
None

Migrating gRPC Commands API reference from Slate (Iroha API)

---

irohad/execution/CMakeLists.txt
shared_model/builders/CMakeLists.txt

Fix dependencies for command_execution target

fix dependencies for command_execution

---

shared_model/bindings/bindings.i

Bindings build is now broken. This pr fixes it.

Fix build of bindings

---

Jenkinsfile

Signed-off-by: tyvision <antykushin@gmail.com>
Fix the issues with nightly builds merged to develop branch from #1128 
Fresh build on develop branch did not stop previous builds in case they all are not triggered by cron.

Fix issues after #1128 night-time scheduled builds feature merge to Jenkinsfile

---

docs/source/api/commands.rst

Signed-off-by: neewy <n.yushkevich@hotmail.com>
Update of docs according to #1148
More consistency
None

Update with new stateless validation rules

---

docs/source/api/queries.rst

Finishing transfer of documentation from Slate to ReadTheDocs (API Reference section). 
More explanation of Iroha API.
None

Migrating gRPC Queries API reference from Slate (Iroha API)

---

irohad/torii/processor/impl/query_processor_impl.cpp
irohad/torii/processor/query_processor_impl.hpp
irohad/validation/impl/stateful_validator_impl.cpp
test/integration/acceptance/get_transactions_test.cpp
test/integration/client_test.cpp
test/module/irohad/torii/processor/query_processor_test.cpp
test/module/irohad/torii/torii_queries_test.cpp

This PR adds signature checking when query arrives and goes to Query Processor
Improved security
None
See
https://github.com/hyperledger/iroha/compare/develop...shared_model/query-processor-signature?expand=1#diff-80206c039238f53c13011f908e086721R129

Shared model/query processor signature

---

irohad/network/impl/block_loader_impl.cpp
irohad/network/impl/block_loader_impl.hpp
irohad/network/impl/block_loader_service.cpp
test/module/irohad/model/model_mocks.hpp
test/module/irohad/network/block_loader_test.cpp

Migrate `BlockLoader` and `BlockLoaderService` to the new model
No dependency on old model
None

Shared model/new block loader

---

.jenkinsci/artifacts.groovy
.jenkinsci/debug-build.groovy
.jenkinsci/linux-post-step.groovy
.jenkinsci/mac-release-build.groovy
Jenkinsfile

- A feature to upload artifacts produced after a successful build to the artifact server
- Replace Release build stage in Jenkinsfile with a function
- Artifacts will now be available on external server (artifact.soramitsu.co.jp) for downloading
None

Uploading of the build artifacts

---

irohad/model/converters/impl/pb_transaction_factory.cpp
schema/block.proto
shared_model/backend/protobuf/transaction.hpp
test/integration/acceptance/invalid_fields_test.cpp
test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp
test/module/shared_model/validators/field_validator_test.cpp

This is a refactor PR, changed `proto::Transaction::signature` to `photo::Transaction::signatures`.
Consistency
All maintainers have to remove generated schema files

Replace signature with signatures

---

shared_model/interfaces/common_objects/account.hpp

Add a missed field in Account::toString.
Improve readability of logs

Fix toString in account

---

test/module/irohad/ametsuchi/ametsuchi_test.cpp

Remove remaining old model from ametsuchi test.
Continue migrating to the new model
None

Remove old model from ametsuchi test

---

.jenkinsci/linux-post-step.groovy

Fix typo in CI script that prevented from constructing a valid path on the artifact server
Construction of a valid upload path for artifacts after a CI build
None

Fix artifacts upload path

---

README.md

Fix link in readme
No errors when this link is opened
None

Fix overview link

---

docs/source/overview.rst

Signed-off-by: Nikolay Yushkevich <n.yushkevich@hotmail.com>
Unfortunately, the data used in the documentation are obsolete and have been supposed to be replaced before release of beta. We should not keep this metric for too long in public, as Iroha is expected to produce 3000 tx/s throughput on 7 nodes. As we are in the middle of update of Huawei Caliper's data then we need to finish it first and only then update data in docs.
Relevant data in docs.
None

Delete obsolete data

---

docs/source/api/commands.rst

Mention behaviour of Set Account Detail (If there was a value for a given key already in the storage then it will be replaced with the new value)
Explained contents of docs
None

Add details to description of Set Account Detail

---

docs/source/api/queries.rst

Signed-off-by: Nikolay Yushkevich <n.yushkevich@hotmail.com>
Change level of heading in Queries section
Consistency
None

Change level of heading

---

README.md
docs/source/conf.py

Fixed license info in our readme and conf.py files according to https://github.com/hyperledger/iroha/issues/1183
Partially eliminating problems with licensing.
We still need to license all other source code files :)

Fix of licenses

---

irohad/model/impl/query_execution.cpp
irohad/model/query_execution.hpp
test/integration/acceptance/get_transactions_test.cpp

Adds check whether a user can query a transaction
https://soramitsu.atlassian.net/browse/IR-1039
Don't return transaction which user doesn't have access to
-

add transaction creator check

---

docs/source/getting_started/index.rst

Changed the docker image in the guide, so it points to the latest built develop branch.
Now getting started guide will work again.
None

fix: docker image in getting started guide

---

irohad/torii/impl/command_service.cpp
irohad/torii/impl/query_service.cpp
shared_model/cryptography/default_hash_provider.hpp
shared_model/interfaces/base/signable.hpp

Extracted default hash provider from Signable
Now hash provider my be used not only by singable classes
None

Add default hash provider

---

test/integration/acceptance/tx_heavy_data.cpp
test/module/shared_model/validators/field_validator_test.cpp

Fix  `tx_heavy` and `field_validator` tests passing
Less number of broken tests.

Fix tests after heavy tx PR

---

test/module/iroha-cli/client_test.cpp

Add mocks for getAccountRoles() calls in client test.
No warnings from GMOCK runtime during test execution.
None.

Add mocks for getAccountRoles() in client test

---

irohad/ametsuchi/CMakeLists.txt
irohad/consensus/yac/CMakeLists.txt
irohad/main/CMakeLists.txt
irohad/main/irohad.cpp
irohad/network/CMakeLists.txt
irohad/network/impl/block_loader_service.hpp
irohad/network/impl/peer_communication_service_impl.cpp
irohad/ordering/CMakeLists.txt
irohad/simulator/CMakeLists.txt
irohad/synchronizer/CMakeLists.txt
irohad/torii/CMakeLists.txt
irohad/validation/CMakeLists.txt
shared_model/backend/protobuf/CMakeLists.txt
shared_model/builders/CMakeLists.txt
shared_model/builders/protobuf/CMakeLists.txt
shared_model/interfaces/CMakeLists.txt
shared_model/validators/CMakeLists.txt
test/integration/acceptance/CMakeLists.txt
test/module/irohad/consensus/yac/CMakeLists.txt
test/module/irohad/consensus/yac/peer_orderer_test.cpp
test/module/irohad/validation/CMakeLists.txt
test/system/CMakeLists.txt
test/system/irohad_test.cpp

Remove old model dependencies from CMakeLists.
Also remove old model converters::jsonToString from irohad_test.cpp. 
less old model

remove old model from cmake

---

irohad/consensus/yac/impl/yac.cpp
irohad/consensus/yac/impl/yac_crypto_provider_impl.cpp
irohad/consensus/yac/impl/yac_crypto_provider_impl.hpp
irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/consensus/yac/messages.hpp
irohad/consensus/yac/transport/yac_pb_converters.hpp
irohad/main/impl/consensus_init.cpp
irohad/main/impl/consensus_init.hpp
shared_model/builders/common_objects/common.hpp
test/integration/consensus/consensus_sunny_day.cpp
test/module/irohad/consensus/yac/CMakeLists.txt
test/module/irohad/consensus/yac/network_test.cpp
test/module/irohad/consensus/yac/yac_common_test.cpp
test/module/irohad/consensus/yac/yac_crypto_provider_test.cpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/consensus/yac/yac_mocks.hpp
test/module/irohad/consensus/yac/yac_unknown_peer_test.cpp
test/module/irohad/validation/chain_validation_test.cpp
test/module/shared_model/builders/protobuf/test_signature_builder.hpp

Migrate Vote Message to the new model
Consensus now uses new model
None

Shared model/new vote message

---

test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/kv_storage_test.cpp

Move kv_storage test to new model
Continue refactoring to new model
None

remove old model from kv_storage_test

---

docs/README.md

Documentation fix corresponding to [issue #1261](https://github.com/hyperledger/iroha/issues/1261).
The reStructureTest URL was updated, and one word was removed to make the grammar better.
The link will work now.

[Documentation] - Fix the reStructureTest URL in docs/README.md.

---

shared_model/bindings/CMakeLists.txt
test/module/shared_model/bindings/CMakeLists.txt

Decreased required python version from 3.6 to 3.5
Compatibility with repositories
Lower python version, less features

Decrease required python version

---

irohad/ametsuchi/block_query.hpp
irohad/ametsuchi/impl/postgres_block_query.cpp
irohad/ametsuchi/impl/postgres_block_query.hpp
irohad/torii/impl/command_service.cpp
test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
test/module/irohad/ametsuchi/block_query_test.cpp

Add method to check for the existence of transaction in a blockchain. Apply it in command service to verify that transaction was successfully saved.
Previously transaction was retrieved to check that it was saved, which was doing a lot of unnecessary work. Checking for existence is simpler
None

HasTxWithHash for Block Query

---

docs/source/getting_started/index.rst
docs/source/guides/build.rst

Pull request fixes hint in docs about git clone depth parameter.
Old hint has a mistake in it; you will receive an error message if you try to use it.
None.

Fix hint about git clone depth.

---

.jenkinsci/debug-build.groovy
.jenkinsci/mac-release-build.groovy
.jenkinsci/release-build.groovy

- "Debug" build type build followed by "Release" build in CI pipeline generates two sets of artifacts for each build type respectively. This PR disables artifacts generation for "Debug" build type so that they would not be uploaded to artifact server. We only want to have "Release" artifacts published.
- Include TAR packaged artifacts previously generated but not uploaded for Linux builds.
- Replace `cp` with `mv` to save some disk space used by a single build.
- Only "Release" artifacts are uploaded
- TAR packaged binaries for non-Debian OS flavors
- Reduce disk space usage during a CI build
None

Fix artifacts uploading

---

.jenkinsci/mac-release-build.groovy
Jenkinsfile

CI:
- Fix `mv` command run before actual build
- Fix MacOS Release build run without specifying an agent
Prevent Develop branch build on Jenkins from failing
None

Fix mac release build

---

irohad/main/application.cpp
irohad/main/impl/ordering_init.cpp
irohad/main/impl/ordering_init.hpp
irohad/ordering/impl/ordering_gate_impl.cpp
irohad/ordering/impl/ordering_gate_impl.hpp
irohad/simulator/impl/simulator.cpp
test/module/irohad/ordering/ordering_gate_service_test.cpp
test/module/irohad/ordering/ordering_gate_test.cpp

This PR changes the logic of the ordering gate. Now proposals which are older than the last committed block will be discarded from the queue.
Old proposals are not passed down the pipeline when newer commit arrives
None

Ordering gate discards outdated proposals and keeps new ones

---

libs/cache/cache.hpp
test/module/libs/cache/cache_test.cpp

Cache size can now be specified.

Add configurable size to libs/cache

---

example/genesis.block
schema/primitive.proto
shared_model/validators/permissions.hpp

add can_get_blocks permission to the system, to the read_all_group and implicitly to genesis blocks
needed for block query in future
--

add can_get_blocks permission

---

cmake/Modules/Finded25519.cmake
patch/close.patch
test/integration/consensus/consensus_sunny_day.cpp

Fix occasional segmentation faults and assertion failures due to 50ms not being enough to receive commit from the network in consensus sunny day test.
Less issues with test instability.
None.

Fix consensus sunny day test

---

Jenkinsfile

Test integration branch. No actual review required

---

docker/develop/Dockerfile

New version of gRPC introduced another library file, which was not copied in Dockerfile. Any such change in gRPC will require manual maintenance of library list, which is not convenient. This pull request reverts gRPC installation logic to `cmake --target install`, so that all required libraries are installed independent of version.
Less maintenance for Dockerfile.
Potentially longer build time for Dockerfile. This should not be a problem because it is not done often.

Fix gRPC libs not being installed

---

docker/docker-compose.yml

One of the previous commits broke development environment setup process. This PR fixes it
None

Fix development environment setup

---

shared_model/packages/python/README.md

Added documentation about installing Iroha Python libs from source
More documented code
None

Python docs

---

deploy/ansible/roles/iroha-cluster-deploy-node/defaults/main.yml
deploy/ansible/roles/iroha-standalone-deploy-node/defaults/main.yml
docs/source/guides/build.rst
docs/source/guides/deployment.rst

Names of Iroha Docker images are updated in order to reflect actual state.
* Ansible paths are updated
* ReadTheDocs sources are updated
* Docker hub repository description is set 
None
Please check the diff and https://hub.docker.com/r/hyperledger/iroha/

Update names of docker images

---

test/module/shared_model/bindings/builder-test.py
test/module/shared_model/bindings/query-test.py

Add new tests for Iroha Python bindings.
New test set cover building of Iroha's queries and commands. Each parameter of either command or query is tested separately from other parameters for boundary values (in a moment only one method's parameter takes invalid value - the rest are provided with valid values).
The total number of tests for commands is 98, queries - 45.
| Iroha Command | Tests |
| --- | --- |
| | test_empty_tx |
| **AddPeer** | test_add_peer<br/> test_add_peer_valid_domains<br/> test_outdated_add_peer<br/> test_add_peer_with_invalid_creator<br/> test_add_peer_with_invalid_creator_domain<br/> test_add_peer_with_empty_creator<br/> test_add_peer_with_invalid_key_size<br/> test_add_peer_with_invalid_domain |
| **AddSignatory** | test_add_signatory<br/> …

Add Python Tests

---

test/module/shared_model/amount_utils_test.cpp

Old gcc fails to deduce type in a lambda.

Hotfix compilation error on linux

---

README.md

Signed-off-by: Vyacheslav Bikbaev <la.sintez@gmail.com>
Fixed readme.md, removed copyright (since Hyperledger required it), removed some whitespaces, changed TG link
Up-to-date readme
none

Readme: trailing spaces, license, links

---

MAINTAINERS.md

Signed-off-by: Vyacheslav Bikbaev <la.sintez@gmail.com>
Valid email

fix: bikbaev email in contributors

---

cmake/functions.cmake
shared_model/bindings/CMakeLists.txt
test/module/shared_model/bindings/CMakeLists.txt

Change CMake calls to support MSVC and Windows environment to run and compile Python bindings.
Python bindings on Windows!
**Release build only**. Default python installation from python.org is missing `_d.{lib, dll}`
Please follow previous setup for build https://github.com/hyperledger/iroha/pull/1297
[SWIG 3.0.12](http://www.swig.org/download.html) should be installed in the system.
- `choco install python3`
- `pip install protobuf`

Support python tests with MSVC

---

test/module/shared_model/bindings/CMakeLists.txt
test/module/shared_model/bindings/build.gradle

Fix commands to support running java tests on Windows.
- Correctly set java PATH to tests step in Gradle
- Pass path to protoc executable to Gradle
Java bindings on Windows!
None.
Please follow previous setup for build https://github.com/hyperledger/iroha/pull/1297
[SWIG 3.0.12](http://www.swig.org/download.html) should be installed in the system.
- `choco install jdk10` or `choco install jdk8`
- `choco install gradle`

Java tests MSVC support

---

irohad/validation/CMakeLists.txt

Build was broken on systems without protobuf headers installed.
Build is possible again.
None
```
git clean -ffdx
cmake --build build
```

Fix build of stateful_validator target

---

.jenkinsci/github-merge.groovy
.jenkinsci/test-launcher.groovy
Jenkinsfile

Signed-off-by: tyvision <antykushin@gmail.com>
As soon as this is a test PR from one branch to another, there is no actual impact to Iroha.
This PR checks if merge functionality could be held by Jenkins. After it will be checked, the real PR will be opened.
Availability of Jenkins CI to merge code itself

[Review is not required] CI test merge functionality

---

test/module/irohad/ametsuchi/storage_init_test.cpp

Storage init test did not take into account environment variable which led to falling test on CI, this PR fixes that issue. 
No test is falling anymore
None

Storage init test

---

irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
test/module/irohad/multi_sig_transactions/mst_processor_test.cpp

Change avoids sharing of empty state in MST gossips propagation mechanism.
Network load decreased.
None
Compile & test

Improve MST. Avoid empty state propagation

---

docs/source/api/commands.rst
docs/source/api/queries.rst
shared_model/validators/field_validator.cpp
test/module/shared_model/validators/field_validator_test.cpp

Add missing validation rule for precision field. Add cases for precision field in field validator test.
Improved coverage.
Now the validation rule is useless because of used type for precision value in c++. It will become a relevant check when the underlying type of PrecisionType will be changed.
compile & test

Add validation rule for precision field

---

.jenkinsci/debug-build.groovy
.jenkinsci/github-api.groovy
.jenkinsci/mac-debug-build.groovy
.jenkinsci/notifications.groovy
.jenkinsci/test-launcher.groovy
Jenkinsfile

test how CI will merge the code to the target

[Review is not required] CI merge feature test x2

---

irohad/execution/impl/query_execution.cpp
shared_model/backend/protobuf/queries/proto_query.hpp
shared_model/builders/protobuf/builder_templates/query_template.hpp
shared_model/interfaces/queries/query.hpp
shared_model/validators/query_validator.hpp

Continuing #1381 
Remove polymorphic wrapper from query processing factory and query validator
Less polymorphic wrapper.
None.

Remove polymorphic wrapper from query

---

irohad/multi_sig_transactions/state/mst_state.hpp
test/module/irohad/multi_sig_transactions/mst_processor_test.cpp

Improve description of difference operator of `MstState`.
Improve the logic of time constants initialization in MST processor test.
None
compile & test

Nano refactor of MST processor test & axiom fix

---

docs/source/core_concepts/glossary.rst
docs/source/maintenance/ansible.rst
docs/source/maintenance/index.rst
docs/source/maintenance/permissions.rst

Add a list of permissions with their descriptions. 
Permissions are also linked with corresponding commands or queries.
Now the essential part of Iroha maintenance process is documented.
Missing examples. **They will be added in the following PR.**
You can compile docs locally using the guide from https://github.com/hyperledger/iroha/blob/develop/docs/README.md
and navigate in a browser to `_build/html/maintenance/permissions.html`
There is a tool that performs automatic page generation from the csv source of
https://docs.google.com/spreadsheets/d/1aKUXLrtbD5tzJV9fSZfagFcRC_PJVrPc2EkskA1VkFU/edit?usp=sharing (visible to Soramitsu employees) - 
https://repl.it/@igor_egorov/PermissionsGoogleSheetRst

Add permissions documentation

---

irohad/ametsuchi/impl/postgres_block_index.cpp
irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/execution/command_executor.hpp
irohad/execution/impl/command_executor.cpp
shared_model/backend/protobuf/commands/impl/proto_command.cpp
shared_model/backend/protobuf/commands/proto_command.hpp
shared_model/builders/common_objects/common.hpp
shared_model/builders/protobuf/builder_templates/block_template.hpp
shared_model/builders/protobuf/builder_templates/query_response_template.hpp
shared_model/builders/protobuf/common_objects/proto_domain_builder.hpp
shared_model/builders/protobuf/transport_builder.hpp
shared_model/interfaces/commands/command.hpp
shared_model/interfaces/transaction_responses/tx_response.hpp
shared_model/utils/variant_deserializer.hpp
shared_model/validators/block_validator.hpp
shared_model/validators/container_validator.hpp
shared_model/validators/transaction_validator.hpp
test/framework/specified_visitor.hpp
test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp
test/module/shared_model/validators/transaction_validator_test.cpp

Continuing #1388 
Refactored validator and executor. Changes in executor were done by replacing `command->` by `command.`.
Also removed polymorphic wrapper includes and references where it is unused
No more polymorphic wrapper in variants
None

Remove polymorphic wrapper from command

---

irohad/model/converters/impl/pb_query_factory.cpp
irohad/model/queries/blocks_query.hpp
irohad/model/query_payload_meta.hpp
schema/queries.proto
shared_model/backend/protobuf/queries/proto_blocks_query.hpp
shared_model/backend/protobuf/queries/proto_query.hpp
shared_model/backend/protobuf/queries/proto_query_payload_meta.hpp
shared_model/builders/protobuf/builder_templates/blocks_query_template.hpp
shared_model/builders/protobuf/builder_templates/query_template.hpp
shared_model/builders/protobuf/queries.hpp
shared_model/interfaces/queries/blocks_query.hpp
shared_model/interfaces/queries/query.hpp
shared_model/interfaces/queries/query_payload_meta.hpp
shared_model/validators/blocks_query_validator.hpp
shared_model/validators/default_validator.hpp
shared_model/validators/field_validator.cpp
shared_model/validators/field_validator.hpp
test/module/irohad/model/converters/pb_query_factory_test.cpp
test/module/shared_model/backend_proto/shared_proto_queries_test.cpp
test/module/shared_model/builders/protobuf/test_query_builder.hpp
test/module/shared_model/validators/field_validator_test.cpp
test/module/shared_model/validators/query_validator_test.cpp
test/module/shared_model/validators/validators_fixture.hpp

New query for obtaining blocks was introduced with builders.

add query for blocks, builders

---

irohad/torii/impl/command_service.cpp
test/module/irohad/torii/torii_service_test.cpp

Set of different fixes for Torii.
Bugfixes.
None.
Tests remain the same until Torii redesign.

New bunch of torii fixes

---

example/java/TransactionExample.java
example/node/index.js
example/python/tx-example.py
shared_model/bindings/model_proto.hpp
shared_model/builders/protobuf/unsigned_proto.hpp
test/module/shared_model/bindings/BuilderTest.java
test/module/shared_model/bindings/QueryTest.java
test/module/shared_model/bindings/builder-test.py
test/module/shared_model/bindings/query-test.py

In #1389 bindings fixes was missed
Bindings examples/test should work now

Fix signing in bindings test

---

irohad/execution/impl/command_executor.cpp
shared_model/backend/protobuf/commands/impl/proto_create_role.cpp
shared_model/backend/protobuf/commands/impl/proto_grant_permission.cpp
shared_model/backend/protobuf/commands/impl/proto_revoke_permission.cpp
shared_model/backend/protobuf/commands/proto_create_role.hpp
shared_model/backend/protobuf/commands/proto_grant_permission.hpp
shared_model/backend/protobuf/commands/proto_revoke_permission.hpp
shared_model/interfaces/commands/create_role.hpp
shared_model/interfaces/commands/grant_permission.hpp
shared_model/interfaces/commands/impl/create_role.cpp
shared_model/interfaces/commands/impl/grant_permission.cpp
shared_model/interfaces/commands/impl/revoke_permission.cpp
shared_model/interfaces/commands/revoke_permission.hpp
shared_model/validators/field_validator.cpp
shared_model/validators/field_validator.hpp
shared_model/validators/transaction_validator.hpp
test/module/irohad/execution/command_validate_execute_test.cpp
test/module/shared_model/validators/field_validator_test.cpp

New permissions in commands
One more step toward legacy model removal
Quite slower, because require some additional allocation (mostly for set)

New permissions in commands

---

shared_model/interfaces/queries/blocks_query.hpp
shared_model/packages/javascript/binding.gyp

Nodejs library is broken now; this pr fixes it.
Working nodejs library.
None.

Fix build of nodejs library

---

test/module/irohad/multi_sig_transactions/transport_test.cpp

Missed (in #1373) dynamic port binding in transport_test
All tests are using non-fixed ports
None

Add missed dynamic port binding in transport_test

---

example/java/build_library.sh

After changing of default java package path to *.java files was also changed but it wasn't reflected in jar building script. This pr fixes this problem.
Without fix jar package is useless.
None.

Fix jar build script

---

cmake/functions.cmake

Now schema target will be recompiled if *.proto file is changed.
Previously you had to manually delete old generated files.
No longer need to manually recompile schema
None

Add schema recompilation on .proto file change

---

irohad/execution/CMakeLists.txt
shared_model/backend/protobuf/query_responses/impl/proto_block_query_response.cpp
shared_model/backend/protobuf/query_responses/impl/proto_block_response.cpp
shared_model/backend/protobuf/query_responses/proto_block_response.hpp

fix linking error on linux(clang 6), add protobuf dependency, fix bug
Iroha now compiles on linux with clang 6

fix linking error, add protobuf dependency, fix bug

---

docs/source/core_concepts/index.rst

Change RTD docs levels

---

shared_model/bindings/CMakeLists.txt
shared_model/bindings/bindings.i
shared_model/bindings/model_blocks_query_builder.cpp
shared_model/bindings/model_blocks_query_builder.hpp
test/module/shared_model/bindings/BlocksQueryTest.java
test/module/shared_model/bindings/CMakeLists.txt
test/module/shared_model/bindings/blocks-query-test.py

Adds missing blocks query builders
Allows creating blocks query from bindings
None
None so far

BlocksQueryBuilder in bingins

---

iroha-cli/main.cpp

Now CLI checks if account name is passed in order to create keypair. It used to tell that keys were generated, while no keys were present in the folder.
Now it works
None

Check for account name

---

docker/release/entrypoint.sh

This PR changes configuration file used in release Docker image. Previously, we have been using `config.sample` file. This did not conform to Getting Started guide in the docs.
Along with #1418 makes initial Iroha network deployment process easier for users
None

Fix config file used in release Docker image

---

irohad/execution/impl/query_execution.cpp

Fix iroha build, which has been failing due to usage of old permissions in query execution
Make iroha build again
None

Fix query execution build

---

irohad/torii/impl/command_service.cpp

Fix one more race condition in StatusStream.
One error less.
None.

Fix of torii again

---

test/integration/acceptance/set_account_detail_test.cpp

#1452 was merged without upstream updates, that caused compilation error. In this pr permissions was changed to the new one
Green develop
none

Fix dev build

---

irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/consensus/yac/impl/yac_gate_impl.hpp
irohad/consensus/yac/impl/yac_hash_provider_impl.cpp
irohad/consensus/yac/impl/yac_hash_provider_impl.hpp
irohad/consensus/yac/yac_hash_provider.hpp
irohad/network/consensus_gate.hpp
irohad/simulator/block_creator.hpp
irohad/simulator/impl/simulator.cpp
irohad/simulator/impl/simulator.hpp
irohad/synchronizer/impl/synchronizer_impl.cpp
irohad/synchronizer/impl/synchronizer_impl.hpp
irohad/synchronizer/synchronizer.hpp
shared_model/interfaces/iroha_internal/block_variant.hpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/consensus/yac/yac_hash_provider_test.cpp
test/module/irohad/consensus/yac/yac_mocks.hpp
test/module/irohad/network/network_mocks.hpp
test/module/irohad/simulator/simulator_mocks.hpp
test/module/irohad/simulator/simulator_test.cpp
test/module/irohad/synchronizer/synchronizer_test.cpp

Should be reviewed after #1398 is merged
Updates irohad to use new block variant. Simulator, Synchronizer and YacGate are updated
Will help to process empty blocks in future
None

Update to new block variant

---

irohad/synchronizer/CMakeLists.txt

Eventually, develop might fail to build due to missing dependency in synchronizer's cmake.
Issue example:
```
Scanning dependencies of target synchronizer
...
In file included from /home/igor/cpp/iroha3/irohad/synchronizer/impl/synchronizer_impl.cpp:19:
In file included from /home/igor/cpp/iroha3/shared_model/backend/protobuf/block.hpp:23:
/home/igor/cpp/iroha3/shared_model/backend/protobuf/common_objects/signature.hpp:23:10: fatal error: 'primitive.pb.h'
file not found
#include "primitive.pb.h"
^~~~~~~~~~~~~~~~
```
Fix build.
None
```
cmake --build build
```

Add missing cmake dependency

---

shared_model/interfaces/common_objects/transaction_sequence_common.hpp

Fixes build for users with boos version higher than 1.66
Iroha builds
None

Fix boost version build

---

irohad/simulator/impl/simulator.cpp

Removed one thing, which caused the build failure.
Iroha can be built.
None

[fix] Removed build killer

---

test/system/irohad_test.cpp

The test failed on first run if ledger directory specified in `config.sample` was not empty, then the directory was cleared, and the second run succeeded. Random path is used now for ledger directory.
No more sudden losses of ledger if you forgot to change ledger directory from sample!
None

Use random path in irohad_test

---

.jenkinsci/bindings.groovy
CMakeLists.txt
cmake/Modules/Finded25519.cmake
shared_model/backend/protobuf/CMakeLists.txt
shared_model/bindings/bindings.i
shared_model/interfaces/CMakeLists.txt
shared_model/packages/javascript/tests/queryBuilder.js
shared_model/validators/answer.hpp

- Remove server-side objects from separate shared model build, which fixes failing Android build
- Fix Windows build on Jenkins due to invalid flag used
- Fix Android build on Jenkins, which was always using develop branch for builds
- Fix patching of ed25519 library when it is called from shared model directory, due to wrong absolute path used
- Remove `backend/protobuf` from SWIG interface which is not required. Windows build failed due to this header being present
- Add missing ciso646 header for Windows build
- Enable getTransactions tests on Javascript (__bonus__)
Working build for available platforms: python/java/javascript linux/windows android
None

An assortment of fixes for bindings

---

README.md

Several people were confused with docs. I had to update this section + get rid of Codacy badge.
Updated readme with more relevant information.

Update readme with relevant information

---

shared_model/validators/field_validator.cpp

Fixed error message in IP field validator 
Better English 
Reformatted code
None

Fix error message in IP validator

---

cmake/Modules/Findgrpc.cmake

Improved dependency management logic inside Findgrpc.cmake
Thanks to @lebdron for the help!
Before the change it was not possible to build grpc_grpc target
with protobuf installed in a system and without installed grpc.
None ?
```
cmake --build build --target grpc_grpc
```

Improve Findgrpc.cmake

---

test/module/shared_model/validators/transaction_validator_test.cpp
test/module/shared_model/validators/validators_fixture.hpp

Signed-off-by: Moonraker <ssolonets@gmail.com
Feature/batch meta #1504 was merged partially. This is the missing part
fix build
--

Fix develop

---

irohad/ametsuchi/impl/temporary_wsv_impl.cpp

Use bind in TemporaryWsv apply to avoid early evaluation of execution result
Commands are validated before execution
None

Refactor Temporary Wsv command application

---

example/genesis.block

Delete Peers from Genesis block
Iroha can be used with one instance
--

fix genesis

---

docs/source/api/queries.rst
docs/source/core_concepts/glossary.rst
irohad/execution/impl/query_execution.cpp
irohad/execution/query_execution.hpp
schema/queries.proto
shared_model/backend/protobuf/CMakeLists.txt
shared_model/backend/protobuf/queries/impl/proto_get_pending_transactions.cpp
shared_model/backend/protobuf/queries/proto_get_pending_transactions.hpp
shared_model/backend/protobuf/queries/proto_query.hpp
shared_model/bindings/model_query_builder.cpp
shared_model/bindings/model_query_builder.hpp
shared_model/builders/protobuf/builder_templates/query_template.hpp
shared_model/interfaces/CMakeLists.txt
shared_model/interfaces/queries/get_pending_transactions.hpp
shared_model/interfaces/queries/impl/get_pending_transactions.cpp
shared_model/interfaces/queries/query.hpp
shared_model/validators/query_validator.hpp

This PR adds an interface of GetPendingTransactions query to shared model. 
Currently, the query does NOT perform actual information retrieving (will be implemented after appearing of transactions batches support in develop branch).
Additionally, this pr provides documentation for the new query.
It is a starting point for further development of GetPendingTransactions feature.
None ?
build everything and test everything, even bindings

Add GetPendingTransactions query to shared model

---

shared_model/validators/field_validator.cpp
test/integration/acceptance/tx_acceptance_test.cpp
test/module/irohad/network/block_loader_test.cpp
test/module/irohad/torii/torii_service_test.cpp

Signatures are validated properly, but there is no check for their existence. The pr fixes that.
Also adds test for the Torii (test for the FieldValidator is pretty tedious) for that case

Check the signatures for its size

---

test/integration/binary/CMakeLists.txt

Build of `binary_test` target was broken. Now the target can be built.
BTF can be built.
```
cmake -Bbuild -H. -DSWIG_PYTHON=ON
cmake --build build --target binary_test
```

Fix build of Binary Testing Framework

---

README.md

Fix URL for Jenkins master branch build
Correct Jenkins master branch URL
None

Fix jenkins build link

---

shared_model/interfaces/transaction.hpp
test/framework/batch_helper.hpp
test/module/shared_model/backend_proto/proto_batch_test.cpp
test/module/shared_model/builders/protobuf/test_transaction_builder.hpp

Add test batch creator which is useful for tests in MST
Add composable functions and tests for it
```
cmake -H. -Bbuild && cmake --build build --target proto_batch_test && build/test_bin/proto_batch_test
```

Implement test batch builder

---

shared_model/bindings/model_transaction_builder.cpp
shared_model/bindings/model_transaction_builder.hpp
shared_model/builders/protobuf/builder_templates/transaction_template.hpp

Adds `batchMeta` setter for transaction builder.
Now clients can set batch information.
None

Add batchMeta to transaction builder

---

README.md

Signed-off-by: Nikolay Yushkevich <n.yushkevich@hotmail.com>
Correct link in Android sample app and delete badge with low coverage data (it is not correct).

Delete codecov badge and android demo link

---

shared_model/backend/protobuf/impl/proposal.cpp
shared_model/backend/protobuf/proposal.hpp
shared_model/interfaces/iroha_internal/proposal.hpp

Since it is required to vote for proposals, and YAC operates with hashes, a corresponding method is added to proposal interface.
Can vote for proposals.
None.

Add hash to proposal

---

.jenkinsci/debug-build.groovy
.jenkinsci/release-build.groovy

Fixes PR #1606. It lacked the check for not defined variable `CHANGE_BRANCH` when current build refers to a branch, not PR
Correct conditional statement behaviour for both PR and branch builds
None

fix missing property CHANGE_BRANCH

---

.jenkinsci/debug-build.groovy
.jenkinsci/docker-pull-or-build.groovy
.jenkinsci/release-build.groovy
Jenkinsfile

Another fix for #1606. Check for branch name inside `dockerPullOrUpdate` function before pushing into Docker registry.
Updated images on Dockerhub
None

Fix CI docker push

---

cmake/Modules/Finded25519.cmake

Remove patch call for inexisting patch

Remove patch call in ed25519

---

example/java/build_library.sh
example/java/prepare.sh

If one of internal commands inside any of bash scripts fail (exit with non-0 code), the whole script continues, giving a false hope that bindings were built.
This change prevents this behavior, and make the whole script fail if any subcommand fails.
None.

Make scripts fail if any of bash cmds fail

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/storage.hpp
irohad/main/irohad.cpp

Before the fix, launching of irohad with --overwrite-ledger option did not lead to blocks removal.
Desired behavior restored.
System test for the option is missing - will be created in [IR-1569](https://soramitsu.atlassian.net/browse/IR-1569)
* run clean irohad
* send several transactions
* rerun irohad with --overwrite-ledger option
* send one more transaction
* ensure that transaction was committed
```
irohad --config config.sample --genesis_block genesis.block --keypair_name node0 --overwrite-ledger
```

Fix --overwrite-ledger option behavior

---

irohad/ametsuchi/impl/postgres_command_executor.cpp
test/integration/acceptance/revoke_permission_test.cpp

Refactor error messages in postgres command executor in order to fix the test. Also, previously removeSignatory command returned wrong error message in case of missing permission(953 line of postgres_command_executor.cpp)
Less bugs.

Fix revoke permission test

---

irohad/ordering/CMakeLists.txt
irohad/ordering/impl/on_demand_connection_manager.cpp
irohad/ordering/impl/on_demand_connection_manager.hpp
test/module/irohad/ordering/on_demand_connection_manager_test.cpp

Recent discussions lead to addition of a new consumer peer. This change is now reflected in the code.
Easier peer management
for-loops

Add missing peer to on-demand OS connection manager

---

test/module/irohad/torii/CMakeLists.txt
test/module/irohad/torii/torii_service_test.cpp

Fix torii command service tests
After feature/mst_batches will be merged into trunk, trunk should be a base branch for this pull request.

Fix torii service test

---

docs/source/guides/build.rst
shared_model/packages/javascript/scripts/install-dependencies.sh
snap/snapcraft.yaml

Boost::thread was missing [in doc](https://github.com/hyperledger/iroha/pull/1575#issuecomment-414546766) (thx @dram) and in some other places

Add thread component in boost bootstrapping

---

test/integration/acceptance/CMakeLists.txt
test/integration/acceptance/acceptance_fixture.cpp
test/integration/acceptance/acceptance_fixture.hpp
test/integration/acceptance/get_account_test.cpp

Add GetAccount acceptance test
Coverage is increased
None

Feature GetAccount test

---

.jenkinsci/debug-build.groovy
.jenkinsci/docker-pull-or-build.groovy
.jenkinsci/doxygen.groovy
.jenkinsci/linux-post-step.groovy
.jenkinsci/release-build.groovy
Jenkinsfile

This is a hotfix. make dev branch equivalent to develop
Allow for Docker images and build artifacts to be uploaded
The hotfix should be rolled back once 'dev' -> 'develop' branch situation backs to normal

HOTFIX: make dev branch equivalent to develop

---

cmake/functions.cmake
irohad/ordering/impl/on_demand_connection_manager.cpp
irohad/ordering/impl/on_demand_connection_manager.hpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.hpp
irohad/ordering/impl/on_demand_os_client_grpc.cpp
irohad/ordering/impl/on_demand_os_client_grpc.hpp
irohad/ordering/impl/on_demand_os_server_grpc.cpp
irohad/ordering/impl/on_demand_os_server_grpc.hpp
irohad/ordering/on_demand_ordering_service.hpp
irohad/ordering/on_demand_os_transport.hpp
schema/ordering.proto
test/module/irohad/ordering/on_demand_connection_manager_test.cpp
test/module/irohad/ordering/on_demand_os_client_grpc_test.cpp
test/module/irohad/ordering/on_demand_os_server_grpc_test.cpp
test/module/irohad/ordering/on_demand_os_test.cpp
test/module/irohad/ordering/ordering_mocks.hpp

Signed-off-by: Andrei Lebedev <lebdron@gmail.com>
Previous version of OS algorithm had a bug with peers and rounds, which is fixed in this pull request. Interfaces are changed to reflect the fixes. OS receives transactions for a specific round, and it is also possible to close a specific round by using the interface.
Correct on-demand OS
None

Fix BFT OS algorithm and interfaces

---

test/integration/acceptance/CMakeLists.txt
test/integration/acceptance/get_asset_info_test.cpp

This pr introduce integration tests for GetAssetInfo query
More coverage

Add GetAssetInfo acceptance test

---

docs/source/index.rst

This pull request removes last reviewed line in docs.
This line doesn't update automatically and now it's set to the end of march. That's pretty confusing so I suggest to do the easiest fix possible.
None.
We can implement another solution which can be possible to bump this date after each doc update.

Remove confusing last reviewed date from docs

---

clean.sh
shared_model/clean.sh
shared_model/cmake/dependencies.cmake

This moves out `external` directory from project root to the directory created during build.
Allows to use the same project directory for different builds, such as gcc/clang, or linux/mac
None

Move external dependencies dir

---

.jenkinsci/artifacts.groovy

Make `curl` less verbose due to potential sensitive information disclosure
Less verbosity, more security
None

Less verbose curl

---

shared_model/interfaces/iroha_internal/query_response_factory.hpp
test/module/shared_model/backend_proto/proto_query_response_factory_test.cpp

Fix build of dev branch.
Dev will be built.
None.

Dev Build Fix

---

docker/develop/Dockerfile

Add vim editor into develop Docker image
no more `apt-get update && apt-get -y install <your_favorite_editor>` (now vim is your favorite)
Need to learn how to quit vim without a reboot

Add vim into develop Docker image

---

irohad/main/irohad.cpp

I know you waited it for so long time. Beware! of the verbosity flag
Now logs can be lesser, than blockstore itself

Add irohad verbosity flag

---

docker/dependencies/Dockerfile
docker/develop/Dockerfile

Fix URL for downloading sonar-scanner. The previous one is now prompts for basic auth credentials.
Docker image can now be built
None

Fix sonar-scanner URL

---

shared_model/CMakeLists.txt
shared_model/cryptography/model_impl/CMakeLists.txt
shared_model/interfaces/CMakeLists.txt
shared_model/utils/CMakeLists.txt
shared_model/utils/string_builder.cpp
shared_model/utils/string_builder.hpp

Move method implementations to cpp to eliminate redundant object code generation.
Reduced compilation time.
None.

Move string builder implementation to cpp

---

test/module/irohad/multi_sig_transactions/mst_test_helpers.hpp
test/module/irohad/network/CMakeLists.txt
test/module/irohad/synchronizer/CMakeLists.txt
test/module/irohad/torii/processor/transaction_processor_test.cpp

On my system (clang 7.0.0 + ninja) that resolves build issue. Hope that can help someone else
Iroha can be built on more systems

Fix build on some platforms

---

irohad/ametsuchi/impl/block_index.hpp
irohad/ametsuchi/impl/postgres_block_index.cpp
irohad/ametsuchi/impl/postgres_block_index.hpp

This PR refactors postgers_block_index to construct a single query instead of multiple calls to the database.
Supposedly improved performance.
None

Refactor block index to construct a single query for each block

---

shared_model/interfaces/iroha_internal/transaction_batch_parser_impl.cpp

Simplify and speed up parseBatchesImpl function.
Easier to read, seemingly less computations.
Yet to be found.

internal: parseBatchesImpl fix

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/postgres_query_executor.cpp
irohad/ametsuchi/impl/postgres_query_executor.hpp
irohad/ametsuchi/impl/storage_impl.cpp
irohad/ametsuchi/impl/storage_impl.hpp
irohad/ametsuchi/query_executor_factory.hpp
irohad/main/application.cpp
irohad/main/application.hpp
irohad/torii/processor/impl/query_processor_impl.cpp
irohad/torii/processor/query_processor_impl.hpp
shared_model/backend/protobuf/impl/proto_query_response_factory.cpp
shared_model/backend/protobuf/proto_query_response_factory.hpp
shared_model/interfaces/iroha_internal/query_response_factory.hpp
test/module/iroha-cli/client_test.cpp
test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
test/module/irohad/torii/processor/query_processor_test.cpp
test/module/irohad/torii/torii_queries_test.cpp

Introducing stateful error query responses.
Users will see, why their queries fail.
None.

Query Error Responses

---

irohad/torii/impl/command_service_transport_grpc.cpp
shared_model/backend/protobuf/CMakeLists.txt
shared_model/backend/protobuf/impl/proto_tx_status_factory.cpp
shared_model/backend/protobuf/transaction_responses/impl/proto_tx_response.cpp
shared_model/backend/protobuf/transaction_responses/proto_tx_response.hpp
shared_model/interfaces/CMakeLists.txt
shared_model/interfaces/transaction_responses/impl/tx_response.cpp
shared_model/interfaces/transaction_responses/tx_response.hpp
shared_model/interfaces/transaction_responses/tx_response_variant.hpp

Refactor tx response variant with external templates

Refactor tx response variant with external templates

---

irohad/ametsuchi/mutable_storage.hpp
test/module/irohad/ametsuchi/postgres_query_executor_test.cpp

Add missing includes
Project now builds
No

Fix missing includes

---

irohad/ordering/CMakeLists.txt
irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.hpp
test/module/irohad/ordering/on_demand_os_test.cpp

Instead of manually constructing protobuf object, add a factory for on demand ordering service.
No dependency on protobuf
none

Use proposal factory for OnDemandOrderingService

---

irohad/consensus/impl/round.cpp
irohad/consensus/round.hpp
irohad/consensus/yac/messages.hpp
irohad/consensus/yac/yac_hash_provider.hpp
shared_model/utils/string_builder.hpp

toString() method for iroha::consensus::yac::CommitMessage, iroha::consensus::yac::RejectMessage and their members.
pretty logs
more hearer includes

pretty printing YAC messages

---

docker/dependencies/Dockerfile
docker/develop/Dockerfile

Add GCC-7 and clang-6 compilers into develop Dockerfile. It will later be used in CI to test Iroha is able to compile with different compilers.
Make sure we support modern versions of compilers
None
*__clang__*
`cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang-6.0`
*__gcc-7__*
`cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7`

Add GCC-7 and clang-6 into Dockerfile

---

test/fuzzing/CMakeLists.txt
test/fuzzing/consensus_fuzz.cpp
test/fuzzing/ordering_gate_fuzz.cpp

Fuzzing for consensus (**SendState** endpoint).
One more fuzzing-covered endpoint.
Need CI integration.
```
cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++  -DFUZZING=ON ..
make consensus_fuzz
```

Consensus fuzzing

---

iroha-cli/impl/query_response_handler.cpp
irohad/ordering/impl/on_demand_os_client_grpc.cpp
shared_model/backend/protobuf/CMakeLists.txt
shared_model/backend/protobuf/impl/block.cpp
shared_model/backend/protobuf/impl/proposal.cpp
shared_model/backend/protobuf/impl/transaction.cpp
shared_model/backend/protobuf/transaction.hpp
shared_model/interfaces/iroha_internal/transaction_batch.hpp
shared_model/interfaces/transaction.hpp
test/integration/acceptance/replay_test.cpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp
test/module/irohad/ametsuchi/block_query_test.cpp
test/module/irohad/ametsuchi/block_query_transfer_test.cpp
test/module/irohad/ametsuchi/kv_storage_test.cpp
test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
test/module/irohad/network/block_loader_test.cpp
test/module/irohad/ordering/ordering_gate_test.cpp
test/module/irohad/simulator/simulator_test.cpp
test/module/irohad/validation/stateful_validator_test.cpp
test/module/shared_model/builders/protobuf/block_builder_test.cpp
test/module/shared_model/builders/protobuf/transport_builder_test.cpp
test/module/shared_model/converters/json_proto_converter_test.cpp
test/module/shared_model/validators/block_validator_test.cpp
test/module/shared_model/validators/container_validator_test.cpp
test/module/shared_model/validators/field_validator_test.cpp

PIMPL idiom for transaction class is introduced in this PR.
Reduced compilation time.
Some of the tests were rewritten, taking into account lack of copy ctor, which was added later, so they now introduce vector wrapping. Corresponding task is already created.

PIMPL for Transaction

---

irohad/ordering/impl/on_demand_os_client_grpc.cpp
shared_model/backend/protobuf/commands/impl/proto_command.cpp
shared_model/backend/protobuf/commands/proto_command.hpp
test/module/shared_model/backend_proto/shared_proto_commands_test.cpp

Introduce PIMPL idiom for Command class and removed a lot of unnecessary code.
Reduced build time.
None.

Pimpl for Command

---

test/fuzzing/CMakeLists.txt
test/fuzzing/mst_fuzz.cpp

Fuzzing for MST endpoint (**SendState**).
One more endpoint covered.
CI is needed.
Also it looks like a false positive warning from Address Sanitizer (at least I couldn't find a problem - see https://gist.github.com/luckychess/b65bd40e958887273e86a0a535cc896d).
```
cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++  -DFUZZING=ON ..
make mst_fuzz
```

MST fuzzing

---

irohad/ametsuchi/CMakeLists.txt
irohad/ametsuchi/impl/tx_presence_cache_impl.cpp
irohad/ametsuchi/impl/tx_presence_cache_impl.hpp
irohad/ametsuchi/tx_cache_response.hpp
irohad/torii/impl/command_service_impl.cpp
shared_model/interfaces/base/signable.hpp
test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/block_query_test.cpp
test/module/irohad/ametsuchi/tx_presence_cache_test.cpp
test/module/shared_model/interface_mocks.hpp

Implementation of persistent cache for transactions.
It's impossible to deal with replays without this cache (or something similar).
None.
```
make tx_presence_cache_test
```

Persistent cache implementation

---

irohad/main/application.cpp
irohad/network/CMakeLists.txt
irohad/network/impl/peer_communication_service_impl.cpp
irohad/network/impl/peer_communication_service_impl.hpp
irohad/network/ordering_gate.hpp
irohad/network/ordering_gate_common.cpp
irohad/network/ordering_gate_common.hpp
irohad/network/peer_communication_service.hpp
irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_ordering_gate.hpp
irohad/ordering/impl/ordering_gate_impl.cpp
irohad/ordering/impl/ordering_gate_impl.hpp
irohad/simulator/CMakeLists.txt
irohad/simulator/impl/simulator.cpp
irohad/simulator/impl/simulator.hpp
irohad/simulator/verified_proposal_creator.hpp
irohad/torii/processor/impl/transaction_processor_impl.cpp
test/framework/CMakeLists.txt
test/framework/integration_framework/integration_test_framework.cpp
test/fuzzing/status_fuzz.cpp
test/fuzzing/torii_fuzz.cpp
test/module/iroha-cli/client_test.cpp
test/module/irohad/network/network_mocks.hpp
test/module/irohad/ordering/CMakeLists.txt
test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
test/module/irohad/ordering/ordering_gate_test.cpp
test/module/irohad/simulator/simulator_test.cpp
test/module/irohad/torii/CMakeLists.txt
test/module/irohad/torii/processor/transaction_processor_test.cpp
test/module/irohad/torii/torii_service_test.cpp

It is possible that ordering service will not respond to node proposal request, in which case an empty proposal event has to be emitted. This pull request replaces proposal observable with optional proposal and round.
Even closer to BFT pipeline
None

Refactor ordering gate observable to optional

---

irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_ordering_gate.hpp
shared_model/backend/protobuf/proto_proposal_factory.hpp
shared_model/interfaces/iroha_internal/unsafe_proposal_factory.hpp
test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
test/module/shared_model/interface_mocks.hpp

This PR adds a replay check to ordering gate via transaction cache
No replays in ordering gate
None

Replay check to ordering gate

---

irohad/ordering/impl/single_peer_ordering_service.cpp

With current code it is possible that if proposal is not published proposal_height_ is still updated. That may cause Iroha to stop accepting new proposals due to invalid value of proposal height
Fixed problem
None

Fix proposal height set

---

irohad/ametsuchi/tx_presence_cache_utils.hpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp

This Pull request adds a couple of functions to make work with tx_presence_cache more convenient.
Simpler code
None

Add functions to simplify work with tx cache

---

irohad/main/CMakeLists.txt
irohad/main/application.cpp
irohad/main/application.hpp

Pull request replaces cache mock im application.cpp to its fair implementation.
One step closer to the life without replays.
None.

Replace cache mock to cache implementation in application.cpp

---

shared_model/backend/protobuf/queries/impl/proto_query.cpp
shared_model/backend/protobuf/queries/proto_query.hpp
shared_model/validators/query_validator.hpp

This PR inroduces Pimpl idiom for Queries.
Faster build.
None.

Pimpl for Queries

---

irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/consensus/yac/impl/yac_gate_impl.hpp
irohad/network/consensus_gate.hpp
irohad/network/impl/peer_communication_service_impl.cpp
irohad/network/impl/peer_communication_service_impl.hpp
irohad/network/peer_communication_service.hpp
irohad/simulator/CMakeLists.txt
irohad/simulator/block_creator.hpp
irohad/simulator/block_creator_common.cpp
irohad/simulator/block_creator_common.hpp
irohad/simulator/impl/simulator.cpp
irohad/simulator/impl/simulator.hpp
irohad/simulator/verified_proposal_creator.hpp
irohad/simulator/verified_proposal_creator_common.cpp
irohad/simulator/verified_proposal_creator_common.hpp
irohad/torii/processor/CMakeLists.txt
irohad/torii/processor/impl/transaction_processor_impl.cpp
test/framework/integration_framework/integration_test_framework.cpp
test/module/iroha-cli/client_test.cpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/network/network_mocks.hpp
test/module/irohad/simulator/simulator_mocks.hpp
test/module/irohad/simulator/simulator_test.cpp
test/module/irohad/torii/processor/transaction_processor_test.cpp
test/module/irohad/torii/torii_service_test.cpp

Correctly handle `optional<Proposal>` in simulator, and return `boost::none` instead of block if there was no proposal.
Another step to handle `none` from ordering service.
None?

Refactor simulator with optional

---

test/integration/acceptance/fake_peer_example_test.cpp

This is an example of using pre-on-demand Ordering Gate/Service interface introduced in #1849.
It is a duplicate of  #1859, introduced due to my loss of permissions to push to the branch of the original PR.
Usage example
Pretty stupid code, should be removed after some real ITF tests on Ordering appear.
`fake_peer_example_test`

fake peer ordering service usage example

---

example/python/tx-example.py
shared_model/backend/protobuf/queries/proto_query.hpp

Bindings could not build due to `final` word, which can not be processed by swig. It was changed to `FINAL` and now it works.
Also in this PR tx-example was updated to the new naming of the services
Bindings can be built
None

Fix bindings

---

iroha-cli/main.cpp

Little PR with the latest suggestion from #1893 from @MBoldyrev 
All review suggestions are fulfilled 
None

Small review fix

---

irohad/main/impl/on_demand_ordering_init.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp

More logging in OnDemandOrderingServiceImpl.
Easier debugging.
Performance decrease.

OnDemand OS verbose logging

---

irohad/consensus/yac/impl/yac_gate_impl.cpp
irohad/consensus/yac/impl/yac_hash_provider_impl.cpp
irohad/consensus/yac/impl/yac_hash_provider_impl.hpp
irohad/consensus/yac/transport/yac_pb_converters.hpp
irohad/consensus/yac/yac_hash_provider.hpp
irohad/main/impl/on_demand_ordering_init.cpp
irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_ordering_gate.hpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.hpp
libs/common/delay.hpp
test/CMakeLists.txt
test/framework/integration_framework/integration_test_framework.cpp
test/module/irohad/consensus/yac/yac_hash_provider_test.cpp
test/module/irohad/consensus/yac/yac_mocks.hpp
test/module/irohad/ordering/on_demand_ordering_gate_test.cpp

Enable irohad system test
- Pass boost::none instead of empty proposal
- Use delay to reduce the number of reject rounds
Working OS
Yet to discover

Enable system test

---

docs/source/requirements.txt

Bump `requests` version.
No more vulnerability message:

Bump "requests" version

---

docs/source/api/queries.rst
shared_model/schema/qry_responses.proto

Update documentation with new query pagination logic
Up to date documentation
None

Add documentation for queries pagination

---

irohad/main/irohad.cpp

Fix reading of verbosity flag before its initialization
Working verbosity flag 
None

Fix verbosity flag

---

.jenkinsci/debug-build.groovy
.jenkinsci/release-build.groovy

Signed-off-by: Alexey Rodionov <rodionov@soramitsu.co.jp>
Due to disabled builds on arm and aarch, docker tags creation gots an error. We can remove tags or enable builds.
Successful pushes to dockerhub
Manifests for arm and aarch are removed for now.

Remove unused docker manifests

---

test/integration/acceptance/revoke_permission_test.cpp

[IR-79](https://jira.hyperledger.org/browse/IR-79), [Wiki](https://soramitsu.atlassian.net/wiki/spaces/IS/pages/835911684/Revoke+Permission+Strategy)
Use case
- Account1 has can_grant permission.
- Account1 grants a permission to account2.
- Account1 lost can_grant permission.
- Account1 still can do revoke permission from account2
is now treated as a perfectly correct behaviour, though earlier it was considered as a bug. Thus, tests needs to be adjusted to the new standard.
Formalized correct behaviour.
None.

Revoke permission adjusted behaviour and tests

---

irohad/consensus/yac/impl/yac.cpp
irohad/consensus/yac/storage/impl/yac_proposal_storage.cpp
irohad/main/impl/on_demand_ordering_init.cpp
irohad/multi_sig_transactions/state/impl/mst_state.cpp
irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
irohad/ordering/impl/on_demand_connection_manager.cpp
irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/torii/impl/command_service_impl.cpp
irohad/torii/impl/command_service_transport_grpc.cpp
test/framework/integration_framework/fake_peer/fake_peer.cpp

- Log `Round` objects by calling `toString`
- Remove remaining explicit `toString` calls for logging in `irohad`
- Fix round log in on demand ordering init
Simpler code
None?

Refactor round logging; replace remaining toString calls

---

test/fuzzing/CMakeLists.txt
test/fuzzing/ordering_service_fixture.hpp
test/fuzzing/request_proposal_fuzz.cpp

Updates request proposal fuzzing target so it can be compiled

Update RequestProposal endpoint fuzzing

---

test/fuzzing/torii_fuzz.cpp

Updates torii fuzzing target so it's able to be compiled

Update Torii Fuzzing

---

test/module/irohad/ametsuchi/CMakeLists.txt
test/module/irohad/ametsuchi/postgres_executor_test.cpp

Remove common object builders from Postgres executor test

remove common object builders from postgres executor test

---

.jenkinsci/docker-pull-or-build.groovy

Pull docker image or build it before use
CI will pass in master 
None

Fix, docker pull in CI

---

docs/source/api/commands.rst
docs/source/api/queries.rst

Stateful validation errors were only described in this [POW](https://soramitsu.atlassian.net/wiki/spaces/IS/pages/439189508/POW+N+075+Stateful+response), but they should lie in actual Iroha documentation, so all the errors are transferred here.
More documentation.
None.

Stateful Validation Errors to Documentation

---

irohad/main/application.cpp
irohad/main/application.hpp

Field declarations changed according their initialisation order and a bit of code cleaning.
A bit more consistent order of destructor calls.
None.

Irohad field reorder

---

cmake/Modules/Findfmt.cmake
cmake/Modules/Findspdlog.cmake
cmake/dependencies.cmake
libs/logger/CMakeLists.txt
libs/logger/logger.hpp
libs/logger/logger_spdlog.cpp

This change
- updates used `spdlog` library to 1.3.1
- adds external `fmt` library and its usage to the new logger
- adds version checking of the mentioned libs to the cmake `find_package` scripts
One more step towards the new logger.
The cmake code needs a thorough review as I am not experienced in it.

New libs for the new logger

---

deploy/ansible/roles/iroha-docker/README.md

This change tries to make ansible deployment docs easier to understand.

Ansible docs correction

---

docs/source/requirements.txt

Signed-off-by: Nikolay Yushkevich <n.yushkevich@hotmail.com>
In order to fix soramitsu/localized_docs issue at first we need to update an original file for dependencies https://jira.hyperledger.org/browse/IR-150
Less error prone code
None

IR-150 Fix security vulnerability

---

irohad/torii/impl/command_service_impl.cpp
irohad/torii/impl/command_service_transport_grpc.cpp

Merge rc2hotfix2 from master to develop

---

test/load/Dockerfile
test/load/README.md
test/load/docker-compose.yml
test/load/docker_start.sh
test/load/locustfile.py

Add send-tx load test based on locust.io
This is an example of load test to be used as a reference for more complex test cases
[README.md](https://github.com/lebdron/iroha/blob/7426dc869654076b2d8c37cd74d4add6d9ffde9f/test/load/README.md)

Add send-tx load test based on locust.io

---

test/load/README.md

Clarify directory for irohalib and ed25519
Add indents for numbered lists

Fix load test documentation

---

irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_os_server_grpc.cpp

Small optimizations of objects passing.
Avoid copying in several places.

Micro fix: move things

---

irohad/ordering/impl/on_demand_ordering_service_impl.cpp

Fixed old proposals removal.
Eliminated one cause of memory growth.

OrderingService: fixed old proposals wipe

---

docs/source/guides/deployment.rst

Received several questions about broken links in deployment instructions, so I tried and fixed those
No broken links in docs
No apparent ones

Fixed links in deploy instructions

---

irohad/ordering/impl/on_demand_ordering_gate.cpp

Reduce the scope of lock in OnDemandOrderingGate since batches from cache can be sent to ordering service concurrently with transactions from clients
Iroha does not become unresponsive after some period of time with constant load.
None.
Run load test from `test/load` directory.

Fix locking in OnDemandOrderingGate

---

irohad/ordering/impl/ordering_gate_cache/on_demand_cache.cpp

Just move them.
Saves energy.
One more line of code to maintain.

Micro fix: move batches in OrderingGateCache::pop()

---

irohad/ordering/impl/on_demand_ordering_service_impl.cpp

The `assert` macro has effect only in debug builds. We should also handle branches not meeting the asserted condition that will otherwise crash the program in the release builds.
Prevents uninformative crash in non-debug builds.

Storage: fix assertion

---

irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.hpp

Replaced a thread-unsafe class method with a standalone local function.
Thread-unsafe logic concentrated in a single place. (Hopefully) better readability.

OnDemandOrderingServiceImpl: reworked emitProposal

---

irohad/network/ordering_gate_common.cpp
irohad/network/ordering_gate_common.hpp
irohad/ordering/impl/on_demand_connection_manager.cpp
irohad/ordering/impl/on_demand_connection_manager.hpp
irohad/ordering/impl/on_demand_ordering_gate.cpp
irohad/ordering/impl/on_demand_ordering_gate.hpp
irohad/ordering/impl/on_demand_ordering_service_impl.cpp
irohad/ordering/impl/on_demand_ordering_service_impl.hpp
irohad/ordering/impl/on_demand_os_client_grpc.cpp
irohad/ordering/impl/on_demand_os_client_grpc.hpp
irohad/ordering/impl/on_demand_os_server_grpc.cpp
irohad/ordering/on_demand_os_transport.hpp
irohad/simulator/block_creator_common.hpp
irohad/validation/impl/stateful_validator_impl.cpp
irohad/validation/stateful_validator_common.hpp
shared_model/backend/protobuf/proto_proposal_factory.hpp
test/framework/integration_framework/integration_test_framework.hpp
test/integration/acceptance/tx_acceptance_test.cpp
test/module/irohad/consensus/yac/yac_gate_test.cpp
test/module/irohad/consensus/yac/yac_hash_provider_test.cpp
test/module/irohad/ordering/mock_on_demand_os_notification.hpp
test/module/irohad/ordering/on_demand_connection_manager_test.cpp
test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
test/module/irohad/ordering/on_demand_os_server_grpc_test.cpp
test/module/irohad/ordering/ordering_mocks.hpp
test/module/irohad/simulator/simulator_test.cpp

This change avoids copying of proposal where possible and makes the shared proposal constant. Also it applies the new aliasing policy to `ProposalType`.
Less copying, less chances of unintended changes to shared proposals.
Longer type names due to the new aliasing policy.

Reworked proposal sharing

---

.jenkinsci-new/builders/x64-linux-build-steps.groovy
.jenkinsci-new/builders/x64-mac-build-steps.groovy
.jenkinsci-new/text-variables.groovy
Jenkinsfile-new

[DOPS-292](https://soramitsu.atlassian.net/browse/DOPS-292)
add -DUSE_BTF=ON for cmake configuration on CI
It always` false`,  `true` if  build type "Before merge to trunk"

Add -DUSE_BTF=ON cmake configuration parameter on CI

---

irohad/torii/impl/command_service_impl.cpp

Non final txs statuses were removed from the list of final statuses.

Less Transaction Final Statuses

---

CONTRIBUTING.md

Just adding a small link
Some contributors might find the linked instructions useful
none

Adding a link for PRs from forks into CONTRIBUTING.md

---

README.md

Fixing errors of #2100 and updating info in README.md file
Updated info
¯\_(ツ)_/¯

Fix/README.md Update

---

irohad/ametsuchi/impl/postgres_query_executor.cpp
irohad/consensus/yac/impl/yac.cpp
irohad/main/iroha_conf_loader.cpp
irohad/main/iroha_conf_loader.hpp
irohad/main/irohad.cpp
libs/logger/CMakeLists.txt
libs/logger/logger_spdlog.cpp

Here is a set of changes (each in a separate commit):
- moved log levels translation to a separate function which initializes a static map as soon as it is needed (fixes static initialization races)
- fixed formatting due to libfmt upgrade (seems that any `{..}` means a formatted argument now)
- added `tryGetValByKey` specialization for optionals to config file parser. Now optional config members can be made seamlessly
- made the logger configuration section of the config file optional (to avoid an unwanted breaking change)
Fixes & improvements.
Undefined.
b

Fixes to the new logger

---

irohad/ametsuchi/impl/storage_impl.cpp
test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
test/module/irohad/ametsuchi/ametsuchi_test.cpp

RC4 Hotfix 1 - TemporaryWsv deadlock, checkTxPresence performance

---

test/fuzzing/find_fuzz.cpp
test/fuzzing/mst_fuzz.cpp
test/fuzzing/status_fuzz.cpp
test/fuzzing/torii_fuzz.cpp

As our CI does not build fuzzing targets, these get outdated over time. This change fixes broken things because of recent changes in dependees.
Hopefully fuzzing is back.
This does not prevent the cause of such problems - missing CI checks for fuzzing.

Fuzzing fix

---

CONTRIBUTING.md

We are fixing the docs so .md's from the repo could be integrated into ReadTheDocs. Current PR is changing one of the files to be integrated into the documentation nicely as an example. 
Closer to making docs better
if one of the integrated files are changed without considering it, that section on ReadTheDocs might look bad

CONTRIBUTING.md fix for transition to ReadTheDocs

---

irohad/ametsuchi/impl/storage_impl.cpp
irohad/main/application.cpp

When removing all contents of database tables, triggers for constraints significantly slow the process. This PR makes complete data cleaning ignore these constraints which saves much time.
Faster tables clearing.

StorageImpl: faster cleanup
