hyperledger/iroha

- .gitignore
- core/consensus/consensus_event.hpp
- core/consensus/event.hpp
- core/model/transaction.cpp
- core/repository/consensus/merkle_transaction_repository.hpp
Fixed following warnings:
- wrong initialization order in constructors (http://stackoverflow.com/questions/1564937/gcc-warning-will-be-initialized-after)
- comparison between signed and unsigned integer expressions
- no return statement in function returning non-void
**Not fixed** (I believe they will disappear after further developing): 
- unused parameter ‘from’
- /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64: linker input file unused because linking not done
- defined but not used
Warnings may lead to errors. It is better to fix them now, without risk of getting errors in future.
> Fixed warnings during make

- circle.yml
For some reason build process doesn't use cached `hyperledger/iroha-dev` while it executes `build.sh`. Fixing.
> Fix1 circle.yml

- docker/config-discovery/config-server.py
2**30 equals to 1G for a socket recv buff.
This value causes the script throw MemErorr exception on some machine that has not enough memory space.
> use 1M instead of 1G for recv buff

- dependencies.cmake
- smart_contract/repository/CMakeLists.txt
Added following link libraries:
- create_objects_helper
- java_data_structure
Change libjvm from "so" to "dylib".
I tested on MacOS 10.11.6.
> Fix cmake file for MacOS. Add target link libraries.

- core/consensus/sumeragi.cpp
ThreadPool interface has changed.
https://github.com/Warchant/thread-pool-cpp/blob/master/thread_pool/thread_pool.hpp#L117
So, apply `std::move` and `mutable` to the `task` function.
> Fix memory leaks

- test/module/utils/CMakeLists.txt
- test/module/utils/exception_test.cpp
- test/module/utils/logger_test.cpp
I added test programs about logger and exception.
> Add logger and exception test

- irohad/peer_service/peer_service.hpp
I got the following error when building iroha.
```
In file included from /home/debian/workspace/iroha/irohad/peer_service/monitor.hpp:19:0,
from /home/debian/workspace/iroha/irohad/peer_service/monitor.cpp:17:
/home/debian/workspace/iroha/irohad/peer_service/peer_service.hpp: In member function 'bool peer_service::Node::operator>(const peer_service::Node&) const':
/home/debian/workspace/iroha/irohad/peer_service/peer_service.hpp:81:44: error: call of overloaded 'abs(double)' is ambiguous
return (std::abs(trust_ - node.trust_) < -1e5) ? created_ < node.created_
```
This PR makes fix it.
> Fix error about ambiguous abs(double) in peer_service

- libs/handler_map/handler_map.hpp
Adds a class that allows simple argument polymorphism
This map is required for `CommandExecutor`, `CommandValidator`, and also will be useful in `Torii`
```C++
HandlerMap<dao::Command, bool> map_;
std::function<bool(const dao::AddPeer&)> f = ...
map_.insert(f)
...
dao::AddPeer add_peer_cmd;
dao::Command &cmd = add_peer_cmd;
map_.find(cmd).value_or([](const dao::Command&){ 
// handler not found
})(cmd)
```
> Add HandlerMap class

- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
Small refactor torii test.
To remove redundant capture.
`[this, runner = runner]` -> `[this]`
> Remove redundant capture

- irohad/model/transaction.hpp
- test/module/irohad/model/converters/pb_query_responses_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
This pull request removes redundant methods (setTxCounter and setCreatorAccountId) and removes their references from tests.
> remove setTxCounter and setCreatorAccountId from Transaction

- irohad/main/application.cpp
- irohad/network/consensus_gate.hpp
- irohad/simulator/impl/simulator.cpp
- irohad/simulator/impl/simulator.hpp
- irohad/synchronizer/impl/synchronizer_impl.cpp
- irohad/synchronizer/impl/synchronizer_impl.hpp
- test/module/irohad/network/network_mocks.hpp
- test/module/irohad/simulator/simulator_test.cpp
- test/module/irohad/synchronizer/synchronizer_test.cpp
Change `Simulator` and `Synchronizer` interface for explicit subscription to `OrderingGate` and `ConsensusGate`
Explicit dependency in constructor makes the usage less error prone
`shared_ptr`s to `OrderingGate` and `ConsensusGate` should be passed to constructors of `Simulator` and `Synchronizer`
- Subscription to ordering and consensus gates is in constructors
- Add fixture to synchronizer test
- Add mock consensus gate
> Refactor simulator and synchronizer interface

- clean.sh
- schema/CMakeLists.txt
Whenever you try to perform a clean build with 8 or more threads, it will fail because `endpoint` requires `block.pb.h` but has no linkage dependency on `schema` target. I fixed this in this PR.
> Fix build error for 8 threads

- irohad/consensus/yac/impl/peer_orderer_impl.cpp
- irohad/consensus/yac/impl/peer_orderer_impl.hpp
- irohad/main/application.cpp
This pr provides fix of responsibility in dependency of `PeerOrdererImpl`.
Current implementation use only subset of wsv queries - peer queries.
> Fix dependency of peer orderer implementation

- irohad/model/generators/impl/block_generator.cpp
`swarm-deploy.sh` used block generator for genesis block. Since nodes are deployed sequentially, timestamps of genesis blocks were different, which resulted in different genesis block hash.
This PR fixes the creation timestamp of genesis block to 0.
> Fix genesis block generator yielding different blocks due to timestamp

- irohad/ametsuchi/CMakeLists.txt
- irohad/ametsuchi/impl/flat_file_block_query.cpp
- irohad/ametsuchi/impl/flat_file_block_query.hpp
- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/mutable_storage_impl.hpp
- irohad/ametsuchi/impl/storage_impl.cpp
- irohad/ametsuchi/impl/storage_impl.hpp
- irohad/ametsuchi/impl/temporary_wsv_impl.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.hpp
- irohad/ametsuchi/impl/test_storage_impl.cpp
- irohad/ametsuchi/impl/test_storage_impl.hpp
- irohad/ametsuchi/mutable_storage.hpp
- irohad/ametsuchi/storage.hpp
- irohad/ametsuchi/temporary_wsv.hpp
- irohad/consensus/consensus_common.hpp
- irohad/consensus/yac/storage/impl/yac_block_storage.cpp
- irohad/consensus/yac/storage/impl/yac_common.cpp
- irohad/consensus/yac/storage/yac_common.hpp
- irohad/main/application.cpp
- irohad/model/peer.hpp
- irohad/validation/impl/chain_validator_impl.cpp
- irohad/validation/impl/chain_validator_impl.hpp
- irohad/validation/impl/stateful_validator_impl.cpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/ametsuchi/ametsuchi_test.cpp
- test/module/irohad/ametsuchi/testing_storage_test.cpp
- test/module/irohad/consensus/yac/yac_common_test.cpp
- test/module/irohad/validation/chain_validation_test.cpp
Remove redundant WsvQuery inheritance from Storage, add peer subset validation to chain validator
WsvQuery inheritance introduced redundant code
> Feature/ametsuchi refactoring, chain validator extension

- irohad/model/commands/transfer_asset.hpp
- irohad/model/converters/impl/json_command_factory.cpp
- irohad/model/converters/impl/pb_command_factory.cpp
- irohad/model/converters/pb_command_factory.hpp
- irohad/model/execution/impl/command_executor.cpp
- irohad/model/impl/model_operators.cpp
- schema/commands.proto
- test/module/irohad/ametsuchi/ametsuchi_test.cpp
- test/module/irohad/model/command_validate_execute_test.cpp
- test/module/irohad/model/converters/json_commands_test.cpp
- test/module/irohad/model/converters/pb_commands_test.cpp
- test/module/irohad/model/operators/model_operators_test.cpp
Description field was added to asset transfers.
It is useful to have a description for asset transfers; they can be added by end users and help them to describe what does a transfer mean (like "for Bogdan's birthday" or "rent for house" etc)
Similar to any other fields of TransferAsset objects.
- Add description field to commands.proto
- Add description field to transfer_asset model
- Serializers and deserializers are now aware of description field
- Tests are changed accordingly
> Add description field to asset transfer.

- .circleci/config.yml
Build number [4223](https://circleci.com/gh/hyperledger/iroha/4223) failed because `sonar-pr` was invoked for non-existent PR.
This PR fixes that behaviour.
> [Hotfix] Fix bug with absent PR number at sonar-pr step

- docs/zero.block
Now when genesis block is created, we create admin@test account which does not have necessary permissions to create domains, assets and transactions. This pull request fixes it and grants admin user with all permissions
That stops from creating suitable environment in iroha for testing creating accounts and transferring money among them
After this pull request we are able to create domains, assets and accounts via iroha-cli
> Add permission to genesis block

- test/integration/pipeline/tx_pipeline_integration_test.cpp
Pipeline test was failing in docker since database environment variables were not read in integration test.
> Add missing AmetsuchiTest setup call in pipeline test

- iroha-cli/interactive/impl/interactive_transaction_cli.cpp
Fix bug in cli, which created tx from the old commands
1. i.e we create domain `ru`, then in next tx we want to create asset `dollar#ru`. It ends up with error of trying to run command create domain `ru` once again, because was sent 2nd time because of the bug in cli. This pr fixes this bug. 
2. Also there was a bug of parsing precision values from command line, which have type `uint8_t`. The problem is that it tries to put into `char` type, and then it parsed from `char` to `int`, and as result we get the wrong value. This pr fixes this bug.
Now we can use cli without worrying about aforementioned bugs
To solve issue with parsing `uint8_t` instead we parsed values as `uint32_t`.
> Fix tx creation from old commands, fix uint8 parsing

- iroha-cli/interactive/impl/interactive_transaction_cli.cpp
- irohad/main/application.hpp
- irohad/main/iroha_conf_loader.hpp
- scripts/swarm-deploy.sh
`peer_number` was replaced with `keypair_name` in crypto PR.
> Replace peer number with peer key in swarm deploy script

- cmake/Modules/Findbenchmark.cmake
Fixes benchmarking paths
you can check this out by:
`cmake -DBENCHMARKING=ON && make benchmark_example`
> Quickfix benchmarking target paths

- .circleci/config.yml
- docker/develop/Dockerfile
This pull request:
Sometimes MAC VM on circle ci 2.0 fails during its start. It updates branch state to "Failed". BUT, circle ci restarts VM and all steps are executed. Only after this CircleCI updates PR/branch status to success.
> CI build step for MAC

- cmake/Modules/Findgrpc.cmake
Fix issue with CMake looking for shared GRPC library, while static library is built if it is not found in the system.
> Restore shared library build for GRPC

- irohad/ametsuchi/impl/redis_flat_block_query.cpp
Redis flat file query was returning results only for the first indexed block, since `on_completed` was called in the first invocation of `lrange` callback.
> Fix redis file queries returning result only for the first indexed block

- iroha-cli/interactive/impl/interactive_transaction_cli.cpp
- irohad/ametsuchi/impl/postgres_wsv_command.cpp
- irohad/ametsuchi/impl/postgres_wsv_command.hpp
- irohad/ametsuchi/wsv_command.hpp
- irohad/model/commands/create_role.hpp
- irohad/model/converters/impl/json_command_factory.cpp
- irohad/model/converters/impl/pb_command_factory.cpp
- irohad/model/generators/impl/command_generator.cpp
- irohad/model/permissions.hpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/model/command_validate_execute_test.cpp
- test/module/irohad/model/converters/json_commands_test.cpp
- test/module/irohad/model/converters/pb_commands_test.cpp
Fix for case when order of permissions inside CreateRole command could change after serialization/deserialization.
Order of permissions is not important semantically but it it critical for hash calculation. Hash of Transaction which contains CreateRole command with set of permissions inside should remains the same after serialization/deserialization.
- Use std::map instead of std::unordered map everywhere which guarantees element order
- Add test which checks not only command equality but also their hashes
> Fix of permissions' wrong order

- irohad/ametsuchi/impl/flat_file/flat_file.cpp
- irohad/main/irohad.cpp
- test/module/irohad/ametsuchi/flat_file_test.cpp
Describe simply what this pull request is about.
We had a bug of deleting all blocks but the first one, when iroha initializes from the "hot" state, when ledger has several blocks commited
Describe features, what this pull request resolves, and reasons for this pull request.
This PR fixes aforementioned bug and adds tests to check if block store does not delete blocks when it initializes
Take a look at new test case in flat file test
The problem was with `check_consistency` method, which wrongly removed consistent blocks
> Fix check consistency method

- iroha-cli/interactive/impl/interactive_transaction_cli.cpp
- iroha-cli/interactive/interactive_transaction_cli.hpp
- irohad/model/commands/set_account_detail.hpp
- irohad/model/converters/impl/json_command_factory.cpp
- irohad/model/converters/impl/pb_command_factory.cpp
- irohad/model/converters/json_command_factory.hpp
- irohad/model/converters/pb_command_factory.hpp
- irohad/model/generators/command_generator.hpp
- irohad/model/generators/impl/command_generator.cpp
- irohad/model/impl/model_operators.cpp
- schema/commands.proto
- test/module/irohad/model/converters/json_commands_test.cpp
- test/module/irohad/model/converters/pb_commands_test.cpp
Adds set account detail model with corresponding converters
To add key/value detail about account it is required to have set account detail command. Detail is the key/value data about account
Take a look to new protobuf and json converters tests
> Set account detail model and conversion

- shared_model/interfaces/queries/query.hpp
- shared_model/interfaces/signable.hpp
Pr provides fix for `makeOldModel` method for the Query. Provided `toString` methods for `Signable` and `Query`. Also, provided compare method for `Signable`.
- fix implementation for make old model
- add toString methods
- add total compare method for `Signable`
- the absence of tests, because providing only interfaces
> Fix make old model for query

- irohad/ametsuchi/impl/postgres_wsv_command.cpp
- irohad/ametsuchi/impl/postgres_wsv_query.cpp
- irohad/ametsuchi/impl/storage_impl.hpp
- irohad/model/account.hpp
- irohad/model/commands/create_account.hpp
- irohad/model/execution/impl/command_executor.cpp
- irohad/model/generators/impl/command_generator.cpp
- test/module/irohad/ametsuchi/ametsuchi_test.cpp
- test/module/irohad/ametsuchi/wsv_query_command_test.cpp
Add json data to account and update sql schema 
To allow storage of account personal info we need add JSONb field in account table.
- Add new test in wsv_command_query
- By default account is created with empty JSON data
> Update SQL schema: Add json data to account

- shared_model/cryptography/blob.hpp
- shared_model/cryptography/keypair.hpp
- shared_model/interfaces/model_primitive.hpp
- shared_model/interfaces/primitive.hpp
Rework `Primitive` with `ModelPrimitive` interface, that directly not support converting to the old-fashion interface. Rework with it Blob and Keypair. Add template method Blob::makeOldModel for converting to the old model.
- Rework Primitive
- Add makeOldModel to blob
- Little rework of toSting of ModelPrimitive
> Rework primitive: make modelPrimitive class

- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/redis_block_query.cpp
- test/module/irohad/ametsuchi/CMakeLists.txt
- test/module/irohad/ametsuchi/block_query_test.cpp
- test/module/irohad/ametsuchi/redis_block_query_test.cpp
Describe simply what this pull request is about.
We had bug in PR #655 but did not have test for it. This PR adds test for it
Take a look for the redis_block_query_test
During writing a test another bug was discovered:
when block has `N` txs created by the same account, then every transaction from this block was returned by redis_block_query `N` times. 
Bug was resolved by changing index from `account_id->[list of blocks containing account_id's txs]` to `account_id->{set of blocks containing account_id's txs}`
> Redis block query test

- irohad/model/converters/impl/pb_query_factory.cpp
- test/module/irohad/model/converters/pb_query_factory_test.cpp
Fix issue with lack of query_counter when Query serialization.
- Add set_query_counter method to query serialization process.
> Fix issue with lack of query_counter when Query serialization.

- test/module/shared_model/CMakeLists.txt
- test/module/shared_model/lazy_test.cpp
Remove logger include from lazy_test
To make mac os compilation success
> Remove logger include

- irohad/multi_sig_transactions/storage/impl/mst_storage_impl.cpp
- irohad/multi_sig_transactions/storage/mst_storage_impl.hpp
- test/module/irohad/multi_sig_transactions/mst_processor_test.cpp
- test/module/irohad/multi_sig_transactions/storage_test.cpp
This PR provides the fix of dependencies of MST storage. There is no reason for identification own peer in storage.
This fix was required to integrate MST processor to transaction processor.
> Remove own peer identification from mst_storage;

- cmake/dependencies.cmake
- iroha-cli/CMakeLists.txt
- irohad/model/converters/CMakeLists.txt
- libs/amount/CMakeLists.txt
Add boost CMake target - now it is not required to `target_include_directories` and `target_link_libraries` each time boost is required.
Fix issue with `-Werror -Wpedantic` and boost using `__int128` by including boost directories as system include files.
> Fix boost __int128 pedantic warning, add boost CMake target

- README.md
Adds waffle PR+issues throughput plot to [README.md](https://github.com/hyperledger/iroha/blob/8289825364b35733b887feb8c8b7d50171060d7e/README.md).
It is autoupdated and looks like this:
> PR+issues throughput plot

- shared_model/backend/protobuf/commands/proto_add_asset_quantity.hpp
- shared_model/backend/protobuf/commands/proto_command.hpp
- shared_model/backend/protobuf/common_objects/amount.hpp
- shared_model/cryptography/ed25519_sha3_impl/internal/ed25519_impl.hpp
- shared_model/cryptography/ed25519_sha3_impl/internal/sha3_hash.hpp
- shared_model/cryptography/hash_providers/sha3_512.hpp
- shared_model/interfaces/commands/add_asset_quantity.hpp
- shared_model/interfaces/commands/add_peer.hpp
- shared_model/interfaces/commands/add_signatory.hpp
- shared_model/interfaces/commands/append_role.hpp
- shared_model/interfaces/commands/command.hpp
- shared_model/interfaces/commands/create_account.hpp
- shared_model/interfaces/commands/create_asset.hpp
- shared_model/interfaces/commands/create_domain.hpp
- shared_model/interfaces/commands/create_role.hpp
- shared_model/interfaces/commands/grant_permission.hpp
- shared_model/interfaces/commands/remove_signatory.hpp
- shared_model/interfaces/commands/revoke_permission.hpp
- shared_model/interfaces/commands/set_quorum.hpp
- shared_model/interfaces/commands/transfer_asset.hpp
- shared_model/interfaces/hashable.hpp
This pr provides hashing strategy into `Hashable` class and change requirement of hash with blob.
* Rework hashable with crypto provider strategy
* Remove hash from concrete commands
* Add sha3 hash strategy
* Rework hashable classes
> Add hash strategy for shared_model;

- shared_model/interfaces/polymorphic_wrapper.hpp
- shared_model/utils/variant_deserializer.hpp
- Polymorphic wrapper now can be constructed only from base types or
same type
- Add variant types iteration for deserializer, allowing easier
debugging of missing types from one of deserializers
> Add base class check for poly wrapper ctors; variant deserializer check

- test/framework/test_subscriber.hpp
- test/framework/test_subscriber_testing.cpp
- `EqualToList` inherited of `VerificationStrategy`
- Verifies emitted `rxcpp::observable<T>` equals to `std::vector<T>`
Part of https://github.com/hyperledger/iroha/pull/650
It's useful in block query test.
```cpp
TEST_F(TestSubscriberTesting, ValidEqualToListTest) {
auto ints = rxcpp::observable<>::create<int>([](auto s) {
s.on_next(1);
s.on_next(2);
s.on_completed();
});
auto wrapper = make_test_subscriber<EqualToList>(
ints, std::vector<int>{1, 2});
ASSERT_TRUE(wrapper.subscribe().validate());
}
```
- `EqualToTest` to `VerificationStrategy` in `test/framework/test_subscriber.hpp`
> Add VerificationStrategy EqualToList

- shared_model/backend/protobuf/commands/proto_add_asset_quantity.hpp
- shared_model/backend/protobuf/commands/proto_command.hpp
- shared_model/backend/protobuf/common_objects/amount.hpp
- shared_model/utils/lazy_initializer.hpp
- shared_model/utils/reference_holder.hpp
- shared_model/utils/variant_deserializer.hpp
- test/module/shared_model/backend_proto/CMakeLists.txt
- test/module/shared_model/backend_proto/shared_proto_commands_test.cpp
- Consolidate constructors by using std::forward
- Remove lazy and mapper from reference holder to allow move semantics
- Allow move semantics in variant_deserializer
- Add variants type check in deserializer
- Add sample test for proto model creation
> Fix memory leaks in proto shared model usage

- shared_model/cryptography/crypto_provider/crypto_defaults.hpp
- shared_model/cryptography/crypto_provider/crypto_signer.hpp
- shared_model/cryptography/crypto_provider/crypto_verifier.hpp
- shared_model/cryptography/ed25519_sha3_impl/CMakeLists.txt
- shared_model/cryptography/ed25519_sha3_impl/crypto_provider.cpp
- shared_model/cryptography/ed25519_sha3_impl/crypto_provider.hpp
- shared_model/cryptography/ed25519_sha3_impl/signer.cpp
- shared_model/cryptography/ed25519_sha3_impl/signer.hpp
- shared_model/cryptography/ed25519_sha3_impl/verifier.cpp
- shared_model/cryptography/ed25519_sha3_impl/verifier.hpp
- shared_model/cryptography/keypair.hpp
- shared_model/cryptography/seed.hpp
- shared_model/interfaces/hashable.hpp
- test/module/shared_model/CMakeLists.txt
- test/module/shared_model/crypto_usage_test.cpp
Now possible to use cryptography without explicit configuration of algorithm;
This PR provides separation of `crypto_provider` with `Signer` and `Verifier`. And make default algorithm specialization of it.
Additional changes:
* Rework hashable documentation
* Fix warnings in seed and keypair files
* Reworked crypto providers with static context
* Fix CMake dependencies
* Add usage tests
> Add generification of crypto provider;

- shared_model/interfaces/polymorphic_wrapper.hpp
- shared_model/utils/variant_deserializer.hpp
Remove constructor which uses `make_shared` since `T` can be abstract.
> Remove emplace constructor from polymorphic wrapper

- irohad/torii/impl/query_service.cpp
- schema/responses.proto
- test/module/irohad/torii/torii_queries_test.cpp
Pull request adds hash field to QueryResponse proto object.
According our model QueryResponse always contains a hash of a corresponding query but it was not reflected in proto scheme.
- Add hash field in QueryResponse proto
- Hash field is set in QueryService
- Tests know about hash field and check it
Since every QueryResponse hash should be the same as hash of corresponding query I decided not to create additional test for hash but add checks for every existing test similar to status call checking.
> Add hash field to QueryResponse proto object

- shared_model/builders/protobuf/queries.hpp
- test/module/shared_model/backend_proto/shared_proto_queries_test.cpp
This basically fix to consistent builder that returns `shared_model::proto` rather than `iroha::protocol` query
> Update query builder

- shared_model/builders/protobuf/transaction.hpp
- shared_model/interfaces/polymorphic_wrapper.hpp
- shared_model/interfaces/queries/get_roles.hpp
- shared_model/validators/CMakeLists.txt
- shared_model/validators/answer.hpp
- shared_model/validators/commands_validator.hpp
- shared_model/validators/default_validator.cpp
- shared_model/validators/default_validator.hpp
- test/module/shared_model/backend_proto/CMakeLists.txt
- test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp
This PR integrates stateless validation check into transaction builder
We need to have mechanism for performing stateless validation check. It should be integrated in transaction builder and be easily substituted.
Adds new SV template parameter into ProtoTransactionBuilder
Adds implementation of CommandValidator, which checks all tx commands on whether they have properly added fields
> Transaction stateless validation in shared model

- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/backend/protobuf/transaction.hpp
- shared_model/builders/protobuf/unsigned_proto.hpp
- shared_model/interfaces/base/signable.hpp
- test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp
Fix about using payload of Transaction and Query when signing instead of whole blob.
Whole blob may contain other signatures which should not be signed. Also it creates a problem on verification step.
- Add payload() abstract method into Signable
- Implement payload() in both Transaction and Query
- Use payload() call when signing instead of blob()
- Fix test according to changes above
> Fix problem with proto object signing:

- .circleci/config.yml
This PR adds `trunk/.*` branches to sonar-release build, which means that all trunks will be persisted as separate projects on sonar.
> Add trunks to sonar-release step

- shared_model/bindings/bindings.i
Exceptions rethrow from Swig to native languages
C++ exceptions are hard to catch from other languages (if even possible).
From Python:
```
import iroha
builder = iroha.ModelBuilder()
crypto = iroha.ModelCrypto()
me_kp = crypto.generateKeypair()
peer_kp = crypto.generateKeypair()
signatory_kp = crypto.generateKeypair()
account_kp = crypto.generateKeypair()
time = 1513049580000
startCounter = 1
creator = "me@iroha"
signatory = "fyodor@iroha"
commands = []
commands.append(builder.txCounter(startCounter).creatorAccountId(creator).createdTime(time).addPeer("127.0.0.256", peer_kp.publicKey()).build())
protoHelper = iroha.ModelTransactionProto()
for command in commands:
print(protoHelper.signAndAddSignature(command, me_kp).toString())
```
This snippet will result in next exception thrown:
``` …
```
> Rethrow build exceptions to target language exceptions.

- shared_model/cryptography/ed25519_sha3_impl/internal/sha3_hash.cpp
- shared_model/cryptography/ed25519_sha3_impl/internal/sha3_hash.hpp
Small refactoring of sha3_hash, which removes some code duplication, and adds const where needed
- Add const specifier to input parameter in hash functions
- Remove sha3 namespace in favor of namespace resolution operator "::"
> Add const specifier and remove duplication

- shared_model/validators/commands_validator.hpp
- test/module/shared_model/validators/commands_validator_test.cpp
Fix for empty transaction validation
Transaction without commands are not allowed
Test included
- Add validation step for zero commands in transaction case
- Add test for empty transaction validation
> Fix transaction validation for empty commands

- shared_model/interfaces/iroha_internal/block.hpp
Remove merkle root field from shared model of block
At the moment, merkle root is not needed for a block since we store transactions directly inside the block.
Initially intended merkle root  usage for chain validation is not useful, because it does not provide any benefits to performance or additional features.
- Remove merkleRoot() from block.hpp
- Remove setting of merkle_root in makeOldModel()
- Remove merkle root from toString()
> Remove merkle root from block

- shared_model/bindings/model_builder.cpp
- shared_model/builders/protobuf/transaction.hpp
- shared_model/builders/protobuf/unsigned_proto.hpp
- shared_model/validators/commands_validator.hpp
- test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp
This PR provides a constant interface for transaction builder.
* make all generation methods of builder constant
* fix bug (silently) when on setter copy default stateless validator
* fix interface of stateless validator as a constant
> Make transaction builder const

- irohad/model/operators/hash.hpp
- irohad/multi_sig_transactions/state/mst_state.hpp
- libs/common/types.hpp
- test/module/irohad/multi_sig_transactions/transport_test.cpp
Fix test passing for mac os platform
The different behavior of `std::hash` with respect to binary data in Linux and Mac OS environments.  Also, fix semantic of transaction equality for MST.
* rework operator== with hash semantic for transactions
* rework hashing of transactions with hex strings
* cleanup transport test
> Fix tests for mac os;

- test/integration/pipeline/transfer_asset_inter_domain_test.cpp
- test/integration/pipeline/tx_pipeline_integration_test.cpp
- test/integration/pipeline/tx_pipeline_integration_test_fixture.hpp
Fix sending transactions in integration test to be able to guarantee the order of transactions.
To solve the issue of sending multiple transactions in the test.
Being lack this fix, the test of https://github.com/hyperledger/iroha/pull/692 sometimes fails because of sending multiple transactions. 
```cpp
sendTxsInOrderAndValidate({tx1, tx2, tx3});
```
- Remove useless debug.
- Use condition variable to wait previous txs are sent.
- One transaction in one block.
- Remove the feature of sending multiple transactions which are independent each other inside one block because it is not used.
> Use condition variable to wait until previous tx sent

- shared_model/backend/protobuf/commands/proto_command.hpp
- shared_model/backend/protobuf/common_objects/account.hpp
- shared_model/backend/protobuf/common_objects/account_asset.hpp
- shared_model/backend/protobuf/common_objects/amount.hpp
- shared_model/backend/protobuf/common_objects/asset.hpp
- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/backend/protobuf/transaction.hpp
- shared_model/backend/protobuf/util.hpp
- shared_model/bindings/bindings.i
- shared_model/builders/protobuf/transaction.hpp
- shared_model/builders/protobuf/unsigned_proto.hpp
- shared_model/cryptography/blob.hpp
- shared_model/cryptography/ed25519_sha3_impl/internal/sha3_hash.cpp
- shared_model/cryptography/ed25519_sha3_impl/internal/sha3_hash.hpp
- shared_model/cryptography/ed25519_sha3_impl/signer.cpp
- shared_model/cryptography/ed25519_sha3_impl/verifier.cpp
- shared_model/cryptography/public_key.hpp
- shared_model/interfaces/transaction_responses/tx_response.hpp
- shared_model/utils/polymorphic_wrapper.hpp
- test/module/shared_model/backend_proto/CMakeLists.txt
- test/module/shared_model/backend_proto/shared_proto_queries_test.cpp
- test/module/shared_model/backend_proto/shared_proto_transaction_test.cpp
- test/module/shared_model/backend_proto/shared_proto_util_test.cpp
- test/module/shared_model/cryptography/blob_test.cpp
- test/module/shared_model/validators/commands_validator_test.cpp
This pr is changes the iterface of `Blob::blob()` from `std::string` to `std::vector<uint8_t>`
There're issues with the swig string conversions, binary data is basically converted incorrectly
Also note, that this way is more or less bad in terms of efficiency (there's can be redundant copies in debug builds). I think it should be optimized: all binary data should be stored in the `std::vector<uint8_t>`. But that requires significant amount of work, so maybe there's some better approaches
> Return vector in Blob::blob()

- .circleci/config.yml
- cmake/Modules/Findcpp_redis.cmake
- docker/develop/Dockerfile
Mac's CI fails to build redis due to the include dir absence
This also set tacopie as the submodule
> Fixing redis dependency

- shared_model/cryptography/ed25519_sha3_impl/signer.cpp
- shared_model/cryptography/ed25519_sha3_impl/verifier.cpp
Signing and verifying objects with preliminary hashing.
Old model uses hashing while new one does not. We should do the same approach in both.
```
import iroha
import time
import block_pb2
import endpoint_pb2_grpc
import grpc
txbuilder = iroha.ModelTransactionBuilder()
queryBuilder = iroha.ModelQueryBuilder()
crypto = iroha.ModelCrypto()
protoTxHelper = iroha.ModelProtoTransaction()
protoQueryHelper = iroha.ModelProtoQuery()
me_kp = crypto.convertFromExisting("227a458045f8d7d520907fb400461ae3c9101a68af2851d56a85b96fd791911a", "1011098aebf697597a59151a0ba1bb34bcf081f5195fa8de551b9a2b52be864613aae9771f35df7318e0d7b8571f043cd54581a0b1c5cf36fb05ac8956d291fe")
print(me_kp.publicKey().hex())
peer_kp = crypto.generateKeypair()
signatory_kp = crypto.generateKeypair()
account_kp = …
```
> Sign everything with preliminary hashing

- cmake/Modules/Finded25519.cmake
Ed25519 library is statically linked.
I've got a problem with new crypto library (I hope somebody else could also check it). Scenario is pretty simple:
1. Checkout actual develop branch.
2. Do clean.sh to ensure everything was cleaned.
3. Run cmake && make
This sequence gives me a stable problem when I try to run tests (or irohad, doesn't matter):
```
➜  build git:(develop) ctest
Test project /Users/konstantinmunichev/src/iroha/build
Start  1: blob_converter_test
1/77 Test  #1: blob_converter_test ....................   Passed    0.01 sec
Start  2: block_insertion_test
2/77 Test  #2: block_insertion_test ...................***Exception: Child aborted  0.01 sec
Start  3: ametsuchi_test
3/77 Test  #3: ametsuchi_test .........................***Exception: Child aborted  0.00 sec
.....
18% …
```
> Use static linking for ed25519 library

- shared_model/backend/protobuf/queries/proto_query.hpp
- test/module/shared_model/bindings/CMakeLists.txt
- test/module/shared_model/bindings/model_query_builder_test.cpp
Calling build on empty simple query builder resulted in segmentation fault due to access to null pointer. This PR adds handling of such case by throwing an exception if query payload is not set.
> Add handling of empty query to load_query

- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/bindings/model_query_builder.cpp
- shared_model/bindings/model_query_builder.hpp
- shared_model/bindings/model_transaction_builder.cpp
- shared_model/bindings/model_transaction_builder.hpp
- shared_model/validators/field_validator.hpp
- shared_model/validators/query_validator.hpp
- shared_model/validators/transaction_validator.hpp
- test/module/shared_model/validators/query_validator_test.cpp
- test/module/shared_model/validators/validators_fixture.hpp
It solves problem when bindings users can forget to set one ore more mandatory fields for queries and transactions (like tx_counter) and still pass validation.
- Add validator for query and tx counters
- Set mandatory fields for query and tx to invalid values
- Fix bug in load_query
> Improve bindings interface

- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.cpp
- irohad/model/execution/command_executor.hpp
- irohad/model/execution/impl/command_executor.cpp
- test/module/irohad/ametsuchi/kv_storage_test.cpp
- test/module/irohad/model/command_validate_execute_test.cpp
Fix for grant permissions, set_account_detail by adding creator to mutable storage and execute function. 
Creator is not passing during chain_validation thus resulting in an append error. 
- Refactor execute, isValid
- Refactor tests
- Add creator to mutable storage
> Refactor command execution:

- test/integration/pipeline/tx_pipeline_integration_test.cpp
- test/module/irohad/api/connection/command_connection_test.cpp
- test/module/irohad/consensus/yac/network_test.cpp
- test/module/irohad/network/block_loader_test.cpp
- test/module/irohad/ordering/ordering_gate_service_test.cpp
- test/module/irohad/ordering/ordering_gate_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
This pull request removes hardcoded ports from several test classes, and replaces them with dynamic port selection
Hardcoded ports can be already taken by something else, which produces test failure. Such a failure is hard to detect and reproduce, so it is best to avoid such issues.
- Add dynamic ports to block_loader_test and ordering_gate_test
I was not able to change several tests, because address needs to be known beforehand for them to work. This means that adding dynamic port requires major changes in core classes.
> Add dynamic port selection to several tests

- cmake/Modules/Findpq.cmake
- cmake/Modules/Findpqxx.cmake
- cmake/Modules/Findtbb.cmake
`make -j<n>` leads to:
```
[ 28%] Performing build step for 'jtv_libpqxx'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
So this fix basically replaces `make` with with `$(MAKE)` in __cmake/Modules/Find*.cmake__ files according to [this discussion](http://cmake.3232098.n2.nabble.com/How-would-I-use-parallel-make-on-ExternalProjects-td5609078.html)
> Replace make with $(MAKE) in cmake

- cmake/Modules/Findpq.cmake
Add additional subdirectory search for find_path in Findpq.cmake
Enables usage of libpq-dev installed by apt in Ubuntu.
None.
> Fix find_path for libpq on Ubuntu

- irohad/ametsuchi/impl/flat_file/flat_file.cpp
- irohad/ametsuchi/impl/flat_file/flat_file.hpp
- irohad/ametsuchi/impl/redis_block_query.cpp
- test/framework/test_subscriber.hpp
- test/module/irohad/ametsuchi/block_query_test.cpp
- test/module/irohad/ametsuchi/flat_file_test.cpp
Bugfixes, increase coverage
None.
> Cover Redis BlockQuery with tests

- irohad/main/server_runner.cpp
- irohad/network/grpc_call.hpp
- irohad/torii/torii_service_handler.cpp
- irohad/torii/torii_service_handler.hpp
This pull request fixes memory leaks in torii_service_test, torii_queries_test and client_test.
Well, leaks are bad ;)
Probably none (I hope)
Build project with ```-fsanitize=address``` and run tests as ```ASAN_OPTIONS=detect_leaks=1 ctest```:
```
90% tests passed, 8 tests failed out of 78
Total Test time (real) =  39.61 sec
The following tests FAILED:
3 - ametsuchi_test (Child aborted)
4 - wsv_query_command_test (Failed)
15 - yac_timer_test (Child aborted)
47 - ordering_service_test (Child aborted)
49 - ordering_gate_service_test (Child aborted)
73 - field_validator_test (Failed)
77 - tx_pipeline_integration_test (Child aborted)
78 - transfer_asset_inter_domain_test (Child aborted)
```
Without current fix 11 tests will fail.
Please note change …
> Fix memory leak related to Torii

- test/framework/CMakeLists.txt
- test/framework/integration_framework/iroha_instance.hpp
- test/integration/pipeline/test_irohad.hpp
- test/integration/pipeline/tx_pipeline_integration_test_fixture.hpp
Move TestIrohad out of tx_pipeline_integration_test_fixture.hpp enables get rid of gtest dependency.
No gtest dependency in ITF
Please check the PR is correct.
not needed
no
> ITF remove gtest dependency

- shared_model/backend/protobuf/commands/proto_command.hpp
- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/backend/protobuf/transaction_responses/proto_tx_response.hpp
There's a name collision for load functions, that pr fixes it
> Fix load name collision

- docker/develop/Dockerfile
- docker/docker-compose.yml
- scripts/run-iroha-dev.sh
- test/module/irohad/ametsuchi/flat_file_test.cpp
- test/module/libs/crypto/keys_manager_test.cpp
Signed-off-by: dumitru <dimasavva17@gmail.com>
UPD: @warchant
> Docker-related quickfixes for develop

- shared_model/backend/protobuf/block.hpp
- shared_model/builders/protobuf/block.hpp
- shared_model/interfaces/common_objects/signature.hpp
- shared_model/interfaces/iroha_internal/block.hpp
Fixes for shared_model classes:
- Add missed includes
- Fix leaks and captures in block's `makeOldModel`
- Fix binary string conversion in block's & signature's `makeOldModel`
- Removed signatures from block's builder (as long as we sign builded object)
- Use placement new for adding txes in block (otherwise weird compile errors)
Lesser compile errors 
Hopefully none
> Fixes for shared_model classes (Block/Signature)

- irohad/model/permissions.hpp
- test/module/irohad/model/command_validate_execute_test.cpp
- test/module/irohad/model/converters/json_commands_test.cpp
As @motxx noticed here's the shared_model permission converting:
https://github.com/hyperledger/iroha/blob/4e58f7780b8c918e56328231ec8f5a9fd67bb429/shared_model/builders/protobuf/transaction.hpp#L211-L215
That's pr updates old model permission string names, so it may work with the shared_model as well.
?
As an additional way of fixing that is converting permissions and leaving the old model as is. Imo that not really good because it requires update such strings in multiple places.
> Conform old model perms with the shared_model

- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/mutable_storage_impl.hpp
- irohad/ametsuchi/impl/temporary_wsv_impl.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.hpp
- irohad/model/CMakeLists.txt
- irohad/model/execution/command_executor.hpp
- irohad/model/execution/execution_error.hpp
- irohad/model/execution/impl/command_executor.cpp
- libs/common/result.hpp
- test/module/irohad/model/command_validate_execute_test.cpp
This pull request modifies execute() method in command_executor, to return Result instead of bool. This means, that if for some reason, execution of the command has failed, a caller of the executor will know the reason why. This allows for better informativeness of error messages.
1. Command executor now returns meaningful error message
2. Returned error contains command name
1. Validate still returns bool, so it is impossible to know if the database has failed during validation.
2. Because database operations still return boolean, or optional, a lot of code needs to be added to transform it into the result, in the future, it will be simplified.
Mutable storage and temporary wsv both output error message from command_executor into the log. This is the simplest use, and they can return a …
> Command Executor returns error message on execute()

- cmake/Modules/Finded25519.cmake
- docker/develop/Dockerfile
warchant/ed25519 repository has been successfully transferred to hyperledger/iroha-ed25519, this PR updates version in all scripts.
> Update ed25519 version after repository transfer

- irohad/multi_sig_transactions/storage/impl/mst_storage.cpp
- irohad/torii/impl/command_service.cpp
- test/integration/pipeline/CMakeLists.txt
- test/integration/pipeline/multisig_tx_pipeline_test.cpp
Test for multisignature module. It has checking that the tx comes to the commit after all signers sign it 
`make multisig_tx_pipeline_test && test_bin/multisig_tx_pipeline_test`
There's issue with the command_service: it caches the same txes, so I add a pass for mst txes, that may be not really good idea.
This will going to be reworked with new ITF, look at the [`feature/mst-integration`](https://github.com/hyperledger/iroha/tree/feature/mst-integration) if you're interested
> Add multisig integration test

- cmake/Modules/Findspdlog.cmake
- docker/develop/Dockerfile
Signed-off-by: satellitex <s.a.t.e.3.ths@gmail.com>
An error occurred while building shared_model using alpine.
```
In file included from /opt/iroha/external/src/gabime_spdlog/include/spdlog/details/log_msg.h:9:0,
from /opt/iroha/external/src/gabime_spdlog/include/spdlog/sinks/sink.h:9,
from /opt/iroha/external/src/gabime_spdlog/include/spdlog/sinks/base_sink.h:13,
from /opt/iroha/external/src/gabime_spdlog/include/spdlog/logger.h:15,
from /opt/iroha/external/src/gabime_spdlog/include/spdlog/spdlog.h:14,
from /opt/iroha/libs/logger/logger.hpp:21,
from /opt/iroha/libs/logger/logger.cpp:17:
/opt/iroha/external/src/gabime_spdlog/include/spdlog/details/os.h: In function 'std::__cxx11::string spdlog::details::os::errno_str(int)':
/opt/iroha/external/src/gabime_spdlog/include/spdlog/details/os.h …
```
> update spdlog commit version for alpine

- irohad/model/impl/model_operators.cpp
- irohad/model/proposal.hpp
- irohad/ordering/impl/ordering_gate_transport_grpc.cpp
- irohad/ordering/impl/ordering_service_impl.cpp
- irohad/ordering/impl/ordering_service_transport_grpc.cpp
- irohad/simulator/impl/simulator.cpp
- irohad/validation/impl/stateful_validator_impl.cpp
- shared_model/backend/protobuf/from_old_model.hpp
Add missing field `created_time` at the `model::Proposal`, also initializing that field where it possible, fixes ir-501 todo
Can be a problem with block initialization here:
https://github.com/hyperledger/iroha/blob/92d329b3ec88ed7ebe6310fd9c34313c3d09bd18/irohad/simulator/impl/simulator.cpp#L74
Imo it's better use time::now() instead and remove the timestamp field from proposal completely
> Add created_time in model::Proposal

- irohad/main/application.cpp
- irohad/torii/command_client.cpp
- irohad/torii/command_client.hpp
- irohad/torii/command_service.hpp
- irohad/torii/impl/command_service.cpp
- test/integration/client_test.cpp
- test/integration/pipeline/tx_pipeline_integration_test_fixture.hpp
- test/module/irohad/torii/query_service_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
Streaming grpc call for transaction statuses.
We want to have a push-based notifications for tx statuses so here we are.
Each streaming call can theoretically block one of grpc thread up to a second. This timeout can be decreased in a least 10 times but it allows to start streaming call before transaction sending.
Two tests were added to torii_service_test.
Two main possibilities were checked: use combined Torii request which will return stream of responses or use separate calls for that (the second one was actually implemented). The first approach was faced with thread-related difficulties (kick me and I explain details).
> Torii streaming

- shared_model/backend/protobuf/query_responses/proto_concrete_error_query_response.hpp
- shared_model/backend/protobuf/query_responses/proto_error_query_response.hpp
- shared_model/interfaces/query_responses/error_query_response.hpp
- shared_model/interfaces/query_responses/error_responses/no_account_detail_error_response.hpp
- test/integration/pipeline/tx_pipeline_integration_test.cpp
- test/module/shared_model/backend_proto/shared_proto_query_responses_test.cpp
Signed-off-by: Andrei Lebedev <lebdron@gmail.com>
Fix error query response deserialization - wrong protobuf methods were previously used.
Add missing error query reason - no account detail reason was not present in shared model.
Integration test framework `sendQuery(const Query &, Lambda)` works as expected.
None.
https://github.com/hyperledger/iroha/blob/aca94010a0a1d31eb9a65bb558423f5cb4115925/test/module/shared_model/backend_proto/shared_proto_query_responses_test.cpp#L54-L80
> Fix error query response deserialization, add missing query error resp

- irohad/network/ordering_service.hpp
- irohad/network/ordering_service_transport.hpp
- irohad/ordering/impl/ordering_gate_transport_grpc.cpp
- irohad/ordering/impl/ordering_service_impl.cpp
- irohad/ordering/impl/ordering_service_impl.hpp
- irohad/ordering/impl/ordering_service_transport_grpc.cpp
- irohad/ordering/impl/ordering_service_transport_grpc.hpp
- test/module/irohad/ordering/CMakeLists.txt
- test/module/irohad/ordering/ordering_service_test.cpp
Change OrderingServices' interfaces to the new shared model
There's some issues that've been solved as simple as possible, though it's probably not really a good solution
There's need to convert `proto::Proposal` to `protocol::Proposal`, it's pretty easy to set all the fields via builder but transactions. SM's proposal returns an interface, so there's no simple way to convert to protobuf, so I just use `makeOldModel` + `from_old`:
https://github.com/hyperledger/iroha/blob/5b711d1d7348f853ab8cda74e4b5b87207a24198/irohad/ordering/impl/ordering_service_transport_grpc.cpp#L61-L71
I guess the example is self-explainable
https://github.com/hyperledger/iroha/blob/5b711d1d7348f853ab8cda74e4b5b87207a24198/test/module/irohad/ordering/ordering_service_test.cpp#L82-L89
The tbb's concurrent queue …
> Rework OrderingService with new model

- shared_model/utils/variant_deserializer.hpp
Because function returns `template V` (some object) and does not return anything, it caused warning, which in turn, with -Werror resulted in compilation error.
UPD: when you use BOOST_ASSERT in such function, and program is compiled with -DNDEBUG (any release mode), it actually disables BOOST_ASSERT and warning `-Wreturn-type` appears.
> Fix -Wreturn-type

- .circleci/config.yml
Move "save_cache" step in the end of "build" step.
When tests could potentially fail you typically push commit and wait until tests will succeed in CI. 
When save_cache is in the end, test step and analysis steps are executed earlier, so you, as a developer, can save 2-3 min.
> Move cache step to the end

- irohad/main/application.cpp
- irohad/main/application.hpp
- irohad/model/converters/impl/pb_query_response_factory.cpp
- irohad/model/impl/query_execution.cpp
- irohad/torii/command_service.hpp
- irohad/torii/impl/command_service.cpp
- irohad/torii/impl/query_service.cpp
- irohad/torii/processor/impl/query_processor_impl.cpp
- irohad/torii/processor/impl/transaction_processor_impl.cpp
- irohad/torii/processor/query_processor.hpp
- irohad/torii/processor/query_processor_impl.hpp
- irohad/torii/processor/transaction_processor_impl.hpp
- irohad/torii/query_service.hpp
- shared_model/backend/protobuf/from_old_model.hpp
- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/backend/protobuf/query_responses/proto_query_response.hpp
- test/integration/client_test.cpp
- test/module/irohad/torii/processor/CMakeLists.txt
- test/module/irohad/torii/processor/query_processor_test.cpp
- test/module/irohad/torii/processor/transaction_processor_test.cpp
- test/module/irohad/torii/query_service_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
Removed stateless validation from query processor and transaction processor
Updates query service to use new model
Now stateless validation happens in query service
Big parts of code were affected
Old tests were updated and now demonstrate use of new model in query service
> Query service update to sh-m

- CMakeLists.txt
Signed-off-by: Andrei Lebedev <lebdron@gmail.com>
As it was pointed out in https://github.com/hyperledger/iroha/pull/983 , `-g` flag increases binary size, which leads to CircleCI container running out of memory. This pull request removes `-g` flag from coverage builds, allowing CircleCI to pass compilation.
CircleCI does not crash with memory error
Debugging (for example with gdb) in coverage build is probably not possible due to missing debug information
> Remove -g flag if coverage is enabled to reduce binary size

- test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
Clean postgres in ametsuchi test in SetUp step, right after connection.
When test dies with SIGSEGV or other error, TearDown is not executed and postgres remains tables and rows, which lead to double insertion of the same primary key (peer id and others).
This PR fixes this.
Example:
```
Start 95: transfer_asset_inter_domain_test
95/95 Test #95: transfer_asset_inter_domain_test .......***Exception: SegFault  5.05 sec
Running main() from gtest_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TransferAssetInterDomainTest
[ RUN      ] TransferAssetInterDomainTest.TransferAssetInterDomainTest
[2018-02-24 09:50:54.746092543][th:3866][info] IROHAD created
[2018-02-24 09:50:54.746217649][th:3866][info] …
```
> Clean postgres in ametsuchi test in SetUp

- cmake/Modules/Findbenchmark.cmake
- cmake/Modules/Finded25519.cmake
- cmake/Modules/Findgflags.cmake
- cmake/Modules/Findgrpc.cmake
- cmake/Modules/Findgtest.cmake
- cmake/Modules/Findoptional.cmake
- cmake/Modules/Findpq.cmake
- cmake/Modules/Findpqxx.cmake
- cmake/Modules/Findprotobuf.cmake
- cmake/Modules/Findrapidjson.cmake
- cmake/Modules/Findrxcpp.cmake
- cmake/Modules/Findspdlog.cmake
- cmake/Modules/Findtbb.cmake
- cmake/dependencies.cmake
- cmake/functions.cmake
Pass to dependencies:
- compiler generator
- launcher C, CXX (for ccache)
- add gpr lib to packaging, it is used by `grpc`
- remove grpc++_reflection from packaging -- we do not use it.
Change library output path to ${CMAKE_BUILD_DIR} -- means that all external libs will be compiled in `build` directory so we do not need to write full path to these libs.
Fix identations.
**Note**: `iroha_get_lib_name` only does preformatting of library name.
```
Example:
iroha_get_lib_name(OUT iroha SHARED) -> OUT=libiroha.so
iroha_get_lib_name(OUT iroha STATIC) -> OUT=libiroha.a
```
This PR is split part of https://github.com/hyperledger/iroha/pull/983
> Pass compiler generator and launchers to dependencies

- cmake/Modules/Findbenchmark.cmake
- cmake/Modules/Finded25519.cmake
- cmake/Modules/Findgflags.cmake
- cmake/Modules/Findgrpc.cmake
- cmake/Modules/Findgtest.cmake
- cmake/Modules/Findoptional.cmake
- cmake/Modules/Findpq.cmake
- cmake/Modules/Findpqxx.cmake
- cmake/Modules/Findprotobuf.cmake
- cmake/Modules/Findrapidjson.cmake
- cmake/Modules/Findrxcpp.cmake
- cmake/Modules/Findspdlog.cmake
- cmake/Modules/Findtbb.cmake
- cmake/dependencies.cmake
- cmake/functions.cmake
.deb package build process is broken, since Circle CI is using shared library.
> Revert "Pass compiler generator and launchers to dependencies"

- irohad/network/impl/peer_communication_service_impl.cpp
- irohad/network/ordering_gate.hpp
- irohad/network/ordering_gate_transport.hpp
- irohad/ordering/impl/ordering_gate_impl.cpp
- irohad/ordering/impl/ordering_gate_impl.hpp
- irohad/ordering/impl/ordering_gate_transport_grpc.cpp
- irohad/ordering/impl/ordering_gate_transport_grpc.hpp
- test/module/irohad/network/network_mocks.hpp
- test/module/irohad/ordering/ordering_gate_service_test.cpp
- test/module/irohad/ordering/ordering_gate_test.cpp
Fix of naming notation for ordering gate
Code cleanup.
> Fix naming for propagateTransaction in ordering gate

- irohad/network/block_loader.hpp
- irohad/network/impl/block_loader_impl.cpp
- irohad/network/impl/block_loader_impl.hpp
- shared_model/backend/protobuf/block.hpp
- shared_model/backend/protobuf/commands/proto_command.hpp
- shared_model/backend/protobuf/common_objects/account.hpp
- shared_model/backend/protobuf/common_objects/account_asset.hpp
- shared_model/backend/protobuf/common_objects/amount.hpp
- shared_model/backend/protobuf/common_objects/asset.hpp
- shared_model/backend/protobuf/proposal.hpp
- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/backend/protobuf/query_responses/proto_query_response.hpp
- shared_model/backend/protobuf/transaction.hpp
- shared_model/backend/protobuf/transaction_responses/proto_tx_response.hpp
- shared_model/builders/protobuf/builder_templates/query_template.hpp
- shared_model/cryptography/hash_providers/sha3_256.hpp
- shared_model/interfaces/base/hashable.hpp
- shared_model/interfaces/base/signable.hpp
- shared_model/interfaces/common_objects/types.hpp
- shared_model/interfaces/iroha_internal/block.hpp
- shared_model/interfaces/queries/get_transactions.hpp
- shared_model/interfaces/query_responses/query_response.hpp
- shared_model/interfaces/transaction_responses/tx_response.hpp
- test/module/irohad/network/network_mocks.hpp
Move `HashType` and `BlobType` from `Hashable` to `common_objects/types.hpp`.
Because Hashable is a template, you need weird constructions like https://github.com/hyperledger/iroha/pull/1022/files#diff-f5da1abc9499e5ab936bf6172f85dbb6L71 to actually access the type. Also, what if you want to access this type from some other type, which does not have Hashable as its base class? You simply can't.
Now you can just include header and use it.
None.
> Move HashType and BlobType out of Hashable

- irohad/model/converters/impl/pb_command_factory.cpp
- schema/primitive.proto
Fix strings for protobuf can_grant_ permissions and old model strings.
Now it is possible to convert from new to old and vice versa.
no
> fix names of grant permissions in protobuf and old model

- irohad/torii/impl/query_service.cpp
- irohad/torii/query_service.hpp
- test/module/irohad/torii/query_service_test.cpp
QueryService performs redundant operations. Particularly, the following part of the code contained problems:
https://github.com/hyperledger/iroha/blob/def7bc4f7efdf0c2d1c3caecccd2cf3efe0c889e/irohad/torii/impl/query_service.cpp#L53-L77
1. Here on line 60 response's status is set to `STATELESS_INVALID` but this status is not put into cache, whereas response variable is overwritten on line 74 by previous response for the same query hash.
2. On line 64 empty response was put into cache.
3. On line 73 value of optional is taken without checking its existence
4. No tests reflected aforementioned issues
All problems above were fixed.
Now if after query is passed into `QueryProcessor::queryHandle` method, but afterwards corresponding query response is …
> Update query service

- irohad/main/application.cpp
- irohad/network/impl/peer_communication_service_impl.cpp
- irohad/network/impl/peer_communication_service_impl.hpp
- irohad/network/ordering_gate.hpp
- irohad/network/peer_communication_service.hpp
- irohad/ordering/impl/ordering_gate_impl.cpp
- irohad/ordering/impl/ordering_gate_impl.hpp
- test/module/irohad/network/network_mocks.hpp
- test/module/irohad/ordering/ordering_gate_service_test.cpp
- test/module/irohad/ordering/ordering_gate_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
Add concurrent queue to the Ordering Gate.
Fix design bug in PeerCommunicationService: add const modifier for `on_proposal` and `on_commit`.
Solve back pressure issue from OS.
Increase test complexity where used Ordering Gate
> Queue in ordering gate

- irohad/ordering/impl/ordering_service_impl.cpp
- test/framework/integration_framework/integration_test_framework.hpp
Remove Proposal builder from OS method to avoid redundant copies
Fix destructor order in ITF - queues were destroyed before iroha instance, and iroha instance was writing proposals to nonexistent queues
Proposal generation time with 1000 transactions
Before: Elapsed time for generateProposal: 3165786mus
After: Elapsed time for generateProposal: 6114mus
Raw protobuf objects usage in implementation
> Remove proposal builder from OS; fix ITF destructor

- irohad/ametsuchi/impl/postgres_wsv_query.cpp
- irohad/ametsuchi/impl/postgres_wsv_query.hpp
- irohad/ametsuchi/wsv_query.hpp
- irohad/model/converters/impl/json_query_factory.cpp
- irohad/model/converters/impl/pb_query_factory.cpp
- irohad/model/generators/impl/query_generator.cpp
- irohad/model/generators/query_generator.hpp
- irohad/model/impl/query_execution.cpp
- irohad/model/queries/get_account_detail.hpp
- schema/queries.proto
- shared_model/backend/protobuf/queries/proto_get_account_detail.hpp
- shared_model/bindings/model_query_builder.cpp
- shared_model/bindings/model_query_builder.hpp
- shared_model/builders/protobuf/builder_templates/query_template.hpp
- shared_model/interfaces/queries/get_account_detail.hpp
- shared_model/validators/query_validator.hpp
- test/integration/client_test.cpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/ametsuchi/kv_storage_test.cpp
- test/module/irohad/ametsuchi/wsv_query_command_test.cpp
- test/module/irohad/model/converters/json_query_factory_test.cpp
- test/module/irohad/model/converters/pb_query_factory_test.cpp
- test/module/shared_model/bindings/QueryTest.java
- test/module/shared_model/bindings/query-test.py
At the moment getAccountDetail query unable to request details added by users different from query creator. This pull request changes behaviour of getAccountDetail - now it returns all account details (in JSON format).
Possibility to request detail data added from other accounts. Also retrieving a whole details JSON in a single request could be more convenient to clients than to do a request for every key.
Behaviour of query was changed so old code which uses getAccountDetail becomes broken.
Check kv_storage_test. Also simple example for Java:
In genesis block:
```
{
"command_type": "SetAccountDetail",
"account_id": "admin@test",
"key": "pog",
"value": "champ"
}
```
In some .java file:
```
...
UnsignedTx utx = txBuilder.creatorAccountId("admin@test") …
```
> Allow to query all account JSON data

- irohad/model/converters/impl/pb_command_factory.cpp
Fixes bug:
```C++
boost::assign::insert(pb_grant_map_)
// Can add my signatory
(protocol::GrantablePermission::can_add_my_signatory,
can_add_signatory)
// Can remove my signatory
(protocol::GrantablePermission::can_remove_my_signatory,
can_remove_signatory)
// Can set my quorum
(protocol::GrantablePermission::can_set_my_quorum, can_set_quorum)
// Can write details to other accounts
(protocol::GrantablePermission::can_set_my_account_detail,
can_set_detail) // ; <-- if ; is here, then next line(s) related to boost::assign::insert are ignored 
// Can transfer my assets
(protocol::GrantablePermission::can_transfer_my_assets,
can_transfer);
```
Fix warning at:
```bash
/Users/bogdan/tools/iroha/irohad/model/converters/impl/pb_command_factory.cp …
```
> Remove ; to fix warning "unused-value"

- README.md
- snap/snapcraft.yaml
This package will let you publish the latest iroha binaries in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery. 
1-command installs, complete isolation when the snap is made strict, automatic updates, 4 channels with different levels of risks to make things easy and fun for your testers.
At this point, none. You can just give it a try in edge, and see if you like it before publishing it to stable. Once it's in stable, you will get users and will have to keep moving the releases from the edge channel when they are ready.
> Add the packaging metadata to build the iroha snap

- test/module/shared_model/cryptography/crypto_usage_test.cpp
This PR fixes build error, when spdlog is not installed in the system.
> Fix build error when no spdlog installed

- docker/develop/Dockerfile
We compile cmake manually in dev docker, it uses internal libcurl without SSL. Because of this, #1070 build step on circle ci fails with `log: Protocol "https" not supported or disabled in libcurl`.
To fix this I:
- install `libcurl` with `openssl` support.
- I compile cmake with `--system-curl` option, to force cmake use libcurl with ssl cupport
Also, since we use SWIG and it requires cmake 3.7+, I update cmake version to 3.7.2.
- this will let us to use hunter in circle ci (build will not fail in #1070)
None.
Because both changes (curl + cmake version) are made in a single dockerfile, it is hard for me to do 2 separate PRs for these changes, because each change requires full `hyperledger/iroha-docker-develop:v1` rebuild -- and this …
> Edit dev dockerfile: Add libcurl with ssl, set cmake v to 3.7.2

- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/iroha_instance.cpp
- test/integration/consensus/consensus_sunny_day.cpp
- test/integration/pipeline/transfer_asset_inter_domain_test.cpp
- test/integration/pipeline/tx_pipeline_integration_test.cpp
- test/integration/pipeline/tx_pipeline_integration_test_fixture.hpp
Some ides use port `10001` while the same port is used in tests in Iroha. That leads to failing tests. That PR changes port `10001` to `50541` in such tests. 
None
> Change port from 10001 to 50541 in tests

- shared_model/validators/field_validator.cpp
- shared_model/validators/field_validator.hpp
- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/create_role_test.cpp
Adds acceptance tests for CreateRole command
Disabled test:
- **InexistentPerm** - issue at serialization for hashing [here](url), should work after moving tx processor to the new model
- **ExistingRole** - deadlock due to multiple insertions, doesn't seem obvious
Coverage, stability
~2 min of test execution time, itf issue?
> CreateRole acceptance tests

- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/create_account_test.cpp
Add CreateAccount tests.
Hopefully all works as expected, so there is no disabled tests
+ ~100 sec of test execution time :(
`make create_account_test && test_bin/create_account_test`
> Add CreateAccount acceptance tests

- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/create_domain_test.cpp
Add CreateDomain tests.
<s>Hopefully all works as expected, so there is no disabled tests</s>
**UPD**: empty role passes stateless validation, so it is disabled
+ ~100 sec of test execution time :(
`make create_domain_test && test_bin/create_domain_test`
> Add CreateDomain acceptance tests

- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/transfer_asset_test.cpp
Add TransferAsset tests.
Hopefully all works as expected, so no disabled tests
+ ~150 sec of test execution time :(
`make transfer_asset_test && test_bin/transfer_asset_test`
> Add TransferAsset acceptance tests

- shared_model/validators/transaction_validator.hpp
- test/integration/acceptance/transfer_asset_test.cpp
- test/module/shared_model/validators/validators_fixture.hpp
The asset transfer can be performed to the same account who is creating transaction with asset transfer. That prs disables that feature via stateless check.
Also there is a test
Quite better attack resistance
> Prohibit TransferAsset with source equals destination

- test/module/irohad/torii/processor/query_processor_test.cpp
- test/module/irohad/torii/processor/transaction_processor_test.cpp
Idk why CI passes, but clang 5.0.1 don't want to build without that fixes
> Fixes clang build

- irohad/torii/command_service.hpp
- irohad/torii/impl/command_service.cpp
For now stateless validation fail cause no output, that may waste time at debugging stuff. This pr introduce logging such a case (and some other corner cases) in CommandService.
Resolves #803, better logging
> Add CommandService logging

- irohad/ordering/impl/ordering_service_impl.cpp
- irohad/ordering/impl/ordering_service_impl.hpp
- test/module/irohad/ordering/ordering_service_test.cpp
If psql is stopped during irohad, the last one may cause sigsegv, abort or smth else.
This pr introduces few checks for db activeness
Stability
These steps will cause irohad failing:
1. start postgres
2. start irohad
3. stop postgres
4. send something via iroha-cli
With that fixes it doesn't do anything
Maybe call `std::abort` with meaningful error?
> Fix irohad failing on stopped postgres

- example/Android/.gitignore
- example/Android/android-build.sh
Iroha bindings build script for Android
If you want to use Iroha bindings in Android you need to have libirohajava.so native library and a set of .java files. It's quite tricky to build them because shared library should be native for a target Android architecture. With this script build process becomes an easy thing.
None.
Script should be run from an empty folder:
```Example: ./android-build.sh arm64-v8a 26 /Users/me/Downloads/android-ndk-r16b jp.co.soramitsu.iroha.android```
If you run it without parameters it will show you help message.
> Add Iroha build script for Android

- cmake/Modules/Findswig.cmake
Disable ccache on SWIG compilation.
Fix build of **iroha-lib** NPM package, because CMake running under GYP doesn't want to compile SWIG with ccache enabled.
Slightly increases build time and **ccache-swig** tool will not be built.
> Remove ccache from Findswig.cmake

- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/postgres_block_query.cpp
- irohad/ametsuchi/ordering_service_persistent_state.hpp
- irohad/network/impl/block_loader_impl.cpp
- test/integration/acceptance/get_transactions_test.cpp
- test/module/libs/common/result_test.cpp
- test/module/shared_model/cryptography/crypto_usage_test.cpp
Build failed with clang version 5.0.1 (tags/RELEASE_501/final) due to tests being built with warnings treated as errors. This pull request removed unused captures.
Project builds with clang 5.0.1
None
> Fix build errors related to unused lambda captures

- test/module/irohad/ametsuchi/ametsuchi_test.cpp
- test/module/irohad/ametsuchi/block_query_test.cpp
- test/module/irohad/ametsuchi/block_query_transfer_test.cpp
- test/module/irohad/consensus/yac/yac_crypto_provider_test.cpp
- test/module/irohad/simulator/simulator_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
Fix `std::string` constructor calls with implicitly converted arguments, which lead to address sanitizer errors.
No sanitizer errors in ametsuchi_test, and other tests changed in pull request.
This looks like a temporary solution, because these kinds of errors could repeat in the future.
> Fix std::string constructor arguments in tests

- iroha-cli/interactive/impl/interactive_transaction_cli.cpp
- irohad/execution/impl/command_executor.cpp
- irohad/model/converters/impl/pb_command_factory.cpp
- irohad/model/generators/impl/command_generator.cpp
- irohad/model/impl/query_execution.cpp
- shared_model/validators/field_validator.cpp
- shared_model/validators/permissions.hpp
- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/test_block_generator.cpp
- test/integration/acceptance/add_asset_qty_test.cpp
- test/integration/acceptance/create_account_test.cpp
- test/integration/acceptance/create_domain_test.cpp
- test/integration/acceptance/create_role_test.cpp
- test/integration/acceptance/get_transactions_test.cpp
- test/integration/acceptance/subtract_asset_qty_test.cpp
- test/integration/acceptance/transfer_asset_test.cpp
- test/integration/client_test.cpp
- test/module/irohad/ametsuchi/ametsuchi_test.cpp
- test/module/irohad/ametsuchi/kv_storage_test.cpp
- test/module/irohad/model/command_validate_execute_test.cpp
- test/module/irohad/model/converters/json_commands_test.cpp
- test/module/irohad/model/converters/pb_commands_test.cpp
- test/module/irohad/torii/processor/query_processor_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/validation/query_execution.cpp
- test/module/shared_model/validators/field_validator_test.cpp
Move permissions from iroha::model to shared_model::permissions
Permissions.hpp was moved to shared model but namespace still was old (iroha::model). Now it's fixed.
None.
> Change namespace for permissions

- shared_model/validators/field_validator.cpp
- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/tx_heavy_data.cpp
Add tests for heavy transactions.
We have tests that cover problems with transport.
Nowadays it is just a disabled tests because of the cost of fixes is very large.
> Tests for heavy transactions

- iroha-cli/main.cpp
Allow transaction loading for genesis block generation in cli. I know it is going to be rewritten but that small fix enable that vial feature.
Configuration of the genesis block
1. Generate transaction in json
2. Launch `iroha-cli --genesis_block --genesis_transaction <your_file>`
> Add feature for custom genesis block gen

- irohad/torii/impl/command_service.cpp
- irohad/torii/impl/query_service.cpp
- schema/endpoint.proto
- schema/responses.proto
- test/module/iroha-cli/client_test.cpp
Added error message to response, if stateless validation has failed. Now ErrorResponse and Torii response will have information from the stateless validator.
Clients can now see what went wrong with if their transactions or queries do not pass stateless validation
Size of the response is increased in some cases.
> Stateless_invalid response contains error message

- irohad/consensus/yac/impl/yac_gate_impl.cpp
- irohad/consensus/yac/impl/yac_gate_impl.hpp
- test/module/irohad/consensus/yac/yac_gate_test.cpp
Retry to synchronize storage if the previous attempt was unsuccessful
Before, if the block query failed (nodes hadn't applied block yet), the polling node doesn't make any attempt to synchronize again. In this PR it is fixed. 
None
> fix synchronization issues

- .jenkinsci/linux-post-step.groovy
- Jenkinsfile
Signed-off-by: bakhtin <a@bakhtin.net>
This PR fixes the case, when CI build artifacts could have been uploaded on unsuccessful build or not uploaded at all (e.g., build was aborted and artifacts were not generated)
More stable and consistent process of uploading artifacts
None
> Fix artifacts uploading on unsuccessful build

- irohad/model/converters/impl/pb_query_response_factory.cpp
- irohad/torii/impl/query_service.cpp
- schema/responses.proto
- shared_model/backend/protobuf/query_responses/proto_query_response.hpp
- shared_model/builders/protobuf/builder_templates/query_response_template.hpp
- test/module/shared_model/backend_proto/shared_proto_query_responses_test.cpp
This pr change QueryResponse.query_hash to be a hex-encoded string instead of byte array.
Since this data is returned inside a json object is should have a hex representation - similar to transaction hashes. Binary strings can be a problem to deal with in some client languages. 
--
> Use hex-encoded query hashes instead of binary hashes

- irohad/ordering/impl/ordering_service_impl.cpp
- irohad/ordering/impl/ordering_service_impl.hpp
- test/module/irohad/ordering/ordering_service_test.cpp
Fix issues with heap-use-after-free and `generateProposal` thread working after destructor.
- `unsubscribe` call now blocks until a running method is completed
- no more mutex for destructor
- mutex is used when a transaction is received from the network, so that subject calls are not concurrent
- queue size is verified when subscriber is called, and not when event is received
More stable implementation
Code duplication in constructor caused by templates in rxcpp, which are only removed after `subscribe`. A possible solution is to pass coordination as template parameter, but this will require some type rework and renaming.
> Rework ordering service event handling

- shared_model/packages/javascript/binding.gyp
Signed-off-by: Arseniy Fokin <stinger112@gmail.com>
Use only Shared Model own build system instead of Iroha's one.
Paths to Iroha home have been changed to Shared Model home.
> [Feature] Change paths to use Shared Model in NPM

- irohad/main/application.cpp
- irohad/main/application.hpp
Block loader, consensus, and ordering service can access peer query concurrently, which may lead to race condition if same connection is reused, because postgres connection does not handle concurrent accesses. Separate connection are used in these components now.
Less race conditions, more stable tests
At least two new connections to database. Probably a more elegant way can be found later with a connection pool for example.
> Fix peer query race condition

- irohad/consensus/yac/impl/yac_gate_impl.cpp
- shared_model/backend/protobuf/block.hpp
- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/backend/protobuf/transaction.hpp
- shared_model/interfaces/base/signable.hpp
The shared model had the method that clean signatures inside an object. This method is not suitable for the philosophy of sh_m objects - this method does object invalid in terms of stateless validation. 
Remove method that breaks stateless validation for sh_m objects.
We have to check the stability of bindings by ourself. CI cannot handle it now.
> Remove clearSignatures method

- irohad/consensus/yac/impl/timer_impl.cpp
- irohad/consensus/yac/impl/timer_impl.hpp
- irohad/consensus/yac/impl/yac.cpp
- irohad/consensus/yac/timer.hpp
- irohad/consensus/yac/yac.hpp
- irohad/main/impl/consensus_init.cpp
- irohad/main/impl/consensus_init.hpp
- test/integration/consensus/consensus_sunny_day.cpp
- test/module/irohad/consensus/yac/timer_test.cpp
- test/module/irohad/consensus/yac/yac_mocks.hpp
- test/module/irohad/consensus/yac/yac_rainy_day_test.cpp
- test/module/irohad/consensus/yac/yac_simple_cold_case_test.cpp
- test/module/irohad/consensus/yac/yac_sunny_day_test.cpp
- test/module/irohad/consensus/yac/yac_unknown_peer_test.cpp
Add external rx observable to yac timer, so that it is possible to write it in a testable way -- events are fired at expected time points.
Timer testability without real time assumptions
Not as flexible as before -- it's not possible to reuse the same timer with different delays. But since changes are local -- only consensus is involved -- it's fine to change interface later when something more flexible will be required.
> YAC Rx timer dependency

- irohad/ametsuchi/impl/storage_impl.cpp
- irohad/ametsuchi/impl/storage_impl.hpp
- irohad/ametsuchi/storage.hpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/ametsuchi/ametsuchi_test.cpp
adds on_commit observable to storage
needed for blockQuery in the future
--
> add on_commit observable to storage

- irohad/model/impl/model_operators.cpp
- shared_model/backend/protobuf/block.hpp
- shared_model/backend/protobuf/transaction.hpp
- shared_model/interfaces/common_objects/signature.hpp
- test/module/irohad/model/operators/model_operators_test.cpp
- test/module/shared_model/cryptography/CMakeLists.txt
- test/module/shared_model/cryptography/security_signatures_test.cpp
* Fix sh_m and old-fashion model signature operator==
* Fix ::addSignature for sh_m tx and block
Close potential security issues for Iroha's stateless validation.
Tests are provided.
> * Fix operator== for signatures type in old-fashion model and sh_m

- cmake/functions.cmake
Add the type of tests for Ctest names. Type of test is fetching from the source path of the test.
Currently available the following prefixes:
* "module_" for unit tests
* "regression_" for finding regressions
* "integration_" for integration tests
* and "system_" for system tests, respectively.
Possible to build only required tests for different cases in CI
Name of tests is not a same with the name of a target.
> Add prefix with type of test for Ctest names

- .jenkinsci/debug-build.groovy
- .jenkinsci/docker-manifest.groovy
- .jenkinsci/docker-pull-or-build.groovy
- .jenkinsci/release-build.groovy
- Jenkinsfile
Introduce automatic updates of Docker manifest file with each push to Docker registry. Previously it was uploaded manually once (`docker/manifest.yaml`) using `manifest-tool` Go-written program. It was considered sufficient and assumed that each successive update of an image under some tag would update its parent reference. Turned out we must reupload manifest file with each push of the tag. Instead of using `manifest-tool` this PR exploits a new feature introduced in Docker 18. It allows to manipulate manifest file using Docker CLI itself.
Always up-to-date Docker manifest file
Slightly slower Jenkins CI builds (~3-4s degradation per build)
> Automate Docker manifest uploading

- shared_model/utils/CMakeLists.txt
- shared_model/utils/amount_utils.cpp
- shared_model/utils/amount_utils.hpp
- test/module/shared_model/amount_utils_test.cpp
It was unable to build Iroha on some systems. The fix arranges dependencies as it should be.
Thanks to @lebdron for the fix!
Iroha can be built on systems without google protobuf header files installed.
None
`cmake -H. -Bbuild`
`cmake --build build`
> Fix build issues related to changes in "amount utils"

- test/framework/integration_framework/integration_test_framework.cpp
- test/regression/regression_test.cpp
No segfault will occur when unused ITF instance is destructed.
The following code would not cause segfault:
```
{
IntegrationTestFramework itf(1);
}
```
None
```
cmake -Bbuild -H.
cmake --build build --target regression_test
build/test_bin/regression_test --gtest_filter=RegressionTest.DestructionOfNonInitializedItf
```
The rest of ITF methods such as "sendTx" could also get the fix, but they are left without such check of null pointers as it was done inside "done" method by this fix.
**This is ok**, because "done" will be called automatically inside default ITF deleter passed to destructor and "sendTx" would not. 
Moreover, "sendTx" will generate an exception only in case of strict violation of ITF usage mechanism (calling "sendTx" without …
> Fix segfault when non intialized ITF were destructed

- irohad/consensus/yac/impl/supermajority_checker_impl.cpp
- irohad/torii/processor/impl/query_processor_impl.cpp
- irohad/validation/impl/stateful_validator_impl.cpp
- irohad/validation/impl/stateful_validator_impl.hpp
- irohad/validation/utils.hpp
- test/module/irohad/validation/CMakeLists.txt
- test/module/irohad/validation/stateful_validator_test.cpp
Decrease redundancy in public key check in signature range.
Less self-repeating code
There's additional alloc+copy in SupermajorityCheckerImpl, that probably might be optimized
> Extract signaturesSubset function

- deploy/ansible/roles/iroha-cluster-deploy-node/defaults/main.yml
- deploy/ansible/roles/iroha-standalone-deploy-node/defaults/main.yml
Signed-off-by: tyvision <antykushin@gmail.com>
As docker container naming on dockerhub has been fixed, we need to update ansible playbooks for iroha deployment.
Variable `irohaDockerImageTag` is changed from `develop` to `master`
It fixes iroha deployment in docker using ansible
> fix iroha dockerimage tag

- irohad/ametsuchi/CMakeLists.txt
- irohad/ametsuchi/impl/postgres_options.cpp
- irohad/ametsuchi/impl/postgres_options.hpp
- irohad/ametsuchi/impl/storage_impl.cpp
- irohad/ametsuchi/impl/storage_impl.hpp
- test/module/irohad/ametsuchi/CMakeLists.txt
- test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
- test/module/irohad/ametsuchi/postgres_options_test.cpp
- test/module/irohad/ametsuchi/storage_test.cpp
Postgres database can have dbname parame. We can use it to run every test with database in parallel by creating a new instance of database for each test
More flexible database creation
Drop database is not implemented, so after all tests are executed an empty instance of database might be left.
> Add dbnname param

- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/integration_test_framework.hpp
- test/framework/integration_framework/iroha_instance.hpp
- test/regression/regression_test.cpp
Add test that allows us to ensure that Iroha state still can be recovered from existing block store.
Increased coverage.
None
```
cmake --build build --target regression_test
./build/test_bin/regression_test --gtest_filter=RegressionTest.StateRecovery
```
> Add state recovery test

- .jenkinsci/bindings.groovy
Java bindings on Jenkins CI are generated with dynamically linked `libed25519.so`. End users do not necessarily have this library installed on the system. This makes Java bindings without `libed25519.so` not usable. This PR fixes this issue by removing ed25519 files from the system prior configuring the build with CMake.
Generation of working Java bindings on CI without the need to have ed25519 installed on the system
None
Freshly generated Java bindings to test with:
https://artifact.soramitsu.co.jp/iroha/bindings/java/java-bindings-Release-20180523-928b22.zip
> Fix libed25519 linked dynamically

- irohad/synchronizer/impl/synchronizer_impl.cpp
- test/module/irohad/synchronizer/synchronizer_test.cpp
Fixing synchronization bug
Create network of 4 nodes.
Start only 3 nodes and send a transaction.
Start the disabled node and send a transaction (so that trigger synchronization)
The last one will fall
Didn't find useful routines in rxcpp, maybe it can be rewritten in more elegant way
> Fix synchronization bug

- irohad/ametsuchi/impl/postgres_block_query.cpp
- irohad/ametsuchi/impl/postgres_block_query.hpp
- irohad/ametsuchi/impl/storage_impl.cpp
- irohad/ametsuchi/impl/storage_impl.hpp
- irohad/main/application.cpp
- irohad/torii/command_service.hpp
- irohad/torii/impl/command_service.cpp
- irohad/torii/processor/impl/query_processor_impl.cpp
- irohad/torii/processor/query_processor_impl.hpp
- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/query_test.cpp
- test/module/iroha-cli/client_test.cpp
- test/module/irohad/ametsuchi/storage_init_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
Same connection was reused from different gRPC threads causing errors.
- Return block query with unique connection
- Use mutex when writing to query notifier
- Remove unused connections from storage
- Use unique connection for each status query
Stable block query in terms of postgres connections.
A new connection is created on each query 🙈 
https://github.com/hyperledger/iroha/blob/1443c2611ccc2eb3e14e93e10e8d3cdf2da2fdf2/test/integration/acceptance/query_test.cpp#L74-L91
> Fix block query race condition

- iroha-cli/impl/query_response_handler.cpp
- iroha-cli/interactive/impl/interactive_query_cli.cpp
- iroha-cli/interactive/interactive_query_cli.hpp
Add _GetAccountAssetTransactions_ handler to `iroha-cli` and update _QueryResponseHandler_ to print more information for Transactions Responses.
Makes the CLI a little more complete and improves the output to make transactions a bit more traceable. 
None
None
None
> Add GetAccountAssetTransactions handler to the CLI

- iroha-cli/impl/query_response_handler.cpp
- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/postgres_block_index.cpp
- irohad/ametsuchi/impl/postgres_block_query.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.cpp
- irohad/simulator/impl/simulator.cpp
- irohad/torii/processor/impl/transaction_processor_impl.cpp
- irohad/validation/impl/stateful_validator_impl.cpp
- shared_model/backend/protobuf/block.hpp
- shared_model/backend/protobuf/proposal.hpp
- shared_model/backend/protobuf/queries/proto_get_transactions.hpp
- shared_model/backend/protobuf/queries/proto_query.hpp
- shared_model/backend/protobuf/query_responses/proto_transaction_response.hpp
- shared_model/backend/protobuf/transaction.hpp
- shared_model/interfaces/common_objects/types.hpp
- shared_model/interfaces/iroha_internal/block.hpp
- shared_model/interfaces/iroha_internal/proposal.hpp
- shared_model/interfaces/query_responses/transactions_response.hpp
- shared_model/interfaces/transaction.hpp
- shared_model/validators/container_validator.hpp
- shared_model/validators/transaction_validator.hpp
- test/integration/acceptance/get_transactions_test.cpp
- test/integration/acceptance/query_test.cpp
- test/module/irohad/ametsuchi/block_query_transfer_test.cpp
- test/module/irohad/execution/command_validate_execute_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/validation/query_execution.cpp
- test/module/shared_model/builders/common_objects/query_response_builder_test.cpp
- test/regression/regression_test.cpp
Continuing #1397 
Replaced intermediate transaction collection in stateful validator with `boost::filtered`
Hopefully only one more PR required to remove polymorphic wrapper from the project
GCC 5.4 required a workaround for set initialization because it used `insert` instead of `emplace` in iterator constructor
Even less polymorphic wrapper
None
> Remove polymorphic wrapper from transaction and transaction collection

- shared_model/bindings/model_transaction_builder.cpp
- shared_model/bindings/model_transaction_builder.hpp
- shared_model/packages/javascript/tests/txbuilder.js
- shared_model/validators/transaction_validator.hpp
- test/integration/acceptance/acceptance_fixture.cpp
- test/module/shared_model/builders/protobuf/block_builder_test.cpp
- test/module/shared_model/builders/protobuf/transport_builder_test.cpp
- test/module/shared_model/validators/transaction_validator_test.cpp
Add missed quorum function to transaction builder
Quorum can be set in client code.
None
> Add missed quorum function to transaction builder

- example/java/TransactionExample.java
- example/java/prepare.sh
- shared_model/bindings/CMakeLists.txt
Include package name declarations inside generated java bindings 
Classes inside the generated lib can now be imported from the package. 
Don't foresee any drawbacks
> include package name declarations in generated java bindings

- libs/common/visitor.hpp
- shared_model/builders/protobuf/block_variant_transport_builder.hpp
- shared_model/interfaces/CMakeLists.txt
- shared_model/interfaces/iroha_internal/block_variant.cpp
- shared_model/interfaces/iroha_internal/block_variant.hpp
- shared_model/validators/any_block_validator.hpp
- test/module/shared_model/builders/protobuf/transport_builder_test.cpp
Before BlockVariant was implemented via `using BlockVariantType=boost::variant<Block, EmptyBlock>`. This is not convenient in irohad because it forces to use visitors every time when it is needed to access BlockVariant's fields
Now it is a class which gives more convenient access to the fields in stored type
More convenient field access for BlockVariant
Multiple inheritance from boost::variant (to allow instantiation with either Block or EmptyBlock) and AbstractBlock (to guarantee AbstractBlocks interface)
> Update block variant

- .jenkinsci/release-build.groovy
`withRegistry` wrapper used in `release-build.groovy` file prevented from executing experimental Docker commands. Namely, `docker manifest` that is used to manage manifest files on Docker hub. My suggestion is that this wrapper somehow fiddles with the system environment and shoves its own `config.json` without experimental features enabled.
This wrapper was redundant anyway as we use `withCredentials` to passthrough login and password for Docker hub.
Develop and Master branch on Jenkins CI will not be failing every time
None
> Remove release build withRegistry wrapper

- .jenkinsci/debug-build.groovy
- Jenkinsfile
Signed-off-by: tyvision <antykushin@gmail.com>
All platforms except `mac` have `--output-on-failure` flag present on test step. This PR adds previously mentioned flag to `mac` platform.
Since now all useful output on failures during tests will be visible at the pipeline logs
> MacOS test step added --output-on-failure flag

- libs/common/visitor.hpp
Fix constexpr function in visitor.hpp: C++14 syntax for that aspect is unsupported by NDK compiler.
Working android bindings.
It remains unclear what's the problem exactly - problems with C++14 support by NDK (unlikely) or just a problem with constexpr functions.
> Use С++11 syntax for constexpr function

- irohad/consensus/yac/storage/impl/yac_vote_storage.cpp
- irohad/consensus/yac/transport/impl/network_impl.cpp
An attempt to move validation logic from consensus core to transport to perform stateless validation
Clearer responsibility separation
Transport contains validation logic in addition to gRPC specific methods -- some middle validation layer should be separated from transport
> Move vote collection validation to transport

- shared_model/bindings/model_crypto.cpp
- shared_model/bindings/model_crypto.hpp
- shared_model/packages/javascript/tests/crypto.js
- test/module/shared_model/bindings/model_crypto_test.cpp
Signed-off-by: Akvinikym <anarant12@gmail.com>
[IR-1223](https://soramitsu.atlassian.net/browse/IR-1223)
Previously, there was no possibility for client code to catch exceptions thrown by ModelCrypto::fromPrivateKey method, so type of exception was changed to std::invalid_argument.
Also, a check for equality between private_key argument's length and 64 was added with related exception throw in case of failure.
Lastly, a couple of new tests were written to test new functionality. 
Overall, this is remake of [old pull request](https://github.com/hyperledger/iroha/pull/1254), which was not fixed and merged.
The exception can now be caught by client's code
None
> Fix/wrap exception for ModelCrypto::fromPrivateKey(priv_key)

- example/python/tx-example.py
- shared_model/bindings/model_proto.hpp
This pr removes move semantics from ModelProto.
Swig doesn't support move semantics so it can't be used in client interfaces. This leads to segfault in tx_example.py.
1. Build and run irohad
2. Run example/python/prepare.sh
3. Run python2 tx-example.py
None.
> Remove move semantics from ModelProto template

- cmake/functions.cmake
Build of python_tests target was broken by commit https://github.com/hyperledger/iroha/commit/df23d337ca82e39451b78fbe7eaf6cb1b216caec. This pr fixes that.
Special thanks to @lebdron 🎉🎉
Now we able to build `python_tests`
None (?)
```
cmake -H. -Bbuild -DSWIG_PYTHON=ON
cmake --build build --target irohapy
cmake --build build --target python_tests
cd build
ctest -R python . # it is expected that python_query_test fails (getaccountassets, will be fixed later) 
```
> Fix build of python_tests target

- shared_model/interfaces/iroha_internal/block_variant.cpp
Windows build fails due to "`Args` are not unpacked" error, but it works with `decltype(args)`, which serves the same purpose.
Successful Windows build
None
Build of python bindings fails due to CI update, so there is an error displayed. The code itself builds fine.
> Fix variable forward for variadic in Windows build

- shared_model/backend/protobuf/query_responses/impl/proto_transaction_response.cpp
After [this](https://github.com/hyperledger/iroha/pull/1424) pull request Clang started [complaining](https://gist.githubusercontent.com/igor-egorov/6e109625916850b64063ac62dc3fba08/raw/de29ad4a661e01a5acab5ece97973c6e26e31128/cmake-iorhad.log) about wrong order of initialisations of fields of Proto Transaction Response, because one of them is dependent on the other, so order of initialisation was changed to eliminate the warning
Clang stopped complaining
None
> [fix] Clang warnings

- irohad/torii/processor/impl/query_processor_impl.cpp
- test/integration/acceptance/query_test.cpp
Fix query_test nasty bug.
- query_processor_impl doesn't have proper mutex lock for its observable
- using `dummy_tx` by ref occasionally causes heap overflow, so capture by value
- (optional) hash can be retrieved once
Make CI Green Again
Quite slower due to copying (~100ms for me, so not really a big problem)
`make query_test && test_bin/query_test`
> Fix query_test RC

- shared_model/bindings/model_crypto.cpp
- shared_model/cryptography/ed25519_sha3_impl/crypto_provider.cpp
- shared_model/cryptography/ed25519_sha3_impl/crypto_provider.hpp
- shared_model/validators/field_validator.cpp
- shared_model/validators/field_validator.hpp
- test/integration/acceptance/get_transactions_test.cpp
- test/integration/acceptance/tx_acceptance_test.cpp
- test/integration/consensus/consensus_sunny_day.cpp
- test/integration/transport/ordering_gate_service_test.cpp
- test/module/irohad/ametsuchi/block_query_test.cpp
- test/module/irohad/execution/command_validate_execute_test.cpp
- test/module/irohad/network/block_loader_test.cpp
- test/module/shared_model/builders/protobuf/block_builder_test.cpp
- test/module/shared_model/validators/field_validator_test.cpp
Remove magic consts from code related to crypto sizes and introduce such constants in crypto provider
No magics
None
> Add crypto related sizes consts

- irohad/execution/impl/command_executor.cpp
- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/set_account_detail_test.cpp
- test/module/irohad/execution/command_validate_execute_test.cpp
Makes a required fixes so that following tests accepted:
- SetAccountDetail on itself can be set w/o any perm
Less bugs, more coverage
None
> Fix bugs related to SetAccountDetail

- shared_model/validators/field_validator.cpp
- shared_model/validators/field_validator.hpp
- shared_model/validators/query_validator.hpp
- test/module/shared_model/bindings/QueryTest.java
- test/module/shared_model/bindings/query-test.py
GetTransaction qry is know validated for:
- tx_hash must be non-empty
- tx_hash elements must be valid hash (in terms of size)
Presented for bindings:
`ctest -R '(python|java)'`
> Fix issues with GetTransaction validation

- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/get_account_assets_test.cpp
There've been reported bugs about querying GetAccountAssets for zero balance. This pr introduces tests, that show the behavior is normal
More test for the God of Tests
None
`make get_account_assets_test && test_bin/get_account_assets_test`
> Add test for GetAccountAssets qry

- irohad/execution/impl/command_executor.cpp
- test/integration/acceptance/transfer_asset_test.cpp
Transfering asset with non-zero precision causes writing to WSV amount without precision and that basically lead to the strange things.
Particularly amount at [this line](https://github.com/hyperledger/iroha/pull/1470/files#diff-61f63c72eb4f7dc6082d4c9a2a4f8b5cL451) isn't properly set because it's not adjusted to the proper precision. Basically interested line is [this](https://github.com/hyperledger/iroha/pull/1470/files#diff-61f63c72eb4f7dc6082d4c9a2a4f8b5cL425) but it contains result, so there's no easy fix, so that's why the PR contains refactorings
Plus one test and minus one bug.
Also code for execution of TransferAsset was flattened (thus i believe simpler to read)
None
`make transfer_asset_test && test_bin/transfer_asset_test`
> Fix TransferAsset strange behavior

- irohad/ametsuchi/impl/storage_impl.cpp
- test/module/irohad/ametsuchi/ametsuchi_test.cpp
Until fix blocks were emitted only in insert_block method, which is not right, since it should emit every block when commit on storage is happening.
Proper behavior of ametsuchi
None
Run ametsuchi test
> Fix on commit

- irohad/torii/processor/impl/query_processor_impl.cpp
- test/module/irohad/torii/processor/query_processor_test.cpp
BlocksQueryHandle method emitted block error response to the blocks observable, which lead to getting stateful invalid responses by users who subscribed on committed blocks.
No one will get block error response but the caller who sent bad request
None
New blocks query test
> Fix blocks query handle

- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/integration_test_framework.hpp
- test/integration/acceptance/acceptance_fixture.cpp
- test/integration/acceptance/acceptance_fixture.hpp
- test/integration/acceptance/transfer_asset_test.cpp
- Add IntegrationTestFramework::sendTxAwait
- Reuse AcceptanceFixture primitive in TA test
- Move out primitive methods in fixture
- Fix WithOnlyCanTransferPerm/WithOnlyCanReceivePerm tests
Also, [I've tried](http://termbin.com/ega0) to remove `Role::kAddAssetQty` from the first user but it seems to have some bug. Feel free to review/comment it as well
Lesser simpler code -> lesser bugs
None?
`make transfer_asset_test && test_bin/transfer_asset_test`
> Refactor TransferAsset acceptance test

- irohad/execution/impl/query_execution.cpp
- shared_model/interfaces/impl/permissions.cpp
- shared_model/interfaces/permissions.hpp
- test/module/iroha-cli/client_test.cpp
- test/module/irohad/execution/CMakeLists.txt
- test/module/irohad/execution/query_execution_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/validation/CMakeLists.txt
For some reason Queries are checked against Grantable permissions (Grantable are only for commands). This pr removes redundant code (checking in execution, checking in EXPECT_CALL's, test for grantable perms) also `permissions::permissionOf` removal is there 
The lesser useless code the happier people are
None?
> Remove hasAccountGrantablePermissions in qry exec

- iroha-cli/interactive/impl/interactive_common_cli.cpp
- iroha-cli/interactive/impl/interactive_query_cli.cpp
- iroha-cli/interactive/impl/interactive_status_cli.cpp
- iroha-cli/interactive/impl/interactive_transaction_cli.cpp
- iroha-cli/interactive/interactive_common_cli.hpp
- iroha-cli/interactive/interactive_query_cli.hpp
- iroha-cli/interactive/interactive_transaction_cli.hpp
Cache CLI input values to make it more convenient (#827).
There are two use cases. 
1. Make is possible to use default values provided during creation of a `iroha_cli::interactive::ParamsMap` - If a default value is provided (e.g. default host/port), that will be used when the user input is empty.
2. Cache any user inputs - When an input is captured for a parameter, that value is cached and displayed on the input prompt for that parameter. If the user input is empty, cache value will be used.
Get rid of annoying repeated host/port entries when attempting to send requests to Iroha (among other inputs) and make the CLI less frustrating to use.
There's no option to remove a cached value other than replacing it with a new value. However, the CLI doesn't allow empty inputs so this shouldn't be …
> Cache CLI input values

- shared_model/validators/field_validator.cpp
- shared_model/validators/field_validator.hpp
- shared_model/validators/transaction_validator.hpp
- test/integration/acceptance/create_role_test.cpp
- test/module/shared_model/validators/transaction_validator_test.cpp
Remove PermissionSet constraints so it's possible to perform `CreateRole` with empty permission set (in other words role doesn't have to have any permission)
Possible to create role without rights
None?
`make create_role_test && test_bin/create_role_test`
> Remove PermissionSet constraints

- shared_model/validators/field_validator.cpp
Corrects error message for Peer's address in stateless validation
Fixes #1467
> Fix error message for Peer's address

- irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
- schema/mst.proto
Reusing peer in mst.proto
Less code duplication in schema
Worse extensionability of mst.proto
> Reuse Peer in mst.proto

- shared_model/packages/javascript/tests/txbuilder.js
- test/module/shared_model/bindings/BuilderTest.java
- test/module/shared_model/bindings/builder-test.py
The behavior of createRole command was changed, so the tests had to be updated.
Fixed tests.
None ?
```
cmake -H. -Bbuild -DSWIG_PYTHON=ON -DSWIG_JAVA=ON -DSWIG_NODE=ON
cmake --build build --target irohajava
cmake --build build --target irohapy
cmake --build build --target python_tests
cmake --build build --target irohanode
cd build
ctest -R "(java|python)" --output-on-failure
```
> Fix tests for createRole with empty set of permissions

- test/benchmark/CMakeLists.txt
- test/benchmark/bm_proto_creation.cpp
This Pull Request adds benchmark for creation of blocks and proposal in various ways (move, copy, clone). We found this to be a considerable cpu bottleneck when profiling the pipeline. The first step in the elimination of that bottleneck is to provide some way to measure the performance of such operations.
https://soramitsu.atlassian.net/wiki/spaces/IS/pages/55968207/How+to+run+test
Benchmarks allow understanding the performance cost of the changes.
API change for block or proposal may make these benchmarks useless
> block and proposal creation benchmark

- .jenkinsci/bindings.groovy
- Jenkinsfile
This adds an option to set Java bindings package name in Jenkins CI builds. It defaults to 'jp.co.soramitsu.iroha'. To change it either change the default name in Jenkinsfile or login into Jenkins and run appropriate branch build with 'Build with parameters' with package name of your choice.
Package name manipulation is useful for importing resulting bindings into other Java projects that requires certain naming
None
An example of a zip-packaged bindings with custom package name can be found on our artifacts server: https://artifact.soramitsu.co.jp/iroha/bindings/java/java-bindings-Release-windows-20180628-fd3344.zip
> Java bindings package name

- shared_model/builders/protobuf/transaction_sequence_builder.hpp
- shared_model/builders/protobuf/unsigned_proto.hpp
- shared_model/interfaces/iroha_internal/batch_meta.hpp
- shared_model/interfaces/iroha_internal/transaction_sequence.cpp
- shared_model/interfaces/iroha_internal/transaction_sequence.hpp
- shared_model/validators/CMakeLists.txt
- shared_model/validators/transactions_collection/any_order_validator.hpp
- shared_model/validators/transactions_collection/batch_order_validator.cpp
- shared_model/validators/transactions_collection/batch_order_validator.hpp
- shared_model/validators/transactions_collection/order_validator.hpp
- shared_model/validators/transactions_collection/signed_transactions_collection_validator.cpp
- shared_model/validators/transactions_collection/signed_transactions_collection_validator.hpp
- shared_model/validators/transactions_collection/transactions_collection_validator.hpp
- shared_model/validators/transactions_collection/unsigned_transactions_collection_validator.cpp
- shared_model/validators/transactions_collection/unsigned_transactions_collection_validator.hpp
- test/module/shared_model/builders/protobuf/transport_builder_test.cpp
Add Validators for transaction sequence (batches) ->
Needed for batch logic
--
> Transaction Sequence Validator

- libs/cache/abstract_cache.hpp
* Fix missed locks in abstract_concurrent_cahce
* Improve locking model with read/write lock semantic
Tests are absent.
In the ideal situation here should be two tests:
1. concurrent tests for getters. But there very hard to get the segfault on them.
2. concurrent test which proves performance issue.
> Add concurrent fix for abstract cache

- irohad/ametsuchi/impl/postgres_wsv_command.cpp
`soci::use` uses the lvalue variables. The precision in insertAsset was passed as temporary an thus used after its scope ending. The pr is extends the precision lifetime
Minus one bug
None
> Increase presision lifetime in insertAsset

- test/module/shared_model/bindings/QueryTest.java
Java bindings were not tested appropriately because of a little bug in tests. Now, it's fixed
All tests are passed
None
> Java bindings fix

- irohad/torii/impl/query_service.cpp
- irohad/torii/processor/impl/query_processor_impl.cpp
- irohad/torii/processor/query_processor.hpp
- irohad/torii/processor/query_processor_impl.hpp
- test/module/irohad/torii/processor/query_processor_test.cpp
- test/module/irohad/torii/query_service_test.cpp
- test/module/irohad/torii/torii_mocks.hpp
- test/module/irohad/torii/torii_service_query_test.cpp
Since simple queries are performed in synchronous manner there's a reason in queryNotifier removing and returning the response at queryHandle call. Also some functions was refactored, so they accept reference, instead of shared_ptr.
Code is simpler
None?
> Refactor QueryProcessor interface

- irohad/validation/impl/stateful_validator_impl.cpp
- test/module/irohad/validation/stateful_validator_test.cpp
Throwing exception, if batch is formed incorrectly, was a bad idea, so it was replaced with error and failure of the whole proposal - it's still an exceptional case, so we don't want such damaged proposal to be propagated further.
No exception
None
> Removed exception in batch SFV

- irohad/validation/utils.hpp
- test/module/irohad/validation/CMakeLists.txt
- test/module/irohad/validation/chain_validation_test.cpp
- test/module/irohad/validation/stateful_validator_test.cpp
- test/module/shared_model/interface_mocks.hpp
Builders replaced with the mocked SM's interfaces in ChainValidator and in SignatureSubset test of the stateful validatior.
Less dependent from builders, cleaner code
None?
> Mock builder introduction

- README.md
The link to the ReadTheDocs site needs to either be http://iroha.readthedocs.io or http://iroha.readthedocs.io/en/latest/. I've shortened it to the root url in the fix. The way it currently is (http://iroha.readthedocs.io/en/) results in a 404.
Link to docs fixed
Working link.
None
> Fix link to the docs

- cmake/Modules/Findtbb.cmake
<s>I don't really now why CI is able to compile it, but tbb::concurrent_queue doesn't really allow unique_ptr [due to try_pop signature](https://msdn.microsoft.com/en-us/library/ee355358.aspx#concurrent_queue__try_pop_method)</s>
It seems that the issue is in clang & tbb itself referenced below
Able to compile with clang compiler
> Use shared_ptr in tbb instead of unique

- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/mutable_storage_impl.hpp
- irohad/ametsuchi/mutable_storage.hpp
- test/module/irohad/ametsuchi/CMakeLists.txt
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/ametsuchi/mutable_storage_test.cpp
In chain validator we might need to check some logic on either EmptyBlock or Block types. Current interface of mutable storage does not allow that. To overcome this issue check method has been introduced which applies predicates logic on the block without actually applying the block to the storage.
We can validate block on storage without applying it
Probably we don't need check method to take AbstractBlock as parameter but use EmptyBlock instead.
Mutable storage test has been introduced
> Check block in mutable storage

- irohad/validation/impl/stateful_validator_impl.cpp
- shared_model/backend/protobuf/batch_meta.hpp
- shared_model/builders/protobuf/builder_templates/transaction_template.hpp
- shared_model/interfaces/iroha_internal/batch_meta.hpp
- shared_model/interfaces/iroha_internal/transaction_sequence.cpp
- shared_model/schema/transaction.proto
- shared_model/validators/transactions_collection/batch_order_validator.cpp
- test/module/shared_model/validators/field_validator_test.cpp
Tx hashes variable is ambiguous in batch meta. Transaction has two hashes: hash and reduced hash, thus reduced hashes is more meaningful name to this field
Better naming
None
> Rename tx hashes to reduced hashes

- .jenkinsci/debug-build.groovy
- .jenkinsci/release-build.groovy
Fixes a rare case when Docker images are not pushed to Dockerhub. This happens when there is a PR for merging `develop` branch into `master` and changes are introduced into Dockerfile. The code in Jenkins file checks for branch name equals `develop` and pushes an image. This check fails when there is a PR opened as branch name in this case equals to something like `PR-****`. 
We now check for parent branch of a PR as well.
Docker images are up-to-date
None
> Docker images push on existing develop branch PR

- libs/logger/logger.cpp
set_pattern could be called simultaneously from several threads affecting global context.
The similar issue - https://github.com/gabime/spdlog/issues/419
No segfault caused by spdlog configuring. 
None
```diff
cd build
make create_role_test
while test_bin/create_role_test ; do :; done
+the loop should not be interrupted by spdlog set_pattern segfault anymore
```
thanks to @lebdron
> Fix spdlog segfault

- test/module/irohad/torii/torii_service_test.cpp
The test (StreamingFullPipelineTest) was failing on slow machines. 
Investigation showed that the root cause was the way thread scheduler works, so the code was generally valid.
Streaming client resubscription is a fully valid use case of streaming service.
The client can resubscribe to the stream if the previous stream was ended unexpectedly for the client.
Unexpectedly means that client requests the hash of a transaction that was definitely sent to Iroha and the stream reaches its end with one of the following statuses: `NOT_RECEIVED`, `STATELESS_VALIDATION_SUCCESS`, `STATEFUL_VALIDATION_SUCCESS`.
Before the fix test client was not able to resubscribe to the stream. Now it can.
Legal test client behavior is implemented.
The test is not …
> Fix ToriiService Streaming Full Pipeline Test

- test/module/iroha-cli/client_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
The client test was failing on slow machines (CI).
The nature of failure was described and fixed in https://github.com/hyperledger/iroha/pull/1615 (please take a look for the details).
Non-failing test.
None
```diff
cd build
make torii_service_test
while test_bin/client_test ; do :; done
+this loop should not be broken up with the error from linux build https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/iroha%2Firoha-hyperledger/detail/PR-1597/39/pipeline/42
```
> Fix non-determinism in client test

- test/regression/regression_test.cpp
Regression test may fail in case of ITF fail during the previous run (for some reason).
In that case, block store was not empty and nobody did its cleanup, because of the exception.
Stability improved
None
regression_test
Generally speaking, all the ITF tests need to be wrapped into test fixtures where the tearDown method will do block store cleanup for the cases when ITF throws an exception.
The suggested fix is a must-have fix for regression test because StateRecovery case does sequential initialization of two ITF instances. Any exception inside the first instance will prevent calling the destructor of the second instance and block store will be left dirty.
> Fix regression test

- test/module/irohad/torii/torii_service_test.cpp
The time showed us that the rest of torii_service_test s also require the fix for thread scheduling issues on slow machines like our CI environment. 
The idea behind the fix is emulating client behavior while getting tx statuses - resubscribing.
Passing tests in a various environments.
Test behavior now is a bit closer to the behavior of a real Iroha user.
None. 
```
cmake --build build --target torii_service_test
cd build
ctest -R torii_service_test --output-on-failure
```
> Fix the rest of thread scheduling issues for torii service test

- irohad/ametsuchi/impl/postgres_command_executor.cpp
- test/module/irohad/ametsuchi/postgres_executor_test.cpp
It was impossible to add a role without permissions to account. Now it is possible.
One small bug was fixed.
> fix append empty role bug

- iroha-cli/interactive/impl/interactive_common_cli.cpp
- irohad/consensus/yac/CMakeLists.txt
- irohad/consensus/yac/impl/yac_gate_impl.hpp
- irohad/consensus/yac/impl/yac_proposal_gate_impl.cpp
- irohad/consensus/yac/impl/yac_proposal_gate_impl.hpp
- irohad/consensus/yac/impl/yac_proposal_hash_provider_impl.cpp
- irohad/consensus/yac/impl/yac_proposal_hash_provider_impl.hpp
- irohad/consensus/yac/yac_proposal_hash_provider.hpp
- irohad/model/converters/impl/json_command_factory.cpp
- irohad/model/converters/impl/json_query_factory.cpp
- irohad/model/converters/json_common.hpp
- irohad/network/proposal_gate.hpp
- libs/common/types.hpp
- test/module/irohad/consensus/yac/CMakeLists.txt
- test/module/irohad/consensus/yac/yac_mocks.hpp
- test/module/irohad/consensus/yac/yac_proposal_gate_test.cpp
- test/module/irohad/consensus/yac/yac_proposal_hash_provider_test.cpp
- test/module/shared_model/interface_mocks.hpp
YAC proposal gate implementation:
- Use hash gate for consensus
- Hash provider with round number as round indentifier and optional<hash> with vote
Bind operator `operator|` was updated to allow non-copyable objects. "Legacy" code in old model and iroha-cli was not compliant with changes and had to be updated.
> Proposal gate

- cmake/functions.cmake
- irohad/consensus/yac/transport/impl/network_impl.hpp
- irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
- irohad/network/impl/async_grpc_client.hpp
- irohad/ordering/CMakeLists.txt
- irohad/ordering/impl/on_demand_os_client_grpc.cpp
- irohad/ordering/impl/on_demand_os_client_grpc.hpp
- irohad/ordering/impl/on_demand_os_server_grpc.cpp
- irohad/ordering/impl/on_demand_os_server_grpc.hpp
- irohad/ordering/impl/ordering_gate_transport_grpc.hpp
- irohad/ordering/impl/ordering_service_transport_grpc.cpp
- irohad/ordering/on_demand_os_transport.hpp
- schema/ordering.proto
- test/framework/mock_stream.h
- test/module/irohad/ordering/CMakeLists.txt
- test/module/irohad/ordering/on_demand_os_client_grpc_test.cpp
- test/module/irohad/ordering/on_demand_os_server_grpc_test.cpp
- test/module/irohad/ordering/on_demand_os_test.cpp
- test/module/irohad/ordering/ordering_mocks.hpp
Add gRPC client and server for on demand ordering service
- Add gRPC mock class generation
- Unit tests for both client and server! No need to run real server with threads for unit tests
- Reuse server notification interface in client - each peer is represented with corresponding notification interface
- Factory is not covered with unit tests due to necessary hardcoded creation of real network channel. It will be covered by integration tests in next pull requests
- mock_stream.h is copied from gRPC repo with an addition of mock method, because it is not provided after installation
> On demand OS transport

- irohad/ordering/CMakeLists.txt
- irohad/ordering/impl/on_demand_connection_manager.cpp
- irohad/ordering/impl/on_demand_connection_manager.hpp
- irohad/ordering/impl/on_demand_ordering_service_impl.cpp
- irohad/ordering/impl/on_demand_ordering_service_impl.hpp
- irohad/ordering/impl/on_demand_os_client_grpc.cpp
- irohad/ordering/impl/on_demand_os_client_grpc.hpp
- irohad/ordering/on_demand_os_transport.hpp
- test/module/irohad/ordering/CMakeLists.txt
- test/module/irohad/ordering/on_demand_connection_manager_test.cpp
- test/module/irohad/ordering/on_demand_os_server_grpc_test.cpp
- test/module/irohad/ordering/ordering_mocks.hpp
- test/module/shared_model/interface_mocks.hpp
Implementation of connection manager component for on demand OS. Manager receives new peers and forwards the requests. Methods are thread safe.
It uses connection factory each time new peers are received, so that required peers are used with each update.
Shared lock is used to allow concurrent method calls and updates of peers.
> On demand OS connection manager

- irohad/torii/impl/command_service.cpp
- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/integration_test_framework.hpp
- test/integration/pipeline/pipeline_test.cpp
- test/regression/regression_test.cpp
This PR adds ability to send transaction sequences to the ITF and check stateless valid/invalid status
We can send sequences of transactions to the ITF
None
The test was added to pipeline test file
> Send tx sequence method in ITF

- shared_model/backend/protobuf/query_responses/impl/proto_error_query_response.cpp
- shared_model/backend/protobuf/query_responses/proto_error_query_response.hpp
- shared_model/interfaces/query_responses/error_query_response.hpp
- shared_model/interfaces/query_responses/impl/error_query_response.cpp
- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/acceptance_fixture.cpp
- test/integration/acceptance/acceptance_fixture.hpp
- test/integration/acceptance/add_asset_qty_test.cpp
- test/integration/acceptance/get_account_asset_txs_test.cpp
- test/integration/acceptance/get_account_assets_test.cpp
- test/integration/acceptance/grantable_permissions_fixture.cpp
- test/integration/acceptance/grantable_permissions_fixture.hpp
- test/integration/acceptance/revoke_permission_test.cpp
- test/integration/acceptance/subtract_asset_qty_test.cpp
- test/integration/acceptance/transfer_asset_test.cpp
- test/integration/acceptance/tx_acceptance_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
The pr introduces tests for getAccountAssetTransactions query.
Increased code coverage.
Two issues were revealed:
* [IR-1631 Wrong response on getAccountAssetTransactions query (a non-existing account or asset)](https://soramitsu.atlassian.net/browse/IR-1631)
* [IR-1632 Missing transactions in getAccountAssetTransactions query response](https://soramitsu.atlassian.net/browse/IR-1632)
None. The code is beautiful 😊
```
cd build
make get_account_asset_txs_test
ctest -R get_account_asset_txs_test --output-on-failure
```
> Add getAccountAssetTransactions tests

- test/module/iroha-cli/CMakeLists.txt
- test/module/iroha-cli/client_test.cpp
Fix client-test regarding mst batches
After feature/mst_batches will be merged into trunk, trunk should be a base branch for this pull request.
> Fix client tests with mst batches

- CMakeLists.txt
- docker/android/Dockerfile
- docker/dependencies/Dockerfile
- docker/develop/Dockerfile
- docs/source/guides/dependencies.rst
- docs/source/guides/libraries/swift_ios.rst
- shared_model/CMakeLists.txt
This PR updates minimum CMake version requirements to 3.11.2. This allows using new features such as FetchContent.
More features, fewer bugs in CMake.
Some users will have to manually install CMake when trying to build iroha.
> Upgrade CMake to version 3.11.4

- libs/crypto/CMakeLists.txt
- libs/crypto/keys_manager.hpp
- libs/crypto/keys_manager_impl.cpp
- libs/crypto/keys_manager_impl.hpp
- test/module/libs/crypto/CMakeLists.txt
- test/module/libs/crypto/keys_manager_test.cpp
- test/system/CMakeLists.txt
- test/system/irohad_test.cpp
Add a test that:
* runs separate independent Iroha instance as our users do
* sends a transaction and awaits its committed status
* sends a query and verifies the query response
Additionally, the implementation of KeysManager was refactored.
Coverage is increased. 
No need to include tx-example.py to CI cycle.
None.
```
cd build
make irohad_test
ctest -R irohad_test --output-on-failure
```
> Add SendTx and SendQuery system tests

- irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
Iroha used to produce something like:
```
[2018-08-28 14:24:40.335785000][th:295648][info] FairMstProcessor Propagate new data[2]
[2018-08-28 14:24:45.339160000][th:295648][info] FairMstProcessor Propagate new data[2]
[2018-08-28 14:24:50.330393000][th:295648][info] FairMstProcessor Propagate new data[2]
[2018-08-28 14:24:55.332114000][th:295648][info] FairMstProcessor Propagate new data[2]
[2018-08-28 14:25:00.328946000][th:295648][info] FairMstProcessor Propagate new data[2]
[2018-08-28 14:25:05.338611000][th:295648][info] FairMstProcessor Propagate new data[2]
[2018-08-28 14:25:10.332539000][th:295648][info] FairMstProcessor Propagate new data[2]
[2018-08-28 14:25:15.331939000][th:295648][info] FairMstProcessor Propagate new data[2]
```
even when there was no propagation. 
This PR …
> Change log order

- test/integration/acceptance/revoke_permission_test.cpp
- test/module/irohad/ordering/ordering_service_test.cpp
Add more debug logs to GrantAndRevoke test case of revoke perms tests.
The reason is that we saw the empty error message when it was not expected to be empty. This bug is rarely reproducible. That is why we added more logs.
> Add more logs to revoke test

- .jenkinsci/debug-build.groovy
This PR fixes branch name that is used for checking against reference Dockerfile. That is due to switching from 'develop' to 'dev' branch temporarily.
Should fix version skew that appeared due to transition to a new base branch ('dev')
None
> Fix docker image version skew

- test/module/irohad/ordering/ordering_service_test.cpp
`GenerateProposalDestructor` test from `OrderingService` suite was unreliable and tied with time and concurrency assumptions. As the Ordering Service soon will be replaced, it was decided to remove the test.
Broken test will not appear again.
None
> Remove the Ordering Service Test

- irohad/multi_sig_transactions/impl/gossip_propagation_strategy.cpp
- shared_model/validators/signable_validator.hpp
`this` capture in `SignableValidator`, since it required in only half of the cases. <s>The second is related to gtest specific issue. That was noticed earlier by @kamilsa </s>
**upd:** seems our current compiler cannot deal with that -_- we need to discuss workarounds
**upd2:** it seems gtest 1.8 isn't compatible for now
clang finishes compilation successfully 
None
> Fix compiling errors on clang

- irohad/simulator/impl/simulator.cpp
- irohad/synchronizer/impl/synchronizer_impl.cpp
- irohad/synchronizer/impl/synchronizer_impl.hpp
- test/module/irohad/synchronizer/synchronizer_test.cpp
- Restrict storage lifetime to callback in simulator and synchronizer. This prevents storage deadlocks, since resources are released before calling `on_next`, which in turn calls subscribers callbacks.
- Refactor `operator|` bind calls and `match` calls to remove null pointers using `boost::get`.
No more deadlocks when storage connection is closed
`boost::get` calls are hard to read, a task will be created to refactor `Result` class.
> Restrict storage lifetime in simulator and synchronizer

- .jenkinsci/artifacts.groovy
- Jenkinsfile
Signed-off-by: Alexey Rodionov <rodionov@soramitsu.co.jp>
Move all our artifacts (bindings, libraries, binaries) to new Nexus-server (nexus.iroha.tech)
Modern artifact storing system
artifacts.soramitsu.co.jp will be removed in the future
> Nexus artifact server

- test/integration/acceptance/set_account_detail_test.cpp
Add more acceptance tests for SetAccountDetail, since some was already added in #1452 
More coverage
None
`test_bin/set_account_detail_test`
> Add more acceptance tests for SetAccountDetail

- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/get_role_permissions_test.cpp
Signed-off-by: Vadim Reutskiy reutskiy@soramitsu.co.jp
Add two tests:
1. For successful query of role permissions for user with GetRoles permission 
2. For unsuccessful query of role permissions for user without GetRoles permission 
GetRolePermissions query is covered by tests
None
Target: get_role_permissions_test
> Add tests for GetRolePermissions query

- test/system/irohad_test.cpp
Signed-off-by: Vadim Reutskiy <reutskiy@soramitsu.co.jp>
Added two tests:
1. Test, which starts Iroha, adds transaction, restarts with --overwrite-ledger flags and checks that there is only one block in blockstorage and Iroha still can add transactions.
2. Test, which starts Iroha, adds transaction, restarts Iroha checks that amount of blocks in blockstorage is the same as before restart and Iroha still can add transactions.
Now system tests can check correctness of restarting Iroha both with keeping blocks in blockstorage and with wiping all data and rewriting ledger from the beginning.
None
Target: irohad_test
> Add test for running Iroha with --overwrite-ledger flag

- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/mutable_storage_impl.hpp
- irohad/ametsuchi/impl/postgres_block_query.cpp
- irohad/ametsuchi/impl/postgres_block_query.hpp
- irohad/ametsuchi/impl/postgres_wsv_query.cpp
- irohad/ametsuchi/impl/postgres_wsv_query.hpp
- irohad/ametsuchi/impl/storage_impl.cpp
- irohad/ametsuchi/impl/storage_impl.hpp
- irohad/ametsuchi/impl/temporary_wsv_impl.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.hpp
- irohad/ametsuchi/storage.hpp
- irohad/main/application.cpp
- irohad/main/application.hpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
Add freeConnections method, which disposes all currently used connections. Due to storage shared pointer not being released in irohad destructor, method has to be manually called in irohad destructor.
No more leftover databases after tests, since they drop without issues now.
Storage shared pointer is still used by some components. It should be verified that all components are destroyed when irohad destructor is called.
> Fix storage connection disposal

- .jenkinsci/debug-build.groovy
- .jenkinsci/selected-branches-coverage.groovy
- Jenkinsfile
- Replace static Jenkins build agents with on-demand ones
- Disable code coverage for all branches but `master`. It consumes a significant amount of time during the build, while coverage metric is not as useful as planned initially.
- Reduce infrastructure monthly bill by executing builds on AWS agents that are started up on-demand and shut down after a certain timeout if no builds are running on it
- Faster builds due to disabled coverage
- Slightly higher latency between "Start build" event sent to Jenkins and actual execution of the build as AWS agent requires some time for initialization. Although, not relevant in case an agent is already up and running
- `ccache` build cache is not available anymore as each agent starts up with a clean hard drive. However, this should not be a …
> Jenkins on-demand AWS agents

- docker/release/entrypoint.sh
- docker/release/wait-for-it.sh
- add wait-for-it.sh script
- modify entrypoint.sh to use wait-for-it.sh
- introduces new variables IROHA_POSTGRES_HOST and IROHA_POSTGRES_PORT
More reliable method to detect if Postgres is ready before running Iroha (which would fail otherwise)
IROHA_POSTGRES_HOST and IROHA_POSTGRES_PORT variables do not override ones defined in config file. In fact, we should manually check that they match. Otherwise, wait-for-it script just exits on timeout without an error. By that time Postgres most probably would be up and ready to accept connections.
But in case IROHA_POSTGRES_HOST is not defined, we just try to run `irohad` command straight off. This may fail as Postgres is not yet running.
As soon as https://soramitsu.atlassian.net/browse/IR-1567 is …
> Wait for Postgres to become ready

- irohad/torii/impl/command_service_impl.cpp
- irohad/torii/processor/impl/transaction_processor_impl.cpp
- test/module/irohad/torii/processor/transaction_processor_test.cpp
Redundant warning was generated in CommandService due to EnoughSignaturesCollectedResponse response, these pr omit that
Less warnings on normal flow
Just run any acceptance test. Before there's a message "CommandService: Found transaction ...", even though the transaction pass the validation. With that pr there's no such warning
> Skip EnoughSig response in processBatch

- docs/source/getting_started/index.rst
Adding a link following the issue #1173
Adding a missing link to instructions on creating multiple Iroha peers: https://github.com/hyperledger/iroha/tree/master/deploy/ansible
Better documentation
None
> Adding a link to documentation

- test/system/irohad_test.cpp
irohad was given 1 second to initialize, if irohad failed to initialized in 1 second, test framework started to send some transactions to not oppened port. Now test wait's for irohad to send "iroha initilized"
test passed
--
> fix irohad_test

- irohad/validation/impl/stateful_validator_impl.cpp
`boost::join` calls were causing longer execution time in stateful validation. Using a `vector` for filtering restores execution time as is was before using `boost::join`.
Normal execution time.
None.
> Fix stateful validator execution time

- irohad/consensus/yac/impl/yac_gate_impl.cpp
- irohad/network/impl/block_loader_service.cpp
- irohad/network/impl/block_loader_service.hpp
- test/module/irohad/network/block_loader_test.cpp
Bug appears, when one of nodes goes down and then tries to synchronize itself with other ones, but at least one commit was accepted during its down state, and new consensus round started. Then, it tried to download block from the last round, but on other peers this block was already substituted by a new one in consensus cache, leading to result that BlockLoader did not give it, taking that node into an infinite loop.
Bug fix makes BlockLoader to look to the BlockStorage after the cache missed.
This bug went away.
No.
> Fix bug with node synchronization

- docker/release/Dockerfile
We now copy `wait-for-it.sh` file, which checks that Postgres is running, to a docker container.
Iroha won't start without Postgres
None
> Copy postgres healthcheck file to docker container

- irohad/ametsuchi/impl/temporary_wsv_impl.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.hpp
- irohad/ametsuchi/temporary_wsv.hpp
- irohad/validation/impl/stateful_validator_impl.cpp
- irohad/validation/stateful_validator_common.hpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/validation/stateful_validator_test.cpp
Move stateful signatures validation to SQL.
1. Reduce the number of database queries. Single query used to perform the required validation.
2. Reduce the number of data fetches. Since signatories are not required to be fetched from database, only a single fetch is done instead of number of signatures.
Increased performance. Execution time of bm_pipeline benchmark on a test machine was 5000ms before, and the changes have brought it down to 4500ms.
More ambiguous error message since a single error type is returned from the database.
> Move signatories validation to SQL

- irohad/main/application.cpp
- irohad/multi_sig_transactions/gossip_propagation_strategy.hpp
- irohad/multi_sig_transactions/impl/gossip_propagation_strategy.cpp
- test/module/irohad/multi_sig_transactions/gossip_propagation_strategy_test.cpp
Before, GossipPropagationStrategy has created threads on each `emitter`. This pr resolves it by adding separate thread as a member field
No redundant threads are created
None
It is not trivial to write test for that fix. This behavior might be observed in a debugger via thread information
> Create thread once at GossipPropagation

- test/fuzzing/CMakeLists.txt
- test/fuzzing/ordering_gate_fuzz.cpp
This pull request adds a fuzzing target for ordering gate.
One more possibility to find bugs and issues in the code.
This code has to be built with mainstream clang (not an apple's one) and currently fuzzing option is not turned on by default - it makes this code hard to support.
Set compiler paths to your local clang binaries.
```
cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++  -DFUZZING=ON ..
make ordering_gate_fuzz
```
Currently this test finds issues pretty quickly and they should be fixed - in a separate task.
> Add fuzzing target for ordering gate

- irohad/synchronizer/impl/synchronizer_impl.cpp
- irohad/validation/chain_validator.hpp
- irohad/validation/impl/chain_validator_impl.cpp
- irohad/validation/impl/chain_validator_impl.hpp
- test/integration/validation/chain_validator_storage_test.cpp
- test/module/irohad/synchronizer/synchronizer_test.cpp
- test/module/irohad/validation/chain_validation_test.cpp
- test/module/irohad/validation/validation_mocks.hpp
Before this change the ChainValidator method validateChain was implicitly used to apply the commits to the main World State, but neither the class, nor the function name, nor its description corresponded to such usage. In this change I tried to put these in accordance.
Improved readability.
I hope there are none.
> Refactor chain validator

- irohad/consensus/CMakeLists.txt
- irohad/consensus/gate_object.hpp
- irohad/consensus/impl/gate_object.cpp
- irohad/consensus/yac/CMakeLists.txt
- irohad/consensus/yac/impl/yac_gate_impl.cpp
- irohad/network/consensus_gate.hpp
- irohad/synchronizer/CMakeLists.txt
- irohad/synchronizer/impl/synchronizer_impl.cpp
- irohad/synchronizer/impl/synchronizer_impl.hpp
- irohad/synchronizer/synchronizer.hpp
- irohad/synchronizer/synchronizer_common.hpp
- test/module/irohad/CMakeLists.txt
- test/module/irohad/consensus/yac/yac_gate_test.cpp
- test/module/irohad/ordering/CMakeLists.txt
- test/module/irohad/ordering/ordering_gate_test.cpp
- test/module/irohad/synchronizer/CMakeLists.txt
- test/module/irohad/synchronizer/synchronizer_test.cpp
- test/module/irohad/torii/processor/transaction_processor_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
This pr fixes SynchronizerImpl to function with YacGateImpl, so it can handle ConsensusGate::GateObject and operate accordingly to the emitted variant.
One more step toward bft consensus
<s>Tests aren't fixed</s>
<s>`AgreementOnNone` isn't properly handled</s>
<s>No decision on behavior of reject cases</s>
> BFT-aware Synchronizer

- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/replay_test.cpp
Adds a test that sends the same transaction (copies are bit-exact) two times and expects that the second transaction should not be processed and committed.
Increased coverage.
The test is disabled now. It should be enabled after IR-1773 and IR-1838.
The test is to be expanded by adding the same cases about MST transactions and states.
```
make replay_test
test_bin/replay_test
```
> A test for basic case of transaction replay attack

- test/integration/acceptance/replay_test.cpp
Commit 1b1966b broke the replay test, because the common constants were moved to a namespace. In this PR I just add the missing namespace using.
Fixed test.
One more line of code to maintain.
> Fix the replay test after `common constants' merging

- test/framework/CMakeLists.txt
- test/framework/integration_framework/fake_peer/fake_peer.cpp
- test/framework/integration_framework/fake_peer/fake_peer.hpp
- test/framework/integration_framework/fake_peer/yac_network_notifier.cpp
- test/framework/integration_framework/fake_peer/yac_network_notifier.hpp
- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/integration_test_framework.hpp
- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/basic_mst_state_propagation.cpp
- test/integration/pipeline/multisig_tx_pipeline_test.cpp
- test/regression/regression_test.cpp
A class for iroha peer simulation. Currently it supports blind agreement on any proposal and interfaces for getting YAC and MST events.
More possible testing scenarios.
To be found.
> ITF: Fake Peer

- irohad/main/CMakeLists.txt
- irohad/main/application.cpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
Add useful mock for tx persistent cache.
Mock is added to test and irohad/application folders for easy access.
Signed-off-by: Fedor Muratov <muratovfyodor@yandex.ru>
> Add mock of persistent cache in:

- test/fuzzing/CMakeLists.txt
- test/fuzzing/block_loader_fixture.hpp
- test/fuzzing/retrieve_block_fuzz.cpp
- test/fuzzing/retrieve_blocks_fuzz.cpp
- test/module/vendor/grpc_mocks.hpp
Fuzzing for block loader endpoints (**retrieveBlock** and **retrieveBlocks**).
Another endpoint is covered by fuzzing.
Hard to support until fuzzing in CI is not ready.
```
cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++  -DFUZZING=ON ..
make retrieve_block_fuzz
make retrieve_blocks_fuzz
```
> Add fuzzing for BlockLoader endpoints

- example/python/batch-example.py
- example/python/blocks-query.py
- example/python/irohalib.py
- example/python/tx-example.py
New Iroha lib in Python gets able to query blocks stream.
Examples `tx-example.py` and `blocks-query.py` are updated.
Up to date examples.
None ?
```
Run:
1. Iroha
2. blocks-query.py
3. tx-example.py
```
> Update tx-example.py and blocks-query.py

- irohad/ametsuchi/impl/postgres_command_executor.cpp
- test/integration/acceptance/CMakeLists.txt
- test/integration/acceptance/set_account_quorum_test.cpp
- test/module/irohad/ametsuchi/postgres_executor_test.cpp
SetAccountQuorum validation rule had inverse logic.
It was not possible to set the quorum less than a number of linked signatories.
The true validation rule is - it is not allowed to set the quorum more than a number of linked signatories.
Fixed validation behavior.
Increased code coverage.
none ?
```
cd build
make set_account_quorum_test
test_bin/set_account_quorum_test
```
> Fix SetAccountQuorum validation rule

- irohad/ordering/impl/on_demand_ordering_service_impl.cpp
- irohad/ordering/impl/on_demand_ordering_service_impl.hpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/ordering/CMakeLists.txt
- test/module/irohad/ordering/on_demand_os_test.cpp
This PR adds replay prevention during proposal generation in on demand ordering service.
Replay prevention
All batches must be checked via cache
> Replay prevention on proposal generation

- irohad/ametsuchi/impl/postgres_block_index.cpp
- irohad/ametsuchi/impl/postgres_block_query.cpp
- irohad/ametsuchi/impl/postgres_block_query.hpp
- irohad/ametsuchi/impl/storage_impl.cpp
- irohad/ametsuchi/tx_cache_response.hpp
- test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
- test/module/irohad/ametsuchi/block_query_test.cpp
Previous implementation of checkTxPresence method used two tables in schema. In this PR those two table were merged into a single one
More clear schema, less methods
None
> Update tx presence method

- example/python/Makefile
- example/python/prepare.sh
Replaced `prepare.sh` with a Makefile.
Makefile is a standard way to generate something. It is also easier to extend and is smarter.
The user needs the `make` program, although it is hard to imagine one not having it.
`make`
We could also use `CMake`, but while the project is not so big it seems an overkill.
> Makefile for python libs example

- irohad/main/irohad.cpp
This is a better implementation of #1776.
The problem is that CI needs to be able to launch `irohad` that will restore the existing state with the same set of flags as that was passed at the first launch.
The new way of launch parameters handling is implemented. All the possible cases is covered.
The new truth table is below:
For a better understanding of changes made in code please take a look at two execution flowcharts (old and new one).
Nothing is changed in already exposed API.
No unexpected behavior is added.
All the combinations of three parameters (presence of blockstore, presence of new genesis_block, presence of overwrite_ledger flag) are covered.
None?
```
cd build
make irohad_test
test_bin/irohad_test
```
> Fix startup flags logic (--genesis_block & --overwrite_ledger)

- irohad/ordering/impl/ordering_gate_transport_grpc.cpp
- test/framework/CMakeLists.txt
- test/framework/integration_framework/fake_peer/fake_peer.cpp
- test/framework/integration_framework/fake_peer/fake_peer.hpp
- test/framework/integration_framework/fake_peer/ordering_gate_network_notifier.cpp
- test/framework/integration_framework/fake_peer/ordering_gate_network_notifier.hpp
- test/framework/integration_framework/fake_peer/ordering_service_network_notifier.cpp
- test/framework/integration_framework/fake_peer/ordering_service_network_notifier.hpp
- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/integration_test_framework.hpp
- test/integration/acceptance/basic_mst_state_propagation.cpp
This patch adds the OS&OG testing facilities to ITF. It is now possible to send these messages to ITF peer & get the ones sent by it to any fake peer.
New feature.
Bugs.
> Ordering service (pre-on-demand version) in ITF & Fake Peer

- irohad/torii/command_client.hpp
- irohad/torii/impl/command_client.cpp
- irohad/torii/impl/command_service_transport_grpc.hpp
- irohad/torii/impl/query_client.cpp
- irohad/torii/query_client.hpp
- irohad/torii/query_service.hpp
- shared_model/schema/endpoint.proto
- test/module/irohad/main/server_runner_test.cpp
To prepare Iroha for backward compatibility, `CommandService` and `QueryService` should be given version tags, `1_0` in this case.
One more step to BC.
Harder to read?
> Renamed Client Services

- irohad/ametsuchi/tx_cache_response.hpp
- irohad/main/application.cpp
- irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
- irohad/multi_sig_transactions/transport/mst_transport_grpc.hpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/multi_sig_transactions/transport_test.cpp
A peer can receive the same MST state from the network more than once.
As the result, sometimes the same transaction was able to be committed multiple times.
Replays on MST state sharing are prevented.
Missing test. (in progress. to be updated soon)
Special test is under development. The pr will be updated soon
> Prevent replay attack on MST state sharing

- irohad/consensus/yac/storage/impl/yac_vote_storage.cpp
[IR-1912](https://soramitsu.atlassian.net/projects/IR/issues/IR-1912)
I stumbled upon this when investigating a [segfault](https://pastebin.com/L0nJZDMc) in `YacProposalStorage`. After this fix the segfault never occurred again.
The change seems very simple: a `find_if` predicate is made to take its argument by constref to avoid copying.
Removed unneeded copying, and somehow fixed segfault (not yet sure about that).
Bugs.
> Nano Fix: YAC vote storage - find proposal predicate takes constref

- irohad/ametsuchi/impl/mutable_storage_impl.cpp
- irohad/ametsuchi/impl/mutable_storage_impl.hpp
- irohad/ametsuchi/impl/postgres_command_executor.cpp
- irohad/ametsuchi/impl/postgres_command_executor.hpp
- irohad/ametsuchi/impl/storage_impl.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.cpp
- irohad/ametsuchi/impl/temporary_wsv_impl.hpp
- irohad/torii/processor/impl/transaction_processor_impl.cpp
- irohad/validation/stateful_validator_common.hpp
- shared_model/interfaces/permissions.hpp
- test/module/iroha-cli/client_test.cpp
- test/module/irohad/ametsuchi/postgres_executor_test.cpp
- test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
- test/module/irohad/simulator/simulator_test.cpp
- test/module/irohad/torii/processor/transaction_processor_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
- test/module/irohad/validation/stateful_validator_test.cpp
Completely removing the stateful error message was a bad idea, because clients now do not have an ability to track down actual query parameters, hidden behind the error code. So, this PR introduces output of query parameters to the log.
More verbose output to developers.
None
`postgres_executor_test` is updated with query parameters checks.
> Stateful Error Response to Log

- irohad/ametsuchi/block_query.hpp
- irohad/ametsuchi/impl/postgres_block_query.cpp
- irohad/ametsuchi/impl/postgres_block_query.hpp
- irohad/ametsuchi/impl/tx_presence_cache_impl.cpp
- irohad/ametsuchi/impl/tx_presence_cache_impl.hpp
- irohad/ametsuchi/tx_presence_cache.hpp
- irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
- irohad/ordering/impl/on_demand_ordering_gate.cpp
- irohad/ordering/impl/on_demand_ordering_service_impl.cpp
- irohad/torii/impl/command_service_impl.cpp
- test/module/irohad/ametsuchi/ametsuchi_mocks.hpp
- test/module/irohad/ametsuchi/block_query_test.cpp
- test/module/irohad/ametsuchi/tx_presence_cache_test.cpp
- test/module/irohad/multi_sig_transactions/transport_test.cpp
- test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
- test/module/irohad/ordering/on_demand_os_test.cpp
- test/module/irohad/torii/torii_service_test.cpp
- Since it is not possible to create block query from storage after it has been dropped, each `getBlockQuery` call should be checked for `nullptr` after call.
- It is also possible to catch an exception when SQL query is executed. `PostgresBlockQuery::checkTxPresence` is refactored with try-catch for this reason.
Less possible segmentation faults and uncaught exceptions.
More checks in code.
It is possible to use `Result` instead of optional in `PostgresBlockQuery::checkTxPresence`, however is will be more difficult to handle it in calling methods.
> Refactor tx presence cache with optional

- shared_model/backend/protobuf/CMakeLists.txt
- shared_model/backend/protobuf/queries/impl/proto_get_account_asset_transactions.cpp
- shared_model/backend/protobuf/queries/impl/proto_get_account_transactions.cpp
- shared_model/backend/protobuf/queries/impl/proto_tx_pagination_meta.cpp
- shared_model/backend/protobuf/queries/proto_get_account_asset_transactions.hpp
- shared_model/backend/protobuf/queries/proto_get_account_transactions.hpp
- shared_model/backend/protobuf/queries/proto_tx_pagination_meta.hpp
- shared_model/interfaces/CMakeLists.txt
- shared_model/interfaces/common_objects/types.hpp
- shared_model/interfaces/queries/get_account_asset_transactions.hpp
- shared_model/interfaces/queries/get_account_transactions.hpp
- shared_model/interfaces/queries/impl/get_account_asset_transactions.cpp
- shared_model/interfaces/queries/impl/get_account_transactions.cpp
- shared_model/interfaces/queries/impl/tx_pagination_meta.cpp
- shared_model/interfaces/queries/tx_pagination_meta.hpp
- shared_model/schema/queries.proto
- shared_model/utils/string_builder.cpp
- shared_model/utils/string_builder.hpp
- shared_model/validators/field_validator.cpp
- shared_model/validators/field_validator.hpp
- test/module/shared_model/validators/field_validator_test.cpp
- test/module/shared_model/validators/validators_fixture.hpp
[IR-20](https://jira.hyperledger.org/projects/IR/issues/IR-20)
This change adds the pagination metadata to some queries that request transaction lists: GetAccountTransactions and GetAccountAssetTransactions. It does not concern GetPendingTransactions as it is expected to be rewritten soon.
A small step towards great feature.
bugs.
When a client requests some sort of transaction list, the request must include pagination metadata. That one _must_ have the page size set  to the maximum amount of transactions the client wants to get at once, and _may_ have the first transaction hash field set to the hash of the transaction, from which the returned list is supposed to start.
> Schema update for queries with lists of transactions

- irohad/main/application.cpp
- irohad/main/impl/block_loader_init.cpp
- shared_model/backend/protobuf/impl/proto_block_factory.cpp
- shared_model/backend/protobuf/proto_block_factory.hpp
- shared_model/validators/CMakeLists.txt
- shared_model/validators/protobuf/proto_block_validator.cpp
- shared_model/validators/protobuf/proto_block_validator.hpp
- test/module/irohad/network/block_loader_test.cpp
- test/module/irohad/simulator/simulator_test.cpp
- test/module/shared_model/backend_proto/proto_block_factory_test.cpp
- test/module/shared_model/validators/CMakeLists.txt
- test/module/shared_model/validators/protobuf/proto_block_validator_test.cpp
After one_of version field was added to Block, it started needing a protocol validation, which would check, if this field is set.
Ill-formed Blocks are not allowed
None.
`proto_block_validator_test` was added.
> Proto Validation for Block

- shared_model/backend/protobuf/commands/impl/proto_add_asset_quantity.cpp
- shared_model/backend/protobuf/commands/impl/proto_add_peer.cpp
- shared_model/backend/protobuf/commands/impl/proto_add_signatory.cpp
- shared_model/backend/protobuf/commands/impl/proto_command.cpp
- shared_model/backend/protobuf/commands/impl/proto_create_account.cpp
- shared_model/backend/protobuf/commands/impl/proto_create_asset.cpp
- shared_model/backend/protobuf/commands/impl/proto_create_role.cpp
- shared_model/backend/protobuf/commands/impl/proto_remove_signatory.cpp
- shared_model/backend/protobuf/commands/impl/proto_subtract_asset_quantity.cpp
- shared_model/backend/protobuf/commands/impl/proto_transfer_asset.cpp
- shared_model/backend/protobuf/commands/proto_add_asset_quantity.hpp
- shared_model/backend/protobuf/commands/proto_add_peer.hpp
- shared_model/backend/protobuf/commands/proto_add_signatory.hpp
- shared_model/backend/protobuf/commands/proto_append_role.hpp
- shared_model/backend/protobuf/commands/proto_create_account.hpp
- shared_model/backend/protobuf/commands/proto_create_asset.hpp
- shared_model/backend/protobuf/commands/proto_create_domain.hpp
- shared_model/backend/protobuf/commands/proto_create_role.hpp
- shared_model/backend/protobuf/commands/proto_detach_role.hpp
- shared_model/backend/protobuf/commands/proto_grant_permission.hpp
- shared_model/backend/protobuf/commands/proto_remove_signatory.hpp
- shared_model/backend/protobuf/commands/proto_revoke_permission.hpp
- shared_model/backend/protobuf/commands/proto_set_account_detail.hpp
- shared_model/backend/protobuf/commands/proto_set_quorum.hpp
- shared_model/backend/protobuf/commands/proto_subtract_asset_quantity.hpp
- shared_model/backend/protobuf/commands/proto_transfer_asset.hpp
Lazy is not needed in a set of shared model objects, so it is getting removed. In this PR, it is removed from Commands.
No Lazy overhead.
None.
> Laziness is removed from Commands

- shared_model/backend/protobuf/common_objects/account.hpp
- shared_model/backend/protobuf/common_objects/account_asset.hpp
- shared_model/backend/protobuf/common_objects/asset.hpp
- shared_model/backend/protobuf/common_objects/domain.hpp
- shared_model/backend/protobuf/common_objects/peer.hpp
- shared_model/backend/protobuf/common_objects/signature.hpp
- shared_model/backend/protobuf/common_objects/trivial_proto.hpp
Signed-off-by: Akvinikym <anarant12@gmail.com>
Lazy is not needed in a set of shared model objects, so it is getting removed. In this PR, it is removed from Common Objects.
No Lazy overhead.
None.
> Laziness is removed from Common Objects

- shared_model/backend/protobuf/batch_meta.hpp
Lazy is not needed in a set of shared model objects, so it is getting removed. In this PR, it is removed from BatchMeta.
No Lazy overhead
None.
> Laziness is removed from BatchMeta

- iroha-cli/impl/query_response_handler.cpp
- irohad/ametsuchi/impl/postgres_block_query.cpp
- irohad/consensus/yac/impl/yac_gate_impl.cpp
- irohad/multi_sig_transactions/transport/impl/mst_transport_grpc.cpp
- irohad/ordering/impl/on_demand_ordering_service_impl.cpp
- irohad/ordering/impl/on_demand_os_server_grpc.cpp
- irohad/torii/impl/command_service_impl.cpp
- irohad/torii/processor/impl/transaction_processor_impl.cpp
- libs/logger/logger.hpp
- shared_model/interfaces/queries/query.hpp
- test/framework/integration_framework/integration_test_framework.cpp
- test/module/shared_model/interface_test.cpp
Previously, user-defined objects were printed into the log via calling their `toString()` method, which is not very efficient. This PR introduces an ability to log such objects directly, and their `toString()` will be called only if level of logging meets the one turned on.
No more additional logging overhead when unnecessary.
None.
> Print user-defined objects to log directly

- shared_model/backend/protobuf/query_responses/impl/proto_account_asset_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_account_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_asset_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_block_error_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_block_query_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_block_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_error_query_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_role_permissions_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_roles_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_signatories_response.cpp
- shared_model/backend/protobuf/query_responses/impl/proto_transaction_response.cpp
- shared_model/backend/protobuf/query_responses/proto_account_asset_response.hpp
- shared_model/backend/protobuf/query_responses/proto_account_detail_response.hpp
- shared_model/backend/protobuf/query_responses/proto_account_response.hpp
- shared_model/backend/protobuf/query_responses/proto_asset_response.hpp
- shared_model/backend/protobuf/query_responses/proto_block_error_response.hpp
- shared_model/backend/protobuf/query_responses/proto_block_query_response.hpp
- shared_model/backend/protobuf/query_responses/proto_block_response.hpp
- shared_model/backend/protobuf/query_responses/proto_concrete_error_query_response.hpp
- shared_model/backend/protobuf/query_responses/proto_error_query_response.hpp
- shared_model/backend/protobuf/query_responses/proto_query_response.hpp
- shared_model/backend/protobuf/query_responses/proto_role_permissions_response.hpp
- shared_model/backend/protobuf/query_responses/proto_roles_response.hpp
- shared_model/backend/protobuf/query_responses/proto_signatories_response.hpp
- shared_model/backend/protobuf/query_responses/proto_transaction_response.hpp
Lazy is not needed in a set of shared model objects, so it is getting removed. In this PR, it is removed from Query Responses.
No Lazy overhead.
None.
> Laziness is removed from Query Responses

- irohad/ordering/impl/ordering_gate_cache/on_demand_cache.cpp
- test/module/irohad/ordering/on_demand_cache_test.cpp
- test/module/shared_model/interface_mocks.hpp
Previously uncommitted transactions cache was removing by reduced hash of transaction batch. However block event emitted to ordering gate returns hashes of transactions. So the fix removes batches from the cache by transaction's hash. So, if any batch in transaction cache contains transaction with given transaction hash, then entire batch with that transaction is removed from the cache
No more duplication warnings
None
on_demand_cache_test with remove function was updated
> Fix uncommitted cache

- irohad/consensus/round.hpp
- irohad/consensus/yac/impl/yac.cpp
- irohad/consensus/yac/impl/yac_gate_impl.cpp
- irohad/consensus/yac/storage/impl/yac_block_storage.cpp
- irohad/main/impl/on_demand_ordering_init.cpp
- irohad/main/impl/on_demand_ordering_init.hpp
- irohad/ordering/impl/on_demand_common.cpp
- irohad/ordering/impl/on_demand_common.hpp
- irohad/ordering/impl/on_demand_ordering_gate.cpp
- irohad/ordering/impl/on_demand_ordering_gate.hpp
- libs/logger/logger.hpp
- test/module/irohad/consensus/yac/yac_gate_test.cpp
- test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
- Ordering gate was generating incorrect reject rounds based on initial stored value. Now it uses the value from observable
- Yac gate was accepting votes and consensus results for old rounds. Now it ignores them
Predictable pipeline behavior
None?
YacGateTest.OlderVote, YacGateTest.OlderCommit, YacGateTest.OlderReject
> Add round check to consensus gate, fix ordering gate round

- test/module/shared_model/CMakeLists.txt
- test/module/shared_model/command_mocks.hpp
- test/module/shared_model/mock_objects_factories/mock_command_factory.cpp
- test/module/shared_model/mock_objects_factories/mock_command_factory.hpp
This PR introduces mocks for commands and a factory, which creates those mocks, so that it will be possible to use them in places, where the actual commands are not needed, such as both ExecutorTest-s.
Less dependencies in future.
None.
> Commands Mocks Factory

- .jenkinsci/debug-build.groovy
- Jenkinsfile
Add fuzzing build process to nightly Iroha builds
increase stability of fuzzing target
Currently it is not possible run tests if fuzzing is enabled, tests newer stops
> Add fuzzing build process to nightly Iroha builds

- irohad/consensus/yac/storage/impl/yac_vote_storage.cpp
- test/framework/integration_framework/fake_peer/fake_peer.cpp
- test/framework/integration_framework/fake_peer/fake_peer.hpp
- test/framework/integration_framework/fake_peer/network/loader_grpc.cpp
- test/framework/integration_framework/fake_peer/network/loader_grpc.hpp
- test/framework/integration_framework/integration_test_framework.cpp
Methods to get observables on fake peer's synchronizer calls.
Additional handles for testing.
bugs.
> ITF: added fake peer synchronizer calls observable getters

- irohad/multi_sig_transactions/impl/mst_processor.cpp
- irohad/multi_sig_transactions/impl/mst_processor_impl.cpp
- irohad/multi_sig_transactions/mst_processor.hpp
- irohad/multi_sig_transactions/mst_processor_impl.hpp
- irohad/multi_sig_transactions/state/impl/mst_state.cpp
- irohad/multi_sig_transactions/state/mst_state.hpp
- irohad/multi_sig_transactions/storage/impl/mst_storage.cpp
- irohad/multi_sig_transactions/storage/impl/mst_storage_impl.cpp
- irohad/multi_sig_transactions/storage/mst_storage.hpp
- irohad/multi_sig_transactions/storage/mst_storage_impl.hpp
- irohad/torii/processor/impl/transaction_processor_impl.cpp
- test/integration/pipeline/multisig_tx_pipeline_test.cpp
- test/module/irohad/multi_sig_transactions/mst_mocks.hpp
- test/module/irohad/multi_sig_transactions/state_test.cpp
- test/module/irohad/multi_sig_transactions/storage_test.cpp
Previously, if batch was pending, and the same batch with **all** signatures comes, it went straight to the PCS. Because of that, the pending one was not removed and in theory could be replayed. Now, the system checks, if the arrived batch does already exist in MST storage, even if it has all signatures.
No more replays possible, and pending storage gets cleaned.
Overhead for unordered_set's `find`.
> Fix MST pending storage

- docs/source/conf.py
Recently I introduced YAML files in docs config here: #1954. Now guess what? 
When you try to run build of docs in Japanese or Dutch here is what you got:
```
Running Sphinx v1.8.2
loading translations [ja]... done
making output directory...
WARNING: The config value `locale_dirs' has type `str', defaults to `list'.
```
This warning actually is an error — as the docs cannot be built in target language. This had to be merged, otherwise people cannot see localized_docs.
Contributors would be able to see docs in their language.
None
Go to https://github.com/soramitsu/localized_docs, follow README.md and try to build Japanese docs in folder docs/ja. You won't see any Japanese text.
Now if you update .gitmodule file with this branch (fix/docs-build) you will see this is a solution.
> Fix build of multi language docs

- irohad/main/impl/on_demand_ordering_init.cpp
- schema/mst.proto
- test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
Fix some compilation warnings for mainstream clang (tested with 7.0 on MacOS)
Code clean. Also warnings in postgres_query_executor_test result in compilation error due to -WError option.
Some warnings are still present, in old model and in soci. Not worth to deal with them at the moment. Also to build a system test you still have to update boost to 1.69.
> Fix clang build warnings

- irohad/main/impl/on_demand_ordering_init.cpp
- irohad/main/impl/on_demand_ordering_init.hpp
- irohad/ordering/impl/on_demand_connection_manager.cpp
- irohad/ordering/impl/on_demand_connection_manager.hpp
- irohad/ordering/impl/on_demand_ordering_gate.cpp
- irohad/ordering/impl/on_demand_ordering_gate.hpp
Pull request fixes couple of memory leaks on irohad shutdown by calling unsubscribe() in destructors of several classes.
Clean output of leak sanitizer, Irohad destructor is called now.
None.
> Fix memory leaks on irohad shutdown

- docs/source/api/queries.rst
- irohad/ametsuchi/impl/postgres_query_executor.cpp
- irohad/ametsuchi/impl/postgres_query_executor.hpp
- test/integration/acceptance/get_transactions_test.cpp
- test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
[IR-135](https://jira.hyperledger.org/browse/IR-135)
GetTransactions query returned list of only those transactions, which hashes were correct and the user had a permission to view them. This behaviour was considered incorrect, so now this query is going to return a stateful error, if at least one of the hashes does not meet the described requirement.
Correct behaviour of the query.
Less usability?
> Fix GetTransactions query behaviour

- irohad/torii/impl/command_service_transport_grpc.cpp
Pull request replaces static local variable in to a generic local one in status streaming handler to prevent races on it (actually, initialisation by itself is safe but % operator is not).
Clients can now perform streaming status requests without unknown status issue (IR-76).
None.
Correctness of fix was tested with help of thread sanitizer. Also instance of irohad is now able to survive under load of 4 clients bombarding it with transactions and streaming status requests on it for at least 30 minutes.
> Fix thread safe issue in status streaming

- irohad/ametsuchi/impl/postgres_query_executor.cpp
- irohad/ametsuchi/impl/postgres_query_executor.hpp
- test/module/irohad/ametsuchi/postgres_query_executor_test.cpp
[IR-136](https://jira.hyperledger.org/browse/IR-136)
Those queries behaved incorrect in case invalid account_id or asset_id was supplied, leading to a success, but empty result in such a case. This PR adds a "fallback" check, which can deduce it and return a correct stateful error.
Correct behaviour of the queries.
Another DB check, which is though executed only in one specific case and does not touch success or another error ones.
> Fix GetAccountTransactions and GetAccountAssetTransactions behaviour

- docs/source/api/queries.rst
Checked the queries for being up-to-date. Seems better now + minor changes on appearance.
Queries are correctly documented
Something might be missed but at the moment looks good.
> Checked and fixed query documentation

- irohad/main/application.cpp
Before this change irohad would output the well-known `~~| COMMIT =^._.^= |~~` message even if no commit was made. This change adds the corresponding messages for other synchronization outcomes that follow the same style.
The logs give better understanding on what is going on. More ASCII smileys in logs.
We will less often see the beloved cat smiley (although in inappropriate moments).
> More precise sync outcome logging in irohad

- libs/common/byteutils.hpp
- test/module/libs/converter/string_converter_test.cpp
Fix hexstringToBytestring method ignoring the failure to parse the whole byte.
Parsing "au" would result in failure instead of value "10".
More correct behavior of the method
None
StringConverterTest.InvalidHexToBinary
> Fix hexstringToBytestring method

- iroha-cli/interactive/impl/interactive_status_cli.cpp
- irohad/model/converters/impl/pb_query_factory.cpp
- irohad/model/converters/impl/pb_transaction_factory.cpp
- libs/common/blob.hpp
- libs/common/byteutils.hpp
- libs/common/hexutils.hpp
Now iroha-cli can send transactions and queries with valid signatures.
Working iroha-cli.
To be discovered.
1. run irohad
2. run iroha-cli
3. send some transaction to iroha (e.g. create asset tx)
> Fix Query & Tx signer in iroha-cli

- irohad/main/irohad.cpp
Make genesis block error message more user friendly. 
Users were seeing "impossible" message in case of incompatibility of blockstore and ledger versions.
No more scary messages.
None ?
> Make genesis block error message more user friendly

- test/integration/acceptance/replay_test.cpp
Enable ordering gate replay test.
Increased test coverage.
Need to improve ITF to exclude exception expectation.
```replay_test```
> Enable replay test

- .jenkinsci/docker-pull-or-build.groovy
- test/fuzzing/retrieve_blocks_fuzz.cpp
- test/fuzzing/status_fuzz.cpp
- test/fuzzing/torii_fuzz.cpp
This pull request adds two fixes: one for docker hub image upload, another fixes build process of fuzzing.
Working upload to docker hub and build process of fuzzing.
We have to merge merge commit back to dev.
> Iroha v1.0 RC2 hotfix: upload to Dockerhub

- test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.cpp
- test/integration/acceptance/fake_peer_example_test.cpp
A test example for new on-demand-os functionality in ITF Fake Peers.
A test example and a proof of work.
Please see `fake_peer_example_test`.
> ITF: fake peer on demand OS usage example

- test/integration/acceptance/acceptance_fixture.hpp
- test/integration/acceptance/add_signatory_test.cpp
- test/integration/acceptance/create_account_test.cpp
- test/integration/acceptance/get_account_test.cpp
- test/integration/acceptance/remove_signatory_test.cpp
- test/integration/acceptance/replay_test.cpp
- test/integration/acceptance/set_account_quorum_test.cpp
- test/integration/acceptance/transfer_asset_test.cpp
The same macro for checking transactions quantity in response was defined in several places.
Now it is defined in acceptance fixture header.
Reduced code duplication.
Still a macro, but we have agreed to use it for the purpose.
```
add_signatory_test
create_account_test
get_account_test
remove_signatory_test
set_account_quorum_test
transfer_asset_test
```
> Add CHECK_TXS macro to acceptance fixture. Reduce code duplication

- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/integration_test_framework.hpp
- test/integration/acceptance/fake_peer_example_test.cpp
I stumbled upon a race condition when the ITF was run and started sending out votes but the Fake Peers were not yet assigned a proper behaviour to react to them. Overcoming that seems impossible without separating genesis block generation from ITF starting to different external interface functions. While doing that I could also rework the interface of Fake Peers addition to the ITF without `future`s, because we now can initialize ITF main peer's key without starting ITF and assigning the genesis block.
Easier and more granular Fake Peer initialization.
Two ITF functions got exposed. One of them `initPipeline` may be not very clear for the users that do not know the guts of the ITF, but I kept it as is, because some existing code relies on it.  
Please see `fake_peer_example_test`. …
> Refactored ITF fake peer initialization

- .jenkinsci/debug-build.groovy
- .jenkinsci/docker-pull-or-build.groovy
- .jenkinsci/doxygen.groovy
- .jenkinsci/linux-post-step.groovy
- .jenkinsci/release-build.groovy
- Jenkinsfile
Delete all "dev" branch mentions in  jenkins
We have less code 
As all refactoring.
> Clean "dev" back to "develop"

- irohad/main/application.cpp
- irohad/main/application.hpp
- irohad/torii/impl/command_service_transport_grpc.cpp
- irohad/torii/impl/command_service_transport_grpc.hpp
- test/module/irohad/torii/torii_transport_command_test.cpp
1. Consensus events now are delivered to all subscribers (TransportCommandService and Synchronizer)
2. Fixed non-graceful shutdown of tx status stream.
The first issue may lead to hang of client application in case when no events were emitted in the network.
Correctness and stability improved.
?
```torii_transport_command_test```
Thanks to @lebdron !
> Fix tx status streaming

- irohad/main/application.cpp
- irohad/main/application.hpp
- irohad/torii/impl/command_service_transport_grpc.cpp
- irohad/torii/impl/command_service_transport_grpc.hpp
- irohad/validation/impl/stateful_validator_impl.cpp
- test/module/irohad/torii/torii_transport_command_test.cpp
- test/module/irohad/validation/stateful_validator_test.cpp
This pr will be a part of RC2 hotfix release.
The #2033 should be merged before this pr. Then this pr has to be rebased to master.
When an atomic batch arrived with one stateful valid and one stateful invalid transaction, only one tx's hash was saved to block as rejected (stateful invalid).
The second tx (stateful valid) was not saved as rejected too.
Correct operating.
The area for improvements is initialization of fail reason for valid transactions which are within the same atomic batch as a tranasction that did not pass stateful validation. 
```
stateful_validator_test
```
> Fix saving rejected txs hashes for failed atomic batches

- libs/logger/CMakeLists.txt
- libs/logger/logger.cpp
- libs/logger/logger.hpp
- libs/logger/logger_manager.cpp
- libs/logger/logger_manager.hpp
- libs/logger/logger_spdlog.cpp
- libs/logger/logger_spdlog.hpp
- test/module/irohad/logger/CMakeLists.txt
- test/module/irohad/logger/logger_test.cpp
[IR-97](https://jira.hyperledger.org/browse/IR-97), [IR-99](https://jira.hyperledger.org/browse/IR-99), [IR-140](https://jira.hyperledger.org/browse/IR-140)
Main classes of a new logger implementation that ...
... supports tree config structure and hides spdlog library.
Loggers can be created with and without a tree config. Project components should pass children of their loggers to their sub-components. Child loggers get the settings from their parents, optionally overridden if a tree config was used.
Please note that this is the first step towards the working new logger, and the project is not yet using it, so it is not expected to compile successfully.
> New logger implementation part 1: main classes

- irohad/main/application.cpp
- irohad/main/application.hpp
- irohad/main/impl/on_demand_ordering_init.cpp
- irohad/main/impl/on_demand_ordering_init.hpp
- irohad/ordering/impl/on_demand_ordering_gate.cpp
- irohad/ordering/impl/on_demand_os_client_grpc.cpp
- irohad/ordering/impl/on_demand_os_client_grpc.hpp
- irohad/torii/impl/command_service_impl.cpp
- irohad/torii/impl/command_service_transport_grpc.cpp
- irohad/torii/impl/command_service_transport_grpc.hpp
- irohad/validation/impl/stateful_validator_impl.cpp
- shared_model/backend/protobuf/proto_transport_factory.hpp
- shared_model/interfaces/iroha_internal/transaction_batch_factory_impl.cpp
- shared_model/interfaces/iroha_internal/transaction_batch_factory_impl.hpp
- shared_model/validators/CMakeLists.txt
- shared_model/validators/proposal_validator.hpp
- shared_model/validators/protobuf/proto_proposal_validator.cpp
- shared_model/validators/protobuf/proto_proposal_validator.hpp
- shared_model/validators/transaction_batch_validator.cpp
- shared_model/validators/transaction_batch_validator.hpp
- shared_model/validators/transactions_collection/transactions_collection_validator.cpp
- test/module/irohad/ordering/on_demand_os_client_grpc_test.cpp
- test/module/irohad/torii/torii_mocks.hpp
- test/module/irohad/torii/torii_transport_command_test.cpp
- test/module/irohad/validation/stateful_validator_test.cpp
- test/module/shared_model/validators/CMakeLists.txt
- test/module/shared_model/validators/proposal_validator_test.cpp
Fix tx status streaming (#2033)
1. Consensus events now are delivered to all subscribers (TransportCommandService and Synchronizer)
2. Fixed non-graceful shutdown of tx status stream.
The first issue may lead to hang of client application in case when no events were emitted in the network.
Fix saving rejected txs hashes for failed atomic batches (#2043)
When an atomic batch arrived with one stateful valid and one stateful invalid transaction, only one tx's hash was saved to block as rejected (stateful invalid).
The second tx (stateful valid) was not saved as rejected too.
Fix proposal validation and prevent resending of incomplete batches (#2044)
Create standalone batch validator.
Add and integrate proto proposal validator.
Prevent …
> Hotfix for segfault and atomic batches

- test/framework/integration_framework/fake_peer/behaviour/honest.cpp
- test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.cpp
- test/framework/integration_framework/fake_peer/proposal_storage.cpp
- test/framework/integration_framework/fake_peer/proposal_storage.hpp
- test/framework/integration_framework/fake_peer/types.hpp
This change makes the Proposal Storage of ITF Fake Peers thread-safe. It is necessary due to the shared usage of these objects.
Bug fixed.
Synchronization slows down execution.
> Fixed thread safety in ITF Fake Peer proposal storage

- docker/dependencies/Dockerfile
- docker/develop/Dockerfile
@bakhtin, @kogeler, please add the dependency to the mac CI environment.
Iroha crypto requires sha3_512 algo.
Python that is older than 3.6 does not have its built-in support.
Additional dependency solves the problem.
Python 3.x where x < 6 is supported
BTF will be enabled on CI.
> Python sha3 dependency to docker

- irohad/main/CMakeLists.txt
- irohad/main/application.cpp
- irohad/main/application.hpp
- irohad/main/impl/block_loader_init.cpp
- irohad/main/impl/block_loader_init.hpp
- irohad/main/impl/consensus_init.cpp
- irohad/main/impl/consensus_init.hpp
- irohad/main/impl/on_demand_ordering_init.cpp
- irohad/main/impl/on_demand_ordering_init.hpp
- irohad/main/impl/ordering_init.cpp
- irohad/main/impl/ordering_init.hpp
- irohad/main/impl/raw_block_loader.cpp
- irohad/main/irohad.cpp
- irohad/main/raw_block_loader.hpp
- irohad/main/server_runner.cpp
- irohad/main/server_runner.hpp
This is a part of new logger integration to irohad. As the complete integration patch is too big for a single PR (+743 -462), it is split in three parts (#2050, #2051, #2052) according to the source code directory structure. This PR includes changes made to `irohad/main`. You can use the unified patch 496b2e9d0 (which was exactly equal to these three PRs put together when they were opened) to build Irohad with the new logger.
One more step towards the new logger.
> New logger integration to irohad: part 2

- irohad/torii/impl/command_service_impl.cpp
- irohad/torii/impl/command_service_transport_grpc.cpp
In some cases, the transaction status stream may not end in 10 seconds even if a final status (e.g. "committed") was already reported.
That might happen when there are no transactions committed in the network and the delay between consensus rounds was increased up to 5 seconds.
The status stream gets forced to end in the case when tx status is not updated during two consensus rounds.
Clients that expect immediate stream end after a final tx status receiving would not suffer from redundant delay.
The solution is not elegant enough, because we do a kind of synchronization on a local variable. 
There is no data race because we do the processing in the same thread.
The gist is a repro script - …
> Fix Status Stream Performance Degradation

- irohad/ametsuchi/impl/peer_query_wsv.cpp
- irohad/ametsuchi/impl/storage_impl.cpp
A quite dirty fix of deadlock occurring when one thread holding a `soci` connection calls some method of `StorageImpl` that needs to acquire a lock, and another thread calling `StorageImpl::dropStorage()` that acquires that lock exclusively first, and then waits for the connections to free.
Quick fix.
The code became less thread safe. But keeping in mind that we provide no thread safety using `soci` at all, that seems not a big problem.
Incapsulate shared mutexes with `soci` sessions in the  classes that use them (please see [IR-284](https://jira.hyperledger.org/browse/IR-284)).
> Storage: fixed drop deadlock

- test/framework/integration_framework/fake_peer/behaviour/behaviour.hpp
- test/framework/integration_framework/fake_peer/behaviour/empty.cpp
- test/framework/integration_framework/fake_peer/behaviour/empty.hpp
- test/framework/integration_framework/fake_peer/behaviour/honest.cpp
- test/framework/integration_framework/fake_peer/behaviour/honest.hpp
- test/framework/integration_framework/fake_peer/block_storage.cpp
- test/framework/integration_framework/fake_peer/block_storage.hpp
- test/framework/integration_framework/fake_peer/fake_peer.cpp
- test/framework/integration_framework/fake_peer/fake_peer.hpp
- test/framework/integration_framework/fake_peer/network/mst_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/mst_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/ordering_gate_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/ordering_gate_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/ordering_service_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/ordering_service_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/yac_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/yac_network_notifier.hpp
- test/framework/integration_framework/fake_peer/types.hpp
- test/integration/acceptance/fake_peer_example_test.cpp
During the review of the fake peers trunk, there arose an issue regarding using aliases. Together with @lebdron, @muratovv and @luckychess we came to a consensus of not hiding top-level type modifiers like `const`, `&`, `*` and smart pointers behind aliases, and also not to alias a type with no templates. The only exception is using an alias as a business logic type.
Standardized approach to using aliases.
As for me, the code has got less readable due to a lot of long and nested types being exposed distract from the higher-level picture.
> ITF fake peer: applying new aliasing rules

- cmake/Modules/Findsoci.cmake
- irohad/main/application.cpp
- irohad/main/application.hpp
- irohad/main/impl/consensus_init.cpp
- irohad/main/impl/consensus_init.hpp
Fix a mem leak, that could not lead to a linear increase of memory consumption.
Less leaks.
None?
valgrind irohad
you have to use gcc + valgrind on Ubuntu-like linux (not bsd), other configurations are poorly supported by valgrind
> Fix Memory Leak in irohad

- cmake/Modules/Findsoci.cmake
- irohad/main/impl/consensus_init.hpp
- irohad/torii/impl/status_bus_impl.cpp
- irohad/torii/impl/status_bus_impl.hpp
Fix the rest of memory leaks in irohad.
Clean valgrind report.
?
valgrind irohad (under Ubuntu-like environment with GNU compiler)
```diff
==15232== LEAK SUMMARY:
+==15232==    definitely lost: 0 bytes in 0 blocks
+==15232==    indirectly lost: 0 bytes in 0 blocks
+==15232==      possibly lost: 0 bytes in 0 blocks
==15232==    still reachable: 176,875 bytes in 1,787 blocks
==15232==         suppressed: 0 bytes in 0 blocks
```
Thanks to @lebdron!
> Fix the rest of memory leaks

- irohad/torii/impl/command_service_impl.cpp
- irohad/torii/processor/impl/transaction_processor_impl.cpp
- irohad/torii/processor/transaction_processor_impl.hpp
- shared_model/backend/protobuf/transaction_responses/proto_concrete_tx_response.hpp
- shared_model/interfaces/transaction_responses/rejected_tx_response.hpp
- shared_model/interfaces/transaction_responses/tx_response.hpp
- shared_model/interfaces/transaction_responses/tx_response_variant.hpp
- test/integration/acceptance/revoke_permission_test.cpp
- test/integration/acceptance/set_account_quorum_test.cpp
- test/module/irohad/torii/processor/transaction_processor_test.cpp
Add processing of rejected transactions to transaction processor
Rename `shared_model::interface::RejectTxResponse` to `shared_model::interface::RejectedTxResponse` for consistency
Rejected status is emitted for rejected transactions in transaction processor
None?
TransactionProcessorTest.TransactionProcessorInvalidTxsTest
> Fix rejected status emitting

- docs/source/api/commands.rst
Signed-off-by: neewy <n.yushkevich@hotmail.com>
Adding important details about AddPeer command
Updated docs
None
> Add info about peer public key validation

- test/load/Dockerfile
- test/load/README.md
- test/load/config.env
- test/load/docker-compose.yml
- test/load/locustfile-performance.py
- test/load/locustfile.py
- test/load/update-env.py
Performance test that sends a transaction using asynchronous API and waits until the final status - committed or rejected - is received from the status stream.
[README.md](https://github.com/lebdron/iroha/blob/7426dc869654076b2d8c37cd74d4add6d9ffde9f/test/load/README.md)
>Specify locustfile in `LOCUSTFILE_PATH` in Compose file
> Add performance test based on locust.io

- deploy/ansible/roles/iroha-docker/tasks/deploy.yml
- deploy/ansible/roles/iroha-docker/templates/docker-compose.yml.j2
- change how Docker network is created. Split down a step into two: depending on whether `overlay_network` variable is set to `true` or `false`. Also add network removal step as it might have interfered with different `overlay_network` modes.
- fix docker-compose.yml template not using network name variable but hardcoded value instead
less buggy deployment scripts
None
> Fix Ansible deployment scripts

- shared_model/validators/transaction_validator.hpp
Pull request fixes data race in CommandValidatorVisitor.
One issue less.
It's still possible to revive this data race (a bit harder since I disabled copy constructor for CommandValidatorVisitor but not impossible).
> Prevent CommandValidatorVisitor objects from copying

- test/integration/acceptance/add_asset_qty_test.cpp
- test/integration/acceptance/add_signatory_test.cpp
- test/integration/acceptance/create_account_test.cpp
- test/integration/acceptance/create_asset_test.cpp
- test/integration/acceptance/create_domain_test.cpp
- test/integration/acceptance/create_role_test.cpp
- test/integration/acceptance/get_account_asset_txs_test.cpp
- test/integration/acceptance/get_account_assets_test.cpp
- test/integration/acceptance/get_account_test.cpp
- test/integration/acceptance/get_asset_info_test.cpp
- test/integration/acceptance/get_role_permissions_test.cpp
- test/integration/acceptance/get_roles_test.cpp
- test/integration/acceptance/get_transactions_test.cpp
- test/integration/acceptance/grant_permission_test.cpp
- test/integration/acceptance/invalid_fields_test.cpp
- test/integration/acceptance/queries_acceptance_test.cpp
- test/integration/acceptance/query_permission_common_tests.cpp
- test/integration/acceptance/query_test.cpp
- test/integration/acceptance/remove_signatory_test.cpp
- test/integration/acceptance/revoke_permission_test.cpp
- test/integration/acceptance/set_account_detail_test.cpp
- test/integration/acceptance/set_account_quorum_test.cpp
- test/integration/acceptance/subtract_asset_qty_test.cpp
- test/integration/acceptance/transfer_asset_test.cpp
- test/integration/acceptance/tx_acceptance_test.cpp
This change adds comments to some integration tests that suggest rewriting or removing them.
It will help us to reach consensus and rework these tests in the future.
If we misinterpret some test scopes, we may unintentionally cause lowering the test coverage.
Read the tests, read the comments, agree silently or argue noticeably.
Design new test coverage from scratch.
> Comments on reworking integration tests

- test/load/Dockerfile
Yesterday, the team of ZMQ released their new version of wheel: https://pypi.org/project/pyzmq/#history 
Unfortunately it does not build, so I had to fix the version to the latest known working version, which is 17.1.2:
Now locust image can build!
None
`docker build -t iroha-locust .`
> Fix version of pyzmq

- irohad/torii/impl/command_service_impl.cpp
- irohad/torii/impl/command_service_impl.hpp
Fix one more data race due to forgotten _unsubscribe_ call.
One data race less.
None.
Better solution is on a way in https://github.com/hyperledger/iroha/pull/2120.
> One more unsubscribe fix

- test/module/libs/common/CMakeLists.txt
- test/module/libs/common/combine_latest_until_first_completed_test.cpp
Three test cases:
- merge 3 observables, one limited
- merge 4, 2 limited
- merge 2 observables 2 times, then merge the results. Each pair has its limited observable.
New operator tested.
> Test for new RX operator combine_latest_until_first_completed

- iroha-cli/main.cpp
- irohad/main/CMakeLists.txt
- irohad/main/iroha_conf_loader.cpp
- irohad/main/irohad.cpp
- irohad/model/sha3_hash.cpp
- libs/logger/logger_spdlog.cpp
- libs/logger/logger_spdlog.hpp
- test/framework/test_logger.cpp
- test/system/irohad_test.cpp
In spdlog one cannot create two loggers with the same tag. But in the logger manager, loggers are created with lock-free compare-exchange method, which implies multiple logger instances creation. This fix makes them reuse the `spdlog::logger` objects with the `spdlog::get` library thread-safe function.
Also, an initialization race fixed for `logger::kDefaultLogPatterns` and rapidjson lib to iroha_conf_loader.
Fixed a race leading to crash.
> New logger: fixed creation race

- irohad/ametsuchi/impl/storage_impl.cpp
- test/module/irohad/ametsuchi/ametsuchi_fixture.hpp
- test/module/irohad/ametsuchi/ametsuchi_test.cpp
- Add rollback before TemporaryWsv creation to prevent a deadlock in reject case, if a block was prepared before voting
- Add hash index for transaction status table to prevent sequential scan on each query
Improved performance
One more query in the pipeline, hash index is not WAL logged
PreparedBlockTest.TemporaryWsvUnlocks
Use btree instead of hash index
> RC4 Hotfix 1 - TemporaryWsv deadlock, checkTxPresence performance

- shared_model/backend/protobuf/queries/impl/proto_query.cpp
Avoid creation of redundant proto query object.
Reduced memory consumption.
https://gist.github.com/igor-egorov/bcb3302997b799160c603ac30245189b
> Decrease quantity of allocated proto query objects

- CONTRIBUTING.md
- deploy/ansible/roles/iroha-docker/README.md
- docs/source/conf.py
- docs/source/contribution/index.rst
- docs/source/guides/deployment.rst
- docs/source/requirements.txt
We are fixing the docs so .md's from the repo could be integrated into ReadTheDocs. 
Current PR is making it work and also adds one of such files into Contributing section. 
1. Less outdated docs - as soon as .md's change docs will change accordingly. 
2. Easy to put existing md docs into ReadTheDocs
Not everything transfers decently from md to rst. Though, when such files are used in docs, one can easily check the way it looks. 
In short, 100% pretty docs VS. Updated docs
Docs can be included directly into the documentation files like this: 
`.. mdinclude:: ../../../CONTRIBUTING.md`
Transfering such files manually from .md to .rst: easy to miss something and very time-consuming
> Markdown to RST docs configuration

- irohad/synchronizer/impl/synchronizer_impl.cpp
- test/module/irohad/synchronizer/synchronizer_test.cpp
Pass top round from synchronizer in case a chain with multiple blocks higher than current round was downloaded.
Nodes retrieve proposal and vote in correct round after synchronization.
None
SynchronizerTest.ValidWhenValidChainMultipleBlocks
> Fix round number in SynchronizationEvent

- docs/source/guides/index.rst
- docs/source/guides/sec-install.rst
Added tips to Read the Docs for securing Iroha installation ranging from physical security to logging. The guide itself is more general and aimed at meeting obvious yet necessary requirements.
The guide helps administrators to avoid possible security problems that are not directly related to Iroha.
None
> Documentation for Iroha installation security tips

- docs/source/guides/configuration.rst
- irohad/main/iroha_conf_loader.cpp
- libs/logger/logger_manager.cpp
- libs/logger/logger_spdlog.cpp
- libs/logger/logger_spdlog.hpp
Fixes:
- child config overrides only the patterns specified in it, while the unspecified are taken from parent config.
- log message contains the verbosity of message, not the logger.
- the default patterns are used in root logger only if there is no patterns specification for it.
- verbosity padding increased to fit `warning` in default pattern.
Logger behaves as expected.
> Llogger: fixed patterns

- irohad/consensus/yac/impl/yac.cpp
- irohad/consensus/yac/storage/impl/yac_vote_storage.cpp
- irohad/consensus/yac/storage/yac_vote_storage.hpp
- irohad/consensus/yac/yac.hpp
- test/module/irohad/consensus/yac/CMakeLists.txt
- test/module/irohad/consensus/yac/yac_simple_cold_case_test.cpp
- test/module/irohad/consensus/yac/yac_synchronization_test.cpp
- test/module/irohad/consensus/yac/yac_test_util.hpp
Add fix for direct propagation in Yac. If a peer sends a vote for the old round we will share last finalized state.
Fix of synchronization in some cases.
No so elegant solution: YAC checks stateless invariants inside functions, vote storage responsibility is increased.
> Add fix for commit direct propagation

- irohad/main/application.cpp
- irohad/main/impl/on_demand_ordering_init.cpp
- irohad/main/impl/on_demand_ordering_init.hpp
- irohad/ordering/impl/on_demand_connection_manager.cpp
- irohad/ordering/impl/on_demand_connection_manager.hpp
- irohad/ordering/impl/on_demand_ordering_gate.cpp
- irohad/ordering/impl/on_demand_ordering_gate.hpp
- irohad/ordering/impl/on_demand_ordering_service_impl.cpp
- irohad/ordering/impl/on_demand_ordering_service_impl.hpp
- irohad/ordering/impl/on_demand_os_client_grpc.cpp
- irohad/ordering/impl/on_demand_os_client_grpc.hpp
- irohad/ordering/impl/on_demand_os_server_grpc.cpp
- irohad/ordering/on_demand_os_transport.hpp
- schema/ordering.proto
- test/module/irohad/ordering/mock_on_demand_os_notification.hpp
- test/module/irohad/ordering/on_demand_connection_manager_test.cpp
- test/module/irohad/ordering/on_demand_ordering_gate_test.cpp
- test/module/irohad/ordering/on_demand_os_client_grpc_test.cpp
- test/module/irohad/ordering/on_demand_os_server_grpc_test.cpp
- test/module/irohad/ordering/on_demand_os_test.cpp
- test/module/irohad/ordering/ordering_mocks.hpp
Use two queues in ordering service for transactions, one for current reject round, and another for future reject and commit rounds.
Less memory usage in case the ordering service is used for multiple rounds.
Two proposals are stored for next rounds instead of one.
> Refactor ordering service queues

- irohad/torii/impl/command_service_impl.cpp
- irohad/torii/impl/command_service_impl.hpp
- test/module/irohad/torii/CMakeLists.txt
- test/module/irohad/torii/command_service_test.cpp
- test/module/shared_model/interface_mocks.hpp
Signed-off-by: Fedor Muratov <muratovfyodor@yandex.ru>
Add fix for status stream initialization. If runtime cache doesn't contain any value we are going to check the persistent cache for the value.
Fix misleading behavior.
Possible to improve tests.
> * Add checking of persistent cache on start status stream

- test/module/irohad/consensus/yac/mock_yac_crypto_provider.hpp
- test/module/irohad/consensus/yac/yac_test_util.hpp
This change brings the keys in tests to a consistent padding scheme, which is necessary because keys generated in various ways can finally be compared somewhere. And when a public key occasionally gets checked by field validator, it must have a fixed length, so it is better to choose a padding scheme which makes keys of the required length.
Tests fixed. Padding done in single place.
Longer keys are harder to read.
> Fix key padding in tests

- irohad/ordering/impl/on_demand_ordering_gate.hpp
- test/framework/integration_framework/iroha_instance.cpp
This change fixes the cause of complier warnings about member initialization order not matching member declaration order like this:
```
In file included from /opt/iroha/test/framework/integration_framework/iroha_instance.cpp:6:0:
/opt/iroha/test/framework/integration_framework/iroha_instance.hpp: In constructor 'integration_framework::IrohaInstance::IrohaInstance(bool, const string&, const string&, size_t, size_t, logger::LoggerManagerTreePtr, logger::LoggerPtr, const boost::optional<std::__cxx11::basic_string<char> >&)':
/opt/iroha/test/framework/integration_framework/iroha_instance.hpp:84:18: warning: 'integration_framework::IrohaInstance::stale_stream_max_rounds_' will be initialized after [-Wreorder]
const size_t stale_stream_max_rounds_;
^ …
```
> Fix member init order warning

- irohad/torii/impl/command_service_impl.cpp
- test/module/irohad/torii/command_service_test.cpp
Signed-off-by: Fedor Muratov <muratovfyodor@yandex.ru>
Fix bug when not committed/rejected transaction will not pass to Iroha's pipeline because it is a "replay".
Add fix for the problem. The idea of the fix to check only final statuses in the ram cache in command service. If there is a final status we will decline further checking of the transaction. Also, thanks @lebdron for cooperation in founding the bug.
Lack of tests. I hope we will discuss with reviewers about how to write the correct test for the situation.
> Fix race bug in command service

- irohad/consensus/yac/impl/yac_gate_impl.cpp
- irohad/ordering/CMakeLists.txt
- irohad/ordering/impl/on_demand_ordering_service_impl.hpp
- irohad/simulator/impl/simulator.cpp
- test/module/irohad/consensus/yac/yac_gate_test.cpp
- test/module/irohad/ordering/on_demand_os_test.cpp
- Fix duplicate transactions in proposals due to missing `BatchHashEquality` comparator
- Fix block leaks in Simulator and YacGate
- No duplicate transactions in proposals
- Less memory usage
None
YacGateTest.CacheReleased, OnDemandOsTest.DuplicateTxTest
> Fix hash set usage in OS. Fix block leaks in YacGate and Simulator

- docs/source/guides/configuration.rst
Added descriptions of the following params:
- mst_expiration_time
- max_rounds_delay
- stale_stream_max_rounds
doc coverage
> Docs for new config file params

- irohad/ametsuchi/impl/flat_file_block_storage.cpp
- irohad/ametsuchi/impl/flat_file_block_storage.hpp
Remove redundant definition of the insert in flat file block storage.
Improve the stability of the project.
> Remove redefinitions of redundant method in flat file storage

- irohad/torii/impl/command_service_transport_grpc.cpp
- irohad/torii/impl/query_service.cpp
- libs/common/run_loop_handler.hpp
Block streaming is done in client's gRPC thread.
Less additional threads are spawned.
unknown
just copy the whole line
```bash
ctest -R cache_test --output-on-failure && ctest -R command_sync_client_test --output-on-failure && ctest -R command_service_test --output-on-failure && ctest -R command_service_replay_test --output-on-failure && ctest -R torii_service_query_test --output-on-failure && ctest -R query_service_test --output-on-failure && ctest -R torii_queries_test --output-on-failure && ctest -R torii_transport_command_test --output-on-failure && ctest -R mst_net_input_test --output-on-failure && ctest -R port_guard_test --output-on-failure && ctest -R set_account_quorum_test --output-on-failure && ctest -R get_role_permissions_test …
```
> Refactor block streaming method

- irohad/main/application.cpp
- irohad/main/application.hpp
- irohad/torii/impl/query_service.cpp
- irohad/torii/query_service.hpp
- shared_model/validators/blocks_query_validator.hpp
- shared_model/validators/protobuf/proto_query_validator.cpp
- shared_model/validators/protobuf/proto_query_validator.hpp
- test/fuzzing/find_fuzz.cpp
- test/module/irohad/torii/query_service_test.cpp
- test/module/irohad/torii/torii_queries_test.cpp
- test/module/irohad/torii/torii_service_query_test.cpp
Remove legacy code.
A step towards bug resolution with maximum batch size.
Unknown
query_service_test
find_fuzzing
torii_queries_test
torii_service_query_test
> Replace TransportBuilder with ProtoBlocksQueryFactory in QueryService

- CONTRIBUTING.md
This pull request contains additional contribution docs on how to submit discovered vulnerabilities. 
More docs.
None
> Add info about vulnerabilities

- CMakeLists.txt
Now СMake scripts delete from coverage report:
- tests
- Xcode libraries
- build and external files
More precise coverage data 
None
```
cmake -H. -Bbuild -DCOVERAGE=ON;
cmake --build build -- -j8;
cmake --build build --target coverage.init.info;
cd build;
ctest .;
cd ..;
cmake --build build --target coverage.info;
genhtml ./build/reports/coverage.info --output-directory out
```
> Fix coverage generation on macOS

- test/framework/integration_framework/fake_peer/behaviour/behaviour.cpp
- test/framework/integration_framework/fake_peer/behaviour/behaviour.hpp
- test/framework/integration_framework/fake_peer/behaviour/honest.cpp
- test/framework/integration_framework/fake_peer/fake_peer.cpp
- test/framework/integration_framework/fake_peer/fake_peer.hpp
- test/framework/integration_framework/fake_peer/network/mst_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/mst_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/on_demand_os_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/ordering_gate_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/ordering_gate_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/ordering_service_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/ordering_service_network_notifier.hpp
- test/framework/integration_framework/fake_peer/network/yac_network_notifier.cpp
- test/framework/integration_framework/fake_peer/network/yac_network_notifier.hpp
- test/framework/integration_framework/fake_peer/proposal_storage.cpp
- test/framework/integration_framework/fake_peer/proposal_storage.hpp
- test/framework/integration_framework/integration_test_framework.cpp
- test/framework/integration_framework/integration_test_framework.hpp
- test/framework/integration_framework/iroha_instance.cpp
- test/integration/acceptance/fake_peer_example_test.cpp
Rewrote the test...
...to fix an unidentified bug and to improve the test logic.
> Fix itf fake peers on demand ordering test

- irohad/ametsuchi/impl/storage_impl.cpp
Print notices from postgres to spdlog instead of std::cerr
Logging is controlled consistently with other logs
`reinterpret_cast`...
> Redirect postgres log messages to spdlog
